### ISSUE TITLE
Build Pipeline fails when trying to run tests: "Cannot open page 130455"

### ISSUE THREAD

**Issue by CriticalMax** [microsoft/navcontainerhelper#1017]
Hey Freddy, our build pipeline has been failing since wednesday. We have not made changes to any tests afaik. The pipeline always removes the container when finished and the url and company name also stay the same (of course they vary between agents).

Seems kinda similar to #858, we do not get the timezone warning however.

**Scripts used to create container and cause the issue**
```
New-NavContainer -accept_eula `
            -accept_outdated `
            -containerName $ContainerName `
            -imageName $ImageName `
            -licenseFile $LicenseFile `
            -isolation $Isolation `
            -Credential $credentials `
            -auth $Auth `
            -enableSymbolLoading:$EnableSymbolLoading `
            -doNotExportObjectsToText `
            -alwaysPull `
            -additionalParameters $additionalParameters `
            -memoryLimit $RAM `
            -assignPremiumPlan `
            -shortcuts "None" `
            -useBestContainerOS `
            -updateHosts `
            -myScripts $myscripts

Import-TestToolkitToNavContainer -containerName $ContainerName -sqlCredential $sqlcredentials -includeTestLibrariesOnly

Image used is : "mcr.microsoft.com/businesscentral/sandbox:de-ltsc2019".
Nothing gets passed to myScripts and additionParameters should look like this:

@("--volume ""$($RepoPath):C:\app""",
            '-e CustomNavSettings=ServicesUseNTLMAuthentication=true',
            "-e CustomNavSettings=EnableTaskScheduler=False"
)

The other params should be filled corectly, and because the container gets created successfully I don't think the container creation is the problem. Please correct me if I'm wrong ^^.
```

**Output of create container**
```
Using passed password and NavUserPassword authentication
NavContainerHelper is version 0.7.0.1
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Removing container FirstDude3
Removing FirstDude3 from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\FirstDude3
Pulling image mcr.microsoft.com/businesscentral/sandbox:de-ltsc2019
de-ltsc2019: Pulling from businesscentral/sandbox
Using image mcr.microsoft.com/businesscentral/sandbox:de-ltsc2019
Creating Container FirstDude3
Version: 16.2.13509.13794-de
Style: sandbox
Platform: 16.0.13440.13772
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.1282 (ltsc2019)
A better Generic Container OS exists for your host (mcr.microsoft.com/dynamicsnav:10.0.17763.1217-generic)
Using generic image mcr.microsoft.com/dynamicsnav:10.0.17763.1217-generic
Pulling image mcr.microsoft.com/dynamicsnav:10.0.17763.1217-generic
10.0.17763.1217-generic: Pulling from dynamicsnav
Digest: sha256:5b8154025522b66f8e2a41b89e49083feea7fd4cbc6dd844cd5057656dc8a898
Generic Container OS Version: 10.0.17763.1217 (ltsc2019)
Generic Tag of better generic: 0.1.0.1
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale de-DE
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file ***
Downloading C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\my\license.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container FirstDude3 from image mcr.microsoft.com/dynamicsnav:10.0.17763.1217-generic
fdca148fd2541b7cc58cb76c06dcf938900bb30559eec7f61378d57a2e132082
Waiting for container FirstDude3 to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.*
Copying ReportBuilder
Changing Database Server Collation to Latin1_General_100_CS_AS
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 274 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.18.96.1 in container hosts file
Starting Container
Hostname is FirstDude3
PublicDnsName is FirstDude3
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint E43D4478D4926041931EB168FA74C4A611213F98
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to False
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating *** as SQL User and add to sysadmin
Container Dns Name  : FirstDude3
Web Client          : http://FirstDude3/BC/
Dev. Server         : http://FirstDude3
Dev. ServerInstance : BC
Setting FirstDude3 to 172.18.110.100 in host hosts file

Files:
http://FirstDude3:8080/ALLanguage.vsix

Initialization took 237 seconds
Ready for connections!
Reading CustomSettings.config from FirstDude3
Container FirstDude3 successfully created
Copy from container FirstDude3 (C:\ProgramData\NavContainerHelper\Extensions\onprem-Applications-16.2.13509.13794-de\Microsoft_Any_16.2.13509.13794.runtime.app) to C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_Any_16.2.13509.13794.runtime.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_Any_16.2.13509.13794.runtime.app
Synchronizing Any on tenant default
Installing Any on tenant default
App successfully published
Copy from container FirstDude3 (C:\ProgramData\NavContainerHelper\Extensions\onprem-Applications-16.2.13509.13794-de\Microsoft_Library Assert_16.2.13509.13794.runtime.app) to C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_Library Assert_16.2.13509.13794.runtime.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_Library Assert_16.2.13509.13794.runtime.app
Synchronizing Library Assert on tenant default
Installing Library Assert on tenant default
App successfully published
Copy from container FirstDude3 (C:\ProgramData\NavContainerHelper\Extensions\onprem-Applications-16.2.13509.13794-de\Microsoft_Test Runner.runtime.app) to C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_Test Runner.runtime.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_Test Runner.runtime.app
Synchronizing Test Runner on tenant default
Installing Test Runner on tenant default
App successfully published
Copy from container FirstDude3 (C:\ProgramData\NavContainerHelper\Extensions\onprem-Applications-16.2.13509.13794-de\Microsoft_System Application Test Library_16.2.13509.13794.runtime.app) to C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_System Application Test Library_16.2.13509.13794.runtime.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_System Application Test Library_16.2.13509.13794.runtime.app
Synchronizing System Application Test Library on tenant default
Installing System Application Test Library on tenant default
App successfully published
Copy from container FirstDude3 (C:\ProgramData\NavContainerHelper\Extensions\onprem-Applications-16.2.13509.13794-de\Microsoft_Tests-TestLibraries_16.2.13509.13794.runtime.app) to C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_Tests-TestLibraries_16.2.13509.13794.runtime.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\_Microsoft_Tests-TestLibraries_16.2.13509.13794.runtime.app
Synchronizing Tests-TestLibraries on tenant default
Installing Tests-TestLibraries on tenant default
App successfully published
TestToolkit successfully imported
...
```

**Output of Test task**
```
Message : An error has occurred
Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\PsTestTool-6 and retry. You might also have URL or Company name wrong.
at Get-Tests, C:\ProgramData\NavContainerHelper\Extensions\FirstDude3\PsTestTool-6\PsTestFunctions.ps1: line 159
at <ScriptBlock>, <No file>: line 55
```

**Comment by Spycoclown** [comment]
Hi,
your Test User need these extra permission to work properly:
```
<Permission>
      <ObjectType>0</ObjectType>
      <ObjectID>130450</ObjectID>
      <ReadPermission>Yes</ReadPermission>
      <InsertPermission>Yes</InsertPermission>
      <ModifyPermission>Yes</ModifyPermission>
      <DeletePermission>Yes</DeletePermission>
      <ExecutePermission>0</ExecutePermission>
      <SecurityFilter />
    </Permission>
    <Permission>
      <ObjectType>0</ObjectType>
      <ObjectID>130451</ObjectID>
      <ReadPermission>Yes</ReadPermission>
      <InsertPermission>Yes</InsertPermission>
      <ModifyPermission>Yes</ModifyPermission>
      <DeletePermission>Yes</DeletePermission>
      <ExecutePermission>0</ExecutePermission>
      <SecurityFilter />
    </Permission>
    <Permission>
      <ObjectType>0</ObjectType>
      <ObjectID>2000000201</ObjectID>
      <ReadPermission>Yes</ReadPermission>
      <InsertPermission>Yes</InsertPermission>
      <ModifyPermission>Yes</ModifyPermission>
      <DeletePermission>Yes</DeletePermission>
      <ExecutePermission>0</ExecutePermission>
      <SecurityFilter />
    </Permission>
```
I had the same problems before.

**Comment by CriticalMax** [comment]
Update: Seems like this error only occurs when many apps are installed and tested. I can't give exact numbers though. Has something changed regarding the Test Page?

**Comment by freddydk** [comment]
Could you try to run the tests with -debugMode and dump the full output here?

**Comment by CriticalMax** [comment]
Unfortunately I can't. Seems like the tests don't even get loaded.
We have a hunch why that is and are investigating this atm. Could be because of a partner app which blocks the login for unknown reasons ...
Will update you when we know more!

**Comment by freddydk** [comment]
-debugMode on run-testsInNavContainer might still reveal output as to why this happens, but you might be right in the above.
Run-Tests will basically open a web client connection and run the test (through a UI Web Services backend) - if you prep everything and open the Web Client as the same user - you might see the dialog in question?
or use the Get-EventLogFromBcContainer to get the event log to see what he problem is

**Comment by RafaelKoch** [comment]
Opening the client fails also, with a whole bunch of things surfacing in the event log. We never get to see anything in the client, after the login screen it sends us directly to "something went wrong".

We have contacted the partner to have a look. All was well in CU1 but breaks down in CU2, apparently.

I am almost convinced this entire thing is not related to navcontainerhelper or even nav-docker.

This is one exemplary thing from the event log, seems this happens often:

```txt
The description for Event ID 705 from source MicrosoftDynamicsNavServer$BC cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: BC
Category: Runtime
ClientSessionId: 8a4be1ed-e789-4dbd-81eb-433dce2b4772
ClientActivityId: d7970388-e782-4a01-800b-77605073289f
ServerSessionUniqueId: ba265c53-083d-497d-8a4e-5946989d3767
ServerActivityId: bf4ac4ef-ce42-4987-8c8b-82368ceca05c
EventTime: 06/15/2020 08:07:49
Message (UnauthorizedAccessException): This message had personal data removed. The original may still be in transient telemetry. Find it using the transientTelemetryId.
RootException: UnauthorizedAccessException
ExceptionStackTrace:
   at System.IO.MemoryStream.GetBuffer()
   at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.CleanStreamFromInvalidChars(MemoryStream content)
   at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.CreateNavigationData(MemoryStream content)
   at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.TryGetNavigationDataFromDatabase(NavAppRuntimeMetadata appRuntimeMetadata, NavDiagnostics diagnostics, NavigationDefinition& navigationDefinition)
   at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.GetNavigationData(NavAppGroup appGroup, NavDiagnostics diagnostics)
   at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.FillDepartmentWithNavigationData(NavAppGroup appGroup, ActionContainerDefinition departments, NavDiagnostics diagnostics)
   at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.ConstructDepartmentCacheEntry(NavAppGroup appGroup, NavDiagnostics diagnostics)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.CachedDepartmentOrConstructNew(NavAppGroup appGroup, NavDiagnostics diagnostics)
   at Microsoft.Dynamics.Nav.XmlMetadata.NavigationDataAggregator.AppendExtensionNavigationData(NavigationDefinition existingDefinitions, NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetNavigationDepartments(NavAppGroup appGroup)
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetNavigationFrame(Int32 homepageId, Boolean applyPersonalization)
   at Microsoft.Dynamics.Nav.XmlMetadata.MetadataProvider.GetNavigationFrame(Boolean applyPersonalization, NavProfileKey profileKey)
   at SyncInvokeGetNavigationFrame(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(Boolean& alreadyResumedNoLock)
   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProcessing(IResumeMessageRpc resume)
   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

ProcessId: 332
Tag: 00000HC
ThreadId: 56
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: eddb3d6c-f713-4133-b2ca-8c3b3e14eefa
```

**Comment by RafaelKoch** [comment]
Partner can repro, I will close this issue and sorry for bothering You!

**Comment by RafaelKoch** [comment]
Oh... I can't close because Max opened it -> Please be so kind and close this!
