### ISSUE TITLE
Attaching a Extracted Database from another container to a new container

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/navcontainerhelper#1162]
**Describe the issue**
I have extracted a database from a running container and placed that database on VM local path e.g C\temp\hostedpath.
Now trying to use that database on a new container so that i can have the development data with in newly created container.

**Scripts used to create container and cause the issue**
```


$path = "c:\temp\hostdbfolder"


$attachdbSetupDatabaseScript = "https://raw.githubusercontent.com/Microsoft/nav-docker/master/override/attachdb/SetupDatabase.ps1"


# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true
$containername = 'BCDev17-2'
$appbacpacuri = ''
$tenantbacpacuri = ''
$sasToken = "kajbscvukshac"
$artifactUrl = Get-BCArtifactUrl -country us -storageAccount bcinsider -sasToken $sasToken
$licensefile = 'C:\Users\dockeradmin\Documents\V16_20_JUL.flf'

if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}
$additionalParameters = @("--publish 8083:8083","--env WebServerInstance=BCDev3",
"--publish 10049:10049","--volume $path\databases:c:\mydb")  

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -memoryLimit 5GB `
                 -Credential $credential `
                 -includeAL:$true `
                 -alwaysPull `
                 -usessl:$false `
                 -licenseFile:$licensefile `
                 -artifactUrl:$artifactUrl `
                 -updateHosts `
                 -myScripts @($attachdbSetupDatabaseScript) `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -DeveloperServicesPort 10049 `
                 -WebClientPort 8083 `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password



```

**Full output of scripts**
```

NavContainerHelper is version 0.7.0.20
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.14393.3750-generic
10.0.14393.3750-generic: Pulling from dynamicsnav
Using image mcr.microsoft.com/dynamicsnav:10.0.14393.3750-generic
Downloading application artifact /sandbox/17.0.15019.0/us
Downloading C:\Users\dockeradmin\AppData\Local\Temp\9507f281-6e64-4ba6-a56c-70c73686d1a2.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/17.0.15019.0/platform
Downloading C:\Users\dockeradmin\AppData\Local\Temp\018783ce-2893-4b37-bb05-f69ee4b12bd9.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\17.0.15019.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSD
Kv25.msi
Downloading c:\bcartifacts.cache\sandbox\17.0.15019.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\sandbox\17.0.15019.0\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHostin
g.exe
Creating Container BCDev17-2
Version: 17.0.15019.0-US
Style: sandbox
Platform: 16.0.15014.0
Generic Tag: 0.1.0.7
Container OS Version: 10.0.14393.3750 (ltsc2016)
Host OS Version: 10.0.14393.3750 (ltsc2016)
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\NavContainerHelper\Extensions\BCDev17-2\my\SetupDatabase.ps1
Using license file C:\Users\dockeradmin\Documents\ V16_20_JUL.flf
Additional Parameters:
--publish 8083:8083
--env WebServerInstance=BCDev3
--publish 10049:10049
--volume c:\temp\hostdbfolder\databases:c:\mydb
Files in C:\ProgramData\NavContainerHelper\Extensions\BCDev17-2\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupDatabase.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BCDev17-2 from image mcr.microsoft.com/dynamicsnav:10.0.14393.3750-generic
1f0c7f03cd557a14ce5977f12db8056f8aad14bec78155261145c10e21349e87
Waiting for container BCDev17-2 to be ready
Using artifactUrl https://bcinsider.azureedge.net/sandbox/17.0.15019.0/us
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copying ConfigurationPackages
Copying Extensions
Copying Applications.*
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.*
Copying ReportBuilder
Determining Database Collation
Changing Database Server Collation to Latin1_General_100_CS_AS
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 221 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.28.64.1 in container hosts file
Starting Container
Hostname is BCDev17-2
PublicDnsName is BCDev17-2
Using NavUserPassword Authentication
Attaching database in C:\mydb\Financialsus.mdf/C:\mydb\Financialsus.ldf as MYCRONUS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 01EC768B471A4060424394A5BE22F6E27FAD8651
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 147
at <ScriptBlock>, C:\Run\start.ps1: line 223
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcinsider.azureedge.net/sandbox/17.0.15019.0/us
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copying ConfigurationPackages
Copying Extensions
Copying Applications.*
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.*
Copying ReportBuilder
Determining Database Collation
Changing Database Server Collation to Latin1_General_100_CS_AS
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 221 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.28.64.1 in container hosts file
Starting Container
Hostname is BCDev17-2
PublicDnsName is BCDev17-2
Using NavUserPassword Authentication
Attaching database in C:\mydb\Financialsus.mdf/C:\mydb\Financialsus.ldf as MYCRONUS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 01EC768B471A4060424394A5BE22F6E27FAD8651
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 147
at <ScriptBlock>, C:\Run\start.ps1: line 223
at <ScriptBlock>, <No file>: line 1
Initialization of container BCDev17-2 failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.20\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...CDev17-2 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BCDev17-2 failed
...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

Thanks
SUD

**Comment by freddydk** [comment]
Use Get-NavContainerEventLog to extract the event log and see what reason the service tier gives for not starting?

**Comment by SUD-D365** [comment]
Hi @freddydk ,

Event log error is indicating that database must be converted before using it with this version of Business central.
```
The description for Event ID 701 from source MicrosoftDynamicsNavServer$BC cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: BC
Category: Runtime
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 66b76963-ed55-48da-9934-5f2ae7110dd6
EventTime: 07/27/2020 04:26:47
Message (NavSqlException): RootException: NavSqlException
The MYCRONUS database on the LOCALHOST\SQLEXPRESS server must be converted by using the Invoke-NAVApplicationDatabaseConversion cmdlet before you can use it with this version of Dynamics 365 Business Central.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseProperties.CheckDatabaseVersion()
   at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnection(Int32 attemptCount)
   at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey, Boolean isNewDatabase)
   at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSingleLegacyTenant(String databaseServerName, String databaseName, String databaseUserName, ProtectedDatabasePassword databasePassword, EncryptionProvider encryptionProvider, AzureKeyVaultSettings azureKeyVaultSettings)
   at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.ConfigureTenants(ServerUserSettings settings, String encryptionKey)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)


ProcessId: 19884
Tag: 00008NE
ThreadId: 1
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

```

Thanks
SUD

**Comment by freddydk** [comment]
That is what I assumed.

**Comment by SUD-D365** [comment]
Can you please suggest, what would be the possible solution for this?

**Comment by freddydk** [comment]
This is the same as converting a database in a non-docker scenario.
I believe you can find documentation on how to do these things.
