### ISSUE TITLE
Run-TestsInBCContainer throws error "Cannot open page 130455"

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#1317]
### Issue description
With **Run-TestsInBCContainer** I want to run all tests in the DEFAULT test suite. When executing the scripts it throws the following error:

```
Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\NavContainerHelpe
r\Extensions\BC163NPupW1\PsTestTool-6 and retry. You might also have URL or Company name wrong.
at Run-Tests, C:\ProgramData\NavContainerHelper\Extensions\BC163NPupW1\PsTestTool-6\PsTestFunctions.ps1: line 316
at <ScriptBlock>, <No file>: line 57
Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\NavContainerHelp
er\Extensions\BC163NPupW1\PsTestTool-6 and retry. You might also have URL or Company name wrong.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\AppHandling\Run-TestsInNavContainer.ps1:415 char:17
+                 throw $_.Exception.Message
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot open pag...any name wrong.:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder  
   C:\ProgramData\NavContainerHelper\Extensions\BC163NPupW1\PsTestTool-6 and retry. You might also have URL or Company name wrong.
```
Page 130455, however does reside in the database. **So, questions is what causes this error**?

I have been searching through the various existing issues here that relate to "Cannot open page 130455", but I was not able to determine a solution in them.
As a workaround I have run all the tests in DEFAULT suite from the **AL Test Tool** "manually" without any (technical) problem.

The database is a restored backup of a client with their solution, development license and all test apps installed in it.

### Scripts used to run the tests
```
# container name
$containerName = 'BC163NPupW1-2'
$xunitResultsFile = "c:\programdata\navcontainerhelper\results.xml"

# set credentials for using with NavUserPassword
$login = '.....'
$password = '....'
$securepassword = (ConvertTo-SecureString -String $password -AsPlainText -Force)
$credential = New-Object System.Management.Automation.PSCredential($login, $securepassword)

Run-TestsInBCContainer `
    -containerName $containerName `
    -credential $credential `
    -testSuite 'DEFAULT' `
    -detailed `
    -XUnitResultFileName $xunitResultsFile `
    -debugMode
```
### Debugmode output (including error)
```
Run-Tests, open page 130455
Title: Dialog 
Title: 8da61efd-0002-0003-0507-0b0d1113171d
[
    {
        "type":  "ClientGroupControl",
        "mappingHint":  "GROUP",
        "name":  "contentGroupControl",
        "children":  [
                         {
                             "type":  "ClientGroupControl",
                             "mappingHint":  "LAYOUTGROUP",
                             "name":  "",
                             "children":  [
                                              {
                                                  "identifier":  "",
                                                  "name":  "Info",
                                                  "type":  "ClientImageControl"
                                              },
                                              {
                                                  "type":  "ClientStaticStringControl",
                                                  "name":  "",
                                                  "value":  "The current environment is not set as production.\r\nSome external integrations 
are handled differently in this mode. You can change this in page \"NP Retail Setup\"",
                                                  "identifier":  ""
                                              }
                                          ],
                             "caption":  "",
                             "identifier":  "{B178ABC5-D511-462e-B8D1-D08C35BC1113}"
                         }
                     ],
        "caption":  "",
        "identifier":  "{2DD9E973-CD11-40a0-B5CF-6414BD1D3550}"
    },
    {
        "type":  "ClientGroupControl",
        "mappingHint":  "ACTIONBAR",
        "name":  "",
        "children":  [
                         {
                             "caption":  "OK",
                             "type":  "ClientActionControl",
                             "name":  "{B594146A-9CEF-4767-AE76-E9721CD6FB50}",
                             "identifier":  "{B594146A-9CEF-4767-AE76-E9721CD6FB50}"
                         }
                     ],
        "caption":  "",
        "identifier":  "{6B823A4C-719E-4833-975A-1BEFDCBDF389}"
    }
]
Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\NavContainerHelpe
r\Extensions\BC163NPupW1-2\PsTestTool-6 and retry. You might also have URL or Company name wrong.
at Run-Tests, C:\ProgramData\NavContainerHelper\Extensions\BC163NPupW1-2\PsTestTool-6\PsTestFunctions.ps1: line 316
at <ScriptBlock>, <No file>: line 57
at Run-Tests, C:\ProgramData\NavContainerHelper\Extensions\BC163NPupW1-2\PsTestTool-6\PsTestFunctions.ps1: line 316
at <ScriptBlock>, <No file>: line 57
Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\NavContainerHelp
er\Extensions\BC163NPupW1-2\PsTestTool-6 and retry. You might also have URL or Company name wrong.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\AppHandling\Run-TestsInNavContainer.ps1:415 char:17
+                 throw $_.Exception.Message
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot open pag...any name wrong.:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder  
   C:\ProgramData\NavContainerHelper\Extensions\BC163NPupW1-2\PsTestTool-6 and retry. You might also have URL or Company name wrong.
```
### Scripts used to create container
```
# set accept_eula to $true to accept the eula found here: https://go.microsoft.comfwlink/?linkid=861843
$accept_eula = $true
$accept_outdated = $true

# container name and version
$containerName = 'BC163NPupW1-2'
$artifactUrl = Get-BCArtifactUrl -type OnPrem -country "w1" -version "16.3"

# set credentials for using with NavUserPassword
$login = '.....'
$password = '.....'
$securepassword = (ConvertTo-SecureString -String $password -AsPlainText -Force)
$credential = New-Object System.Management.Automation.PSCredential($login, $securepassword)

$navContainerHelperConfig.genericImageName = 'mcr.microsoft.com/dynamicsnav:{0}-generic-dev'

$bakfile = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\MyDatabase.bak'
    
New-BCContainer -accept_eula:$accept_eula `
                -accept_outdated:$accept_outdated `
                -containerName $containerName `
                -artifactUrl $artifactUrl `
                -auth UserPassword `
                -credential $credential `
                -memoryLimit:10GB `
                -updateHost `
                -shortcuts StartMenu `
                -bakFile $bakfile `
                -dumpEventLog
```

### Output of New-BCContainer
```
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 18.09.1
Docker Server Version is 18.09.1
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic-dev
Creating Container BC163NPupW1-2
Version: 16.3.14085.14238-w1
Style: onprem
Platform: 16.0.14073.14195
Generic Tag: 0.1.0.21
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using locale en-US
Using process isolation
Files in C:\ProgramData\NavContainerHelper\Extensions\BC163NPupW1-2\my:
- AdditionalOutput.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC163NPupW1-2 from image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic-dev
ffde34993d4f00424d91f1f1fbc09a415df4c59ecb78b7eb517f8a65c6ceb0b7
Waiting for container BC163NPupW1-2 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.3.14085.14238/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Installation took 18 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.178.92 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.178.92 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.28.16.1 in container hosts file
Starting Container
Hostname is BC163NPupW1-2
PublicDnsName is BC163NPupW1-2
Using NavUserPassword Authentication
Using Database .bak file 'C:\ProgramData\NavContainerHelper\Extensions\BC163NPupW1-2\database.bak'
Using database server localhost\SQLEXPRESS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6B66A0DA63DB55E192509C07ADB2BBEB72B2BCAD
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Creating NP424246 as SQL User and add to sysadmin
Container IP Address: 172.28.30.132
Container Hostname  : BC163NPupW1-2
Container Dns Name  : BC163NPupW1-2
Web Client          : http://BC163NPupW1-2/BC/
Dev. Server         : http://BC163NPupW1-2
Dev. ServerInstance : BC
Setting BC163NPupW1-2 to 172.28.30.132 in host hosts file

Files:
http://BC163NPupW1-2:8080/ALLanguage.vsix

Initialization took 98 seconds
Ready for connections!
Starting EventLog Monitor
Monitoring EventSources from EventLog[Application]:
- MicrosoftDynamicsNAVClientClientService
- MicrosoftDynamicsNAVClientWebClient
- MicrosoftDynamicsNavServer$BC
- MSSQL$SQLEXPRESS

Reading CustomSettings.config from BC163NPupW1-2
Creating Desktop Shortcuts for BC163NPupW1-2
Container BC163NPupW1-2 successfully created
```
### Error in event log
```
The description for Event ID 216 from source MicrosoftDynamicsNavServer$BC cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: BC
Tenant ID: default
Environment Name: 
Environment Type: Production
Session type: Background
Session ID: 25
User: 
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLDialogException
AutomationId: 8da61efd-0002-0003-0507-0b0d1113171d
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: True
DiagnosticsSuppress: False
DiagnosticsMessage: Use ERROR with a text constant to improve telemetry details
MessageWithoutPrivateInformation: Use ERROR with a text constant to improve telemetry details
SuppressExceptionCreatedEvent: False
FatalityScope: Call
ErrorLevel: Error
Message: Error when downloading dependencies from ground control: 
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavDialog.ALError(Guid automationId, String message, NavValue[] values)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6014627.OnRun_Scope.OnRun()
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6014627.OnRun(INavRecordHandle εrec)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.DoRun(DataError errorLevel, NavRecord record)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.InvokeRun(Int32 objectId, Object[] args)
     at Microsoft.Dynamics.Nav.Runtime.ALSession.RunCodeunitAndDisposeSession(NavSession session, Int32 codeUnitId, NavRecord record)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavDialog.ALError(Guid automationId, String message, NavValue[] values)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6014627.OnRun_Scope.OnRun()
     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit6014627.OnRun(INavRecordHandle εrec)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.DoRun(DataError errorLevel, NavRecord record)
     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.InvokeRun(Int32 objectId, Object[] args)
     at Microsoft.Dynamics.Nav.Runtime.ALSession.RunCodeunitAndDisposeSession(NavSession session, Int32 codeUnitId, NavRecord record)

The request is not supported
```
Hope I have provided all the info of meaning.

**Comment by freddydk** [comment]
What is the company name in the database?
Do you have more than one company?

**Comment by freddydk** [comment]
Also, you should shift to BcContainerHelper when the time is right (= when you don't have any containers running) - I am not fixing anything in NavContainerHelper anymore and issues found by people are only fixed in BcContainerHelper.

**Comment by lvanvugt** [comment]
> What is the company name in the database?
It's w1 database so **Cronus International Ltd.**
> Do you have more than one company?
Nope, only Cronus
> Then maybe specify the companyname as a parameter to run-testsinNavContainer
Will try anyway.

**Comment by lvanvugt** [comment]
> 
> 
> Also, you should shift to BcContainerHelper when the time is right (= when you don't have any containers running) - I am not fixing anything in NavContainerHelper anymore and issues found by people are only fixed in BcContainerHelper.

I know, but hadn't had time to that yet. ;-)

**Comment by freddydk** [comment]
You wrote: _As a workaround I have run all the tests in DEFAULT suite from the AL Test Tool "manually" without any (technical) problem._

What does "technical" mean here?
Did you have any issues?
A dialog?
An Error?

**Comment by lvanvugt** [comment]
> You wrote: _As a workaround I have run all the tests in DEFAULT suite from the AL Test Tool "manually" without any (technical) problem._
> 
> What does "technical" mean here?

Ouch, I was thinking while writing this might lead to a question. It means that there were no issues like the ones I am mentioning above. But there were a lot of failing tests (and that was expected)
> Did you have any issues?

The test errors. ;-) Nothing else.

**Comment by lvanvugt** [comment]
BTW: just reran Run-TestsInBCContainer with company name provided and still same issue.

**Comment by freddydk** [comment]
Can you find the location in the app, where this error pops up:

The current environment is not set as production.
Some external integrations are handled differently in this mode. You can change this in page "NP Retail Setup"

It looks like this dialog pops up and is unhandled.

**Comment by lvanvugt** [comment]
Great catch. How did you find out? In all the data (above) I could not find anything. Have been trying and searching for days.

**Comment by freddydk** [comment]
You asked how I saw that - in the debugmode output it displays what windows are open at the time of the error. There is a dialog:
![image](https://user-images.githubusercontent.com/10775043/94651565-ef029180-02f8-11eb-9e9e-60117a8fbe7e.png)

**Comment by lvanvugt** [comment]
Yep, and I saw it some minutes later. As said: "Thanx for your clear view." And sorry for bothering for apparently something so obvious. I have been looking at it over a couple of days and just did not see (or know where to look). Now I surely do.
