### ISSUE TITLE
Login in WebClient fails - AntiforgeryValidationException

### ISSUE THREAD

**Issue by mmenninghaus** [microsoft/navcontainerhelper#1328]
**Describe the issue**
After successfully starting a container, a login fails due to an unknown error. The webclient either states, that "something went wrong" or that the tenant NAV could not be found. This happens for any artifactURL/container on that machine. 

**Scripts used to create container and cause the issue**
```
New-NavContainer -accept_eula -licenseFile 'DEVLICENCEFILE,' -containerName urlaubsmodul -artifactURL 'https://bcartifacts.azureedge.net/sandbox/17.0.16993.0/w1' -doNotExportObjectsToText -TimeZoneId (Get-TimeZone).Id -shortcuts "Desktop" -alwaysPull -updateHosts -useBestContainerOS -accept_outdated -Credential (Get-Credential) -auth 'UserPassword'
```

**Full output of scripts**
```
BcContainerHelper is version 1.0.6
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.13
Docker Server Version is 19.03.13
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
10.0.19041.508-generic: Pulling from dynamicsnav
Digest: sha256:fe59dd46714fa8ec5ed9ca0dbd16fe050f15959c7108ba42f623a5ccbbfd95d3
Status: Image is up to date for mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
Creating Container urlaubsmodul
Version: 17.0.16993.0-W1
Style: sandbox
Multitenant: Yes
Platform: 17.0.16974.0
Generic Tag: 0.1.0.21
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file DEVLICENCEFILE
Files in C:\ProgramData\BcContainerHelper\Extensions\urlaubsmodul\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container urlaubsmodul from image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
bb691b99f37798b35be2c77b144e42ab286cd3cc88f0006f5d81d0d050b7a8cf
Waiting for container urlaubsmodul to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/17.0.16993.0/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\17.0.16993.0\w1\BusinessCentral-W1.bak
Restoring CRONUS Demo Database
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Starting Business Central Service Tier
Importing license file
Copying Database on localhost\SQLEXPRESS from tenant to default
Taking database tenant offline
Copying database files
Attaching files as new Database default
Putting database tenant back online
Mounting tenant database
Mounting Database for default on server localhost\SQLEXPRESS
Sync'ing Tenant
Tenant is Operational
Stopping Business Central Service Tier
Installation took 246 seconds
Installation complete
Initializing...
Setting host.docker.internal to 172.17.35.44 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 172.17.35.44 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.28.16.1 in container hosts file
Starting Container
Hostname is urlaubsmodul
PublicDnsName is urlaubsmodul
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint FD02525D8673E2D2BE635653D5381E2C0B5E672C
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Enabling rewrite rule: Don't rewrite system files
Enabling rewrite rule: Already have tenant specified
Enabling rewrite rule: Hostname (without port) to tenant
Using license file 'c:\run\my\license.flf'
Import License
Dismounting Tenant
Mounting Tenant
Mounting Database for default on server localhost\SQLEXPRESS
Sync'ing Tenant
Tenant is Operational
Creating http download site
Setting SA Password and enabling SA
Creating fbrueck as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.28.19.130
Container Hostname  : urlaubsmodul
Container Dns Name  : urlaubsmodul
Web Client          : http://urlaubsmodul/BC/?tenant=default
Dev. Server         : http://urlaubsmodul
Dev. ServerInstance : BC
Dev. Server Tenant  : default
Setting urlaubsmodul to 172.28.19.130 in host hosts file
Setting urlaubsmodul-default to 172.28.19.130 in host hosts file

Files:
http://urlaubsmodul:8080/ALLanguage.vsix

Initialization took 60 seconds
Ready for connections!
Reading CustomSettings.config from urlaubsmodul
Set TimeZone in Container to W. Europe Standard Time
Creating Desktop Shortcuts for urlaubsmodul
Container urlaubsmodul successfully created
```

**EventLog**
Two Errors are logged when trying to log in in the WebClient:

```
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavTenantNotFoundException
Message: The tenant 'urlaubsmodul' is not mounted or does not exist.
StackTrace:
   at Microsoft.Dynamics.Nav.Client.FaultExceptionHelperClass.ConvertException(Exception ex, Func`1 productNameProvider, NavClientCredentialType credentialType) in s:\repo\src\platform\client\Shared\Prod.Client.ServiceConnection\FaultExceptionHelperClass.cs:line 321
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectFailedEventArgs connectFailedArgs, ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, SpnSetting spnSettingToTry, Boolean allowSpnSettingsSwap, UserSettings& userSettings) in s:\repo\src\platform\client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 349
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectFailedEventArgs connectFailedArgs, ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, SpnSetting spnSettingToTry, Boolean allowSpnSettingsSwap, UserSettings& userSettings) in s:\repo\src\platform\client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 371
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, UserSettings& userSettings) in s:\repo\src\platform\client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 217
   at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult,TChannel](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`3 operationWithContext, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\platform\client\web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 279
Source: Microsoft.Dynamics.Nav.Client.ServiceConnection----------------------------------
Type: System.ServiceModel.Security.MessageSecurityException
Message: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
StackTrace:

Server stack trace: 
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.ProcessReply(Message reply, SecurityProtocolCorrelationState correlationState, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionSecurityTokenProvider.DoOperation(SecuritySessionOperation operation, EndpointAddress target, Uri via, SecurityToken currentToken, TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionSecurityTokenProvider.GetTokenCore(TimeSpan timeout)
   at System.IdentityModel.Selectors.SecurityTokenProvider.GetToken(TimeSpan timeout)
   at System.ServiceModel.Security.SecuritySessionClientSettings`1.ClientSecuritySessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ReliableChannelBinder`1.ChannelSynchronizer.SyncWaiter.TryGetChannel()
   at System.ServiceModel.Channels.ReliableChannelBinder`1.ChannelSynchronizer.SyncWaiter.TryWait(TChannel& channel)
   at System.ServiceModel.Channels.ReliableChannelBinder`1.ChannelSynchronizer.TryGetChannel(Boolean canGetChannel, Boolean canCauseFault, TimeSpan timeout, MaskingMode maskingMode, TChannel& channel)
   at System.ServiceModel.Channels.ReliableChannelBinder`1.Send(Message message, TimeSpan timeout, MaskingMode maskingMode)
   at System.ServiceModel.Channels.SendReceiveReliableRequestor.OnRequest(Message request, TimeSpan timeout, Boolean last)
   at System.ServiceModel.Channels.ReliableRequestor.Request(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientReliableSession.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientReliableDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at Microsoft.Dynamics.Nav.Types.Channels.ChunkingDuplexSessionChannel.OnOpen(TimeSpan timeout) in s:\repo\src\platform\ClientServerShared\Prod.Types\Channels\ChunkingDuplexSessionChannel.cs:line 97
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.ServiceModel.ICommunicationObject.Open()
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.CallOpenConnection(IAsyncNavService server, ConnectionRequest connectionRequest) in s:\repo\src\platform\client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 462
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectFailedEventArgs connectFailedArgs, ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, SpnSetting spnSettingToTry, Boolean allowSpnSettingsSwap, UserSettings& userSettings) in s:\repo\src\platform\client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 275
Source: mscorlib----------------------------------
Type: System.ServiceModel.FaultException
Message: The tenant 'urlaubsmodul' is not mounted or does not exist.
StackTrace:

Source: 
```

```
Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery
An exception was thrown while deserializing the token.

Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {21783be7-0cf7-4d78-812c-79bc1f4431f8} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

**Additional context**
- It only happens on one new dev machine, not on other machines which are set up in the same way and execute the same scripts.

**Comment by freddydk** [comment]
and you have ?tenant=default in the url?

**Comment by mmenninghaus** [comment]
oh my.
