### ISSUE TITLE
Multiple Container with shared external database cannot restart

### ISSUE THREAD

**Issue by sirhc101** [microsoft/navcontainerhelper#1791]
**Describe the issue**
We run an environment with an external SQL Server and two containers (one running AAD, one running UserPassword). We need the second container (UserPassword Auth.) for publishing from VSCode.

Anyway, I followed your description in #1729 and #1461 how to setup the containers with the same encryption key, but it seems not working correctly. Initially the containers where created successfully and both containers are up and running. As soon we restart the container created first it crashes with this error message:
```
container1
Waiting for container container1 to be ready

Initializing...
Setting host.containerhelper.internal to 172.29.64.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is bc
PublicDnsName is bc.xyz.tld
Using NavUserPassword Authentication
Starting Internet Information Server
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 155
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1Error
```

Event Log is showing this:
```
Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
User: 
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavApplicationMountFailedException
ErrorCode: -1
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: False
DiagnosticsSuppress: True
MessageWithoutPrivateInformation: The NAV application could not be mounted for database 'BC17' on database server 'HOST.CONTAINERHELPER.INTERNAL' due to the following error: The Microsoft Dynamics 365 Business Central Server instance cannot connect to the application database because it is using a different password encryption key than the one currently used on the database.
SuppressExceptionCreatedEvent: False
FatalityScope: None
ErrorLevel: Error
Message: The NAV application could not be mounted for database 'BC17' on database server 'HOST.CONTAINERHELPER.INTERNAL' due to the following error: The Microsoft Dynamics 365 Business Central Server instance cannot connect to the application database because it is using a different password encryption key than the one currently used on the database.
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.CheckEncryptionKey(String newEncryptionKey, Boolean verifyServerInstanceKey, Boolean verifyPublicEncryptionKeyFromDatabase)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey, Boolean isNewDatabase)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSingleLegacyTenant(String databaseServerName, String databaseName, String databaseUserName, ProtectedDatabasePassword databasePassword, EncryptionProvider encryptionProvider, AzureKeyVaultSettings azureKeyVaultSettings)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.ConfigureTenants(ServerUserSettings settings, String encryptionKey)
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
     at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
     at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.CheckEncryptionKey(String newEncryptionKey, Boolean verifyServerInstanceKey, Boolean verifyPublicEncryptionKeyFromDatabase)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey, Boolean isNewDatabase)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSingleLegacyTenant(String databaseServerName, String databaseName, String databaseUserName, ProtectedDatabasePassword databasePassword, EncryptionProvider encryptionProvider, AzureKeyVaultSettings azureKeyVaultSettings)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.ConfigureTenants(ServerUserSettings settings, String encryptionKey)
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
     at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
     at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)
```

The container we created second can be restarted w/o problems.

I'm pretty sure I did something wrong while creating the containers, but I've no idea anymore. I already tried to overwrite the key file in `C:\ProgramData\Microsoft\Microsoft Dynamics NAV\170\Server\Keys` manually but it does not work.

**Scripts used to create container and cause the issue**
```
# Encryption Key file
$keyFile = "C:\ProgramData\BcContainerHelper\EncryptionKey.key"
$keyFilePassword = "<MyPassword>"

$databaseCredential = New-Object System.Management.Automation.PSCredential -argumentList "bc-service", (ConvertTo-SecureString -String "<MyPassword>" -AsPlainText -Force)

# First Container

New-BCContainer -accept_eula `
    -containerName container1 `
    -multitenant:$multitenant `
    -updateHosts `
    -artifactUrl (Get-BCArtifactUrl -country "de" -type OnPrem -version "17.4") `
    -memoryLimit 4G `
    -licenseFile $license `
    -EnableTaskScheduler:$false `
    -auth NavUserPassword `
    -Credential $credential `
    -databaseServer 'host.containerhelper.internal' `
    -databaseInstance '' `
    -databaseName "BC17" `
    -databaseCredential $databaseCredential `
    -accept_outdated `
    -useTraefik `
    -PublicDnsName bc.xyz.tld `
    -shortcuts DesktopFolder `
    -alwaysPull `
    -useSSL `
    -myScripts @($keyFile) `
    -additionalParameters @(
        "--env encryptionPassword=$keyFilePassword"
        )

# Second Container

New-BCContainer -accept_eula `
    -containerName container2 `
    -multitenant:$multitenant `
    -updateHosts `
    -artifactUrl (Get-BCArtifactUrl -country "de" -type OnPrem -version "17.4") `
    -memoryLimit 16G `
    -licenseFile $license `
    -EnableTaskScheduler:$true `
    -auth AAD `
    -authenticationEMail "user@xyz.tld" `
    -databaseServer 'host.containerhelper.internal' `
    -databaseInstance '' `
    -databaseName "BC17" `
    -databaseCredential $databaseCredential `
    -accept_outdated `
    -useTraefik `
    -PublicDnsName bc.xyz.tld `
    -shortcuts DesktopFolder `
    -alwaysPull `
    -useSSL `
    -myScripts @($keyFile) `
    -additionalParameters @(
        "--env encryptionPassword=$keyFilePassword",
        "--env appIdUri=api://[..]",
        "--env federationLoginEndpoint=https://login.microsoftonline.com/[..]",
        "--env federationMetadata=https://login.microsoftonline.com/[..]",
        "--env authenticationEMail=user@xyz.tld"
        )
```

**Full output of scripts**

First Container
```
BcContainerHelper is version 2.0.4
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Removing container container1
Removing bc from host hosts file
Removing bc-* from host hosts file
Removing c:\programdata\bccontainerhelper\Extensions\container1
Fetching all docker images
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Pulling image mcr.microsoft.com/businesscentral:10.0.17763.1158
10.0.17763.1158: Pulling from businesscentral
Using image mcr.microsoft.com/businesscentral:10.0.17763.1158
PublicDnsName is bc.xyz.tld
Creating Container container1
Version: 17.4.21491.21531-de
Style: onprem
Multitenant: No
Platform: 17.0.21485.21516
Generic Tag: 1.0.1.4
Container OS Version: 10.0.17763.1158 (ltsc2019)
Host OS Version: 10.0.17763.1098 (ltsc2019)
WARNING: Host OS and Base Image Container OS doesn't match and Hyper-V is not installed. If you encounter issues, you could try to install Hyper-V.
Using process isolation
Using locale de-DE
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Install\BC.flf
Additional Parameters:
--env encryptionPassword=<MyPassword>
--hostname bc
-e webserverinstance=container1
-e publicdnsname=bc.xyz.tld
-l "traefik.protocol=https"
-l "traefik.web.frontend.rule=PathPrefix:/container1"
-l "traefik.web.port=443"
-l "traefik.soap.frontend.rule=PathPrefix:/container1soap;ReplacePathRegex: ^/container1soap(.*) /BC$1"
-l "traefik.soap.port=7047"
-l "traefik.rest.frontend.rule=PathPrefix:/container1rest;ReplacePathRegex: ^/container1rest(.*) /BC$1"
-l "traefik.rest.port=7048"
-l "traefik.dev.frontend.rule=PathPrefix:/container1dev;ReplacePathRegex: ^/container1dev(.*) /BC$1"
-l "traefik.dev.port=7049"
-l "traefik.dl.frontend.rule=PathPrefixStrip:/container1dl"
-l "traefik.dl.port=8080"
-l "traefik.dl.protocol=http"
-l "traefik.enable=true"
-l "traefik.frontend.entryPoints=https"
--env customNavSettings=EnableTaskScheduler=False,PublicODataBaseUrl=https://bc.xyz.tld/container1rest/odata,PublicSOAPBaseUrl=https://bc.xyz.tld/container1soap/ws,
PublicWebBaseUrl=https://bc.xyz.tld/container1
Files in c:\programdata\bccontainerhelper\Extensions\container1\my:
- AdditionalOutput.ps1
- CheckHealth.ps1
- EncryptionKey.key
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container container1 from image mcr.microsoft.com/businesscentral:10.0.17763.1158
ff385ebd9dc829cdb815a0550552eed29330ffba9c18ac85ddab9a1c32d74985
Waiting for container container1 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/17.4.21491.21531/de
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Installation took 18 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.29.64.1 in container hosts file
Starting Container
Hostname is bc
PublicDnsName is bc.xyz.tld
Using NavUserPassword Authentication
Import Encryption Key
Stopping local SQL Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6D34D061F0B7067557ACF3B18FBA5BD172C055DC
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to False
Setting PublicODataBaseUrl to https://bc.xyz.tld/container1rest/odata
Setting PublicSOAPBaseUrl to https://bc.xyz.tld/container1soap/ws
Setting PublicWebBaseUrl to https://bc.xyz.tld/container1
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Container IP Address: 172.29.69.66
Container Hostname  : bc
Container Dns Name  : bc.xyz.tld
Web Client          : https://bc.xyz.tld/container1/
Dev. Server         : https://bc.xyz.tld
Dev. ServerInstance : BC
Setting bc to 172.29.69.66 in host hosts file

Files:
http://bc.xyz.tld:8080/ALLanguage.vsix
http://bc.xyz.tld:8080/certificate.cer

WARNING: You are running a container which is 114 days old.
Microsoft recommends that you always run the latest version of our containers.

Container Total Physical Memory is 31.7Gb
Container Free Physical Memory is 6.7Gb

Initialization took 207 seconds
Ready for connections!
Reading CustomSettings.config from container1
Creating Desktop Shortcuts for container1
Container container1 successfully created
Because of Traefik, the following URLs need to be used when accessing the container from outside your Docker host:
Web Client:        https://bc.xyz.tld/container1
SOAP WebServices:  https://bc.xyz.tld/container1soap
OData WebServices: https://bc.xyz.tld/container1rest
Dev Service:       https://bc.xyz.tld/container1dev
File downloads:    https://bc.xyz.tld/container1dl

Use:
Get-BcContainerEventLog -containerName container1 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName container1 to get debug information about the container
Enter-BcContainer -containerName container1 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName container1 to remove the container again
docker logs container1 to retrieve information about URL's again
```

Second Container 
```
BcContainerHelper is version 2.0.4
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Removing container container2
Removing bc from host hosts file
Removing bc-* from host hosts file
Removing c:\programdata\bccontainerhelper\Extensions\container2
Fetching all docker images
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Pulling image mcr.microsoft.com/businesscentral:10.0.17763.1158
10.0.17763.1158: Pulling from businesscentral
Using image mcr.microsoft.com/businesscentral:10.0.17763.1158
PublicDnsName is bc.xyz.tld
Creating Container container2
Version: 17.4.21491.21531-de
Style: onprem
Multitenant: No
Platform: 17.0.21485.21516
Generic Tag: 1.0.1.4
Container OS Version: 10.0.17763.1158 (ltsc2019)
Host OS Version: 10.0.17763.1098 (ltsc2019)
WARNING: Host OS and Base Image Container OS doesn't match and Hyper-V is not installed. If you encounter issues, you could try to install Hyper-V.
Using process isolation
Using locale de-DE
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Install\BC.flf
Additional Parameters:
--env encryptionPassword=<MyPassword>
--env appIdUri=api://[..]
--env federationLoginEndpoint=https://login.microsoftonline.com/[..]
--env federationMetadata=https://login.microsoftonline.com/[..]
--env authenticationEMail=user@xyz.tld
--hostname bc
-e webserverinstance=container2
-e publicdnsname=bc.xyz.tld
-l "traefik.protocol=https"
-l "traefik.web.frontend.rule=PathPrefix:/container2"
-l "traefik.web.port=443"
-l "traefik.soap.frontend.rule=PathPrefix:/container2soap;ReplacePathRegex: ^/container2soap(.*) /BC$1"
-l "traefik.soap.port=7047"
-l "traefik.rest.frontend.rule=PathPrefix:/container2rest;ReplacePathRegex: ^/container2rest(.*) /BC$1"
-l "traefik.rest.port=7048"
-l "traefik.dev.frontend.rule=PathPrefix:/container2dev;ReplacePathRegex: ^/container2dev(.*) /BC$1"
-l "traefik.dev.port=7049"
-l "traefik.dl.frontend.rule=PathPrefixStrip:/container2dl"
-l "traefik.dl.port=8080"
-l "traefik.dl.protocol=http"
-l "traefik.enable=true"
-l "traefik.frontend.entryPoints=https"
--env customNavSettings=EnableTaskScheduler=True,PublicODataBaseUrl=https://bc.xyz.tld/container2rest/odata,PublicSOAPBaseUrl=https://bc.xyz.tld/container2soap/ws,Pub
licWebBaseUrl=https://bc.xyz.tld/container2
Files in c:\programdata\bccontainerhelper\Extensions\container2\my:
- AdditionalOutput.ps1
- CheckHealth.ps1
- EncryptionKey.key
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container container2 from image mcr.microsoft.com/businesscentral:10.0.17763.1158
342f9c29701b5aa08f855fdea4fa10011c03a6b8b31f1e04ba2468362ec02f5a
Waiting for container container2 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/17.4.21491.21531/de
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Installation took 17 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.29.64.1 in container hosts file
Starting Container
Hostname is bc
PublicDnsName is bc.xyz.tld
Using AccessControlService Authentication
Import Encryption Key
Stopping local SQL Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 4E66E810316B1F5FBC3B41BFEE7EB1B1FB78AFC1
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to True
Setting PublicODataBaseUrl to https://bc.xyz.tld/container2rest/odata
Setting PublicSOAPBaseUrl to https://bc.xyz.tld/container2soap/ws
Setting PublicWebBaseUrl to https://bc.xyz.tld/container2
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Container IP Address: 172.29.65.179
Container Hostname  : bc
Container Dns Name  : bc.xyz.tld
Web Client          : https://bc.xyz.tld/container2/
Dev. Server         : https://bc.xyz.tld
Dev. ServerInstance : BC
Setting bc to 172.29.65.179 in host hosts file

Files:
http://bc.xyz.tld:8080/ALLanguage.vsix
http://bc.xyz.tld:8080/certificate.cer

WARNING: You are running a container which is 114 days old.
Microsoft recommends that you always run the latest version of our containers.

Container Total Physical Memory is 31.7Gb
Container Free Physical Memory is 3.9Gb

Initialization took 193 seconds
Ready for connections!
Reading CustomSettings.config from container2
Creating Desktop Shortcuts for container2
Container container2 successfully created
Because of Traefik, the following URLs need to be used when accessing the container from outside your Docker host:
Web Client:        https://bc.xyz.tld/container2
SOAP WebServices:  https://bc.xyz.tld/container2soap
OData WebServices: https://bc.xyz.tld/container2rest
Dev Service:       https://bc.xyz.tld/container2dev
File downloads:    https://bc.xyz.tld/container2dl

Use:
Get-BcContainerEventLog -containerName container2 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName container2 to get debug information about the container
Enter-BcContainer -containerName container2 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName container2 to remove the container again
docker logs container2 to retrieve information about URL's again
```

Thank you very much in advance

**Comment by freddydk** [comment]
You should try to upgrade to latest containerhelper - and then remove the keyfile + encryptionpassword parameters. from 2.0.6 the containerhelper handles this by caching encryptionkeys for external databases.

**Comment by sirhc101** [comment]
I should always ask you first ;-)

Thank you very much @freddydk.
