### ISSUE TITLE
New-BcContainer scripts fails when SQL Server 2019 is used as host

### ISSUE THREAD

**Issue by slehoux** [microsoft/navcontainerhelper#1794]
**Describe the issue**
Hello to all,

The following script fails after trying to instanciate a BC container connecting to an extgernal SQL Server Database. It times out after a long waiting time. Once the script errors out, you can see that 

- The container has been created and is running
- The database files have been added to the SQL Server DATA folder
- No reference to the container can be found in the host file

I've gone through all suggestions in the follwing thread [https://github.com/microsoft/navcontainerhelper/issues/1754](url), but without success. Was told to post a new issue.

Thanks in advance for any help!

**Scripts used to create container and cause the issue**
```
$databaseServer = "<my-machine>"
$databaseInstance = "<my-database-instance>"

$dbSuffix = "BC_17"
$containerName = "MyBCApp-01"
$databaseFolder = "E:\Program Files\Microsoft SQL Server\MSSQL15.$dbSuffix\MSSQL\DATA"
$LicenseFile = "C:\Users\<my-username>\OneDrive - AZUR Group Inc\Projects\Azur\Ventes\Dynamics\Docker\Licenses\LicenseFile.flf"
$artifactUrl = Get-BCArtifactUrl -type Sandbox -version 17.5 -country ca -select latest

$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String '<my-password>' -AsPlainText -Force)
$dbcredentials = New-Object PSCredential -ArgumentList 'sa', $credential.Password

$databaseParams = @{
    "databaseServer" = "$databaseServer"
    "databaseInstance" = "$databaseInstance"
    "databasePrefix" = "$($containerName)-"
    "databaseName" = '<database_name>'
    "databaseCredential" = $dbcredentials
    "multitenant" = $true
}

New-BcContainer `
    @databaseParams -ReplaceExternalDatabases `
    -accept_eula `
    -containerName $containerName `
    -licenseFile $LicenseFile `
    -artifactUrl $artifactUrl `
    -auth UserPassword `
    -Credential $credential `
    -enableTaskScheduler `
    -alwaysPull `
    -includeAL `
    -usessl:$false `
    -updateHosts `
    -assignPremiumPlan `
    -shortcuts Desktop
```

**Full output of scripts**
```
BcContainerHelper is version 2.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 20.10.5
Docker Server Version is 20.10.5
Removing MyBCApp-01 from host hosts file
Removing MyBCApp-01-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\MyBCApp-01
Starting Database Restore job from https://bcartifacts.azureedge.net/sandbox/17.5.22499.23364/ca
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.18363.1198
10.0.18363.1198: Pulling from businesscentral
Digest: sha256:<redacted>
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.18363.1198
mcr.microsoft.com/businesscentral:10.0.18363.1198
Using image mcr.microsoft.com/businesscentral:10.0.18363.1198
Creating Container MyBCApp-01
Version: 17.5.22499.23364-CA
Style: sandbox
Multitenant: Yes
Platform: 17.0.22463.23355
Generic Tag: 1.0.1.4
Container OS Version: 10.0.18363.1198 (1909)
Host OS Version: 10.0.18363.1198 (1909)
Using process isolation
Using locale en-CA
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\<my-username>\OneDrive - AZUR Group Inc\Projects\Azur\Ventes\Dynamics\Docker\Licenses\D365BCv17.flf
Additional Parameters:
--env customNavSettings=EnableTaskScheduler=True
Files in C:\ProgramData\BcContainerHelper\Extensions\MyBCApp-01\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupDatabase.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container MyBCApp-01 from image mcr.microsoft.com/businesscentral:10.0.18363.1198
<redacted>
Waiting for container MyBCApp-01 to be ready

Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.CA
Installation took 24 seconds
Installation complete
Initializing...
Setting host.docker.internal to 10.15.0.11 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.15.0.11 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Starting Container
Hostname is MyBCApp-01
PublicDnsName is MyBCApp-01
Using NavUserPassword Authentication
PS C:\WINDOWS\system32> C:\Users\<my-username>\AZUR Group Inc\AZUR - Dynamics - Dev - Dev\Scripts\Mounting\New\Tests2.ps1
BcContainerHelper is version 2.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 20.10.5
Docker Server Version is 20.10.5
Removing container MyBCApp-01
Removing MyBCApp-01 from host hosts file
Removing MyBCApp-01-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\MyBCApp-01
Starting Database Restore job from https://bcartifacts.azureedge.net/sandbox/17.5.22499.23364/ca
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.18363.1198
10.0.18363.1198: Pulling from businesscentral
Digest: sha256:<redacted>
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.18363.1198
mcr.microsoft.com/businesscentral:10.0.18363.1198
Using image mcr.microsoft.com/businesscentral:10.0.18363.1198
Creating Container MyBCApp-01
Version: 17.5.22499.23364-CA
Style: sandbox
Multitenant: Yes
Platform: 17.0.22463.23355
Generic Tag: 1.0.1.4
Container OS Version: 10.0.18363.1198 (1909)
Host OS Version: 10.0.18363.1198 (1909)
Using process isolation
Using locale en-CA
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\<my-username>\OneDrive - AZUR Group Inc\Projects\Azur\Ventes\Dynamics\Docker\Licenses\D365BCv17.flf
Additional Parameters:
--env customNavSettings=EnableTaskScheduler=True
Files in C:\ProgramData\BcContainerHelper\Extensions\MyBCApp-01\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupDatabase.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container MyBCApp-01 from image mcr.microsoft.com/businesscentral:10.0.18363.1198
<redacted>
Waiting for container MyBCApp-01 to be ready

Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.CA
Installation took 23 seconds
Installation complete
Initializing...
Setting host.docker.internal to 10.15.0.11 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.15.0.11 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.22.112.1 in container hosts file
Starting Container
Hostname is MyBCApp-01
PublicDnsName is MyBCApp-01
Using NavUserPassword AuthenticationError

Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.CA
Installation took 23 seconds
Installation complete
Initializing...
Setting host.docker.internal to 10.15.0.11 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.15.0.11 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.22.112.1 in container hosts file
Starting Container
Hostname is MyBCApp-01
PublicDnsName is MyBCApp-01
Using NavUserPassword Authentication
Initialization of container MyBCApp-01 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...adApp-01 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container MyBCApp-01 failed
...
```

**Comment by freddydk** [comment]
Could you try to remove the -assignPremiumPlan?

**Comment by slehoux** [comment]
Same error as before unfortunately.

**Comment by freddydk** [comment]
Exactly the same error?
Every time you change something, something might change in the output.
Removing -assignPremiumPlan should remove 
- SetupNavUsers.ps1
from the list of files in the my folder.

I would need the full output every time.

On my machine, when I run this:
```
$dbSuffix = "BC_17"
$containerName = "MyBCApp-01"
$LicenseFile = "C:\temp\license.flf"
$artifactUrl = Get-BCArtifactUrl -type Sandbox -version 17.5 -country ca -select latest

$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$dbcredentials = New-Object PSCredential -ArgumentList 'sa', $dbPassword

$databaseParams = @{
    "databaseServer" = "host.containerhelper.internal"
    "databaseInstance" = ""
    "databasePrefix" = "$($containerName)-"
    "databaseName" = 'CRONUS'
    "databaseCredential" = $dbcredentials
    "multitenant" = $true
}

New-BcContainer `
    @databaseParams -ReplaceExternalDatabases `
    -accept_eula `
    -containerName $containerName `
    -licenseFile $LicenseFile `
    -artifactUrl $artifactUrl `
    -auth UserPassword `
    -Credential $credential `
    -enableTaskScheduler `
    -alwaysPull `
    -includeAL `
    -usessl:$false `
    -updateHosts `
    -shortcuts Desktop
```
I get this
```
BcContainerHelper is version 2.0.8-dev
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 20H2
Docker Client Version is 20.10.5
Docker Server Version is 20.10.5
Removing container MyBCApp-01
Removing MyBCApp-01 from host hosts file
Removing MyBCApp-01-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\MyBCApp-01
Setting database MyBCApp-01-tenant offline
Removing database MyBCApp-01-tenant
Setting database MyBCApp-01-CRONUS offline
Removing database MyBCApp-01-CRONUS
Starting Database Restore job from https://bcartifacts.azureedge.net/sandbox/17.5.22499.23473/ca
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.19042.867
10.0.19042.867: Pulling from businesscentral
Digest: sha256:2471a68787c625b4b5243fc5ed3cf3ebc26f42b524ccc1aba18cf994e5906be7
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.19042.867
mcr.microsoft.com/businesscentral:10.0.19042.867
Using image mcr.microsoft.com/businesscentral:10.0.19042.867
Creating Container MyBCApp-01
Version: 17.5.22499.23473-CA
Style: sandbox
Multitenant: Yes
Platform: 17.0.22463.23443
Generic Tag: 1.0.1.4
Container OS Version: 10.0.19042.867 (20H2)
Host OS Version: 10.0.19042.867 (20H2)
Using process isolation
Using locale en-CA
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\temp\license.flf
Additional Parameters:
--env customNavSettings=EnableTaskScheduler=True
Files in C:\ProgramData\BcContainerHelper\Extensions\MyBCApp-01\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupDatabase.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container MyBCApp-01 from image mcr.microsoft.com/businesscentral:10.0.19042.867
Using Shared Encryption Key file
8b5e65aee95750a4ebee934faf1c02076c1a82b7eed5eb7966e879df3e4d4fbb
Waiting for container MyBCApp-01 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/17.5.22499.23473/ca
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.CA
Installation took 31 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.0.22 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.22 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.21.160.1 in container hosts file
Starting Container
Hostname is MyBCApp-01
PublicDnsName is MyBCApp-01
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Waiting for database creation to finish..........................................................
Import Encryption Key
Stopping local SQL Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 27943B50ABB16314C9EC898F99000B7DA0271B1A
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to True
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Enabling rewrite rule: Don't rewrite system files
Enabling rewrite rule: Already have tenant specified
Enabling rewrite rule: Hostname (without port) to tenant
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Container IP Address: 172.21.172.30
Container Hostname  : MyBCApp-01
Container Dns Name  : MyBCApp-01
Web Client          : http://MyBCApp-01/BC/?tenant=default
Dev. Server         : http://MyBCApp-01
Dev. ServerInstance : BC
Dev. Server Tenant  : default
Setting MyBCApp-01 to 172.21.172.30 in host hosts file

Files:
http://MyBCApp-01:8080/ALLanguage.vsix

Container Total Physical Memory is 63.8Gb
Container Free Physical Memory is 41.9Gb

Initialization took 114 seconds
Ready for connections!
Reading CustomSettings.config from MyBCApp-01
Creating Desktop Shortcuts for MyBCApp-01
Extracting C:\Applications.CA\Base Application.Source.zip
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Windows\Microsoft.NET\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\170\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\170\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Creating Tenant default on MyBCApp-01
Copying Database on host.containerhelper.internal from MyBCApp-01-tenant to MyBCApp-01-default
EngineEdition 3
backup database [MyBCApp-01-tenant] to disk = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MyBCApp01\MyBCApp-01-tenant.bak' with init, stats=10;
restore database [MyBCApp-01-default] from disk = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MyBCApp01\MyBCApp-01-tenant.bak' with stats=10, recovery, move 'Navision_NAV_CA_Data' to 'C:\Program Fil
es\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MyBCApp01\MyBCApp-01-default.mdf', move 'Navision_NAV_CA_Log' to 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MyBCApp01\MyBCApp-01-default.ldf'
Mounting Database for default on server host.containerhelper.internal with AllowAppDatabaseWrite = False
Sync'ing Tenant
Setting MyBCApp-01-default to 172.21.172.30 in host hosts file
Tenant successfully created
Creating User admin
Assigning Permission Set SUPER to admin
Container MyBCApp-01 successfully created

Use:
Get-BcContainerEventLog -containerName MyBCApp-01 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName MyBCApp-01 to get debug information about the container
Enter-BcContainer -containerName MyBCApp-01 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName MyBCApp-01 to remove the container again
docker logs MyBCApp-01 to retrieve information about URL's again
```

**Comment by slehoux** [comment]
Ok, here goes.

```
$databaseServer = "localhost"
$databaseInstance = "<my-db-instance>"

$dbSuffix = "BC_17"
$containerName = "<container-name>"
$databaseFolder = "E:\Program Files\Microsoft SQL Server\MSSQL15.$dbSuffix\MSSQL\DATA"
$LicenseFile = "C:\Users\<username>\OneDrive - AZUR Group Inc\Projects\Azur\Ventes\Dynamics\Docker\Licenses\D365BCv17.flf"
$artifactUrl = Get-BCArtifactUrl -type Sandbox -version 17.5 -country ca -select latest

$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String '<password>' -AsPlainText -Force)
$dbcredentials = New-Object PSCredential -ArgumentList 'sa', $credential.Password

$databaseParams = @{
    "databaseServer" = "$databaseServer"
    "databaseInstance" = "$databaseInstance"
    "databasePrefix" = "$($containerName)-"
    "databaseName" = '<copmpany-name>'
    "databaseCredential" = $dbcredentials
    "multitenant" = $true
}

New-BcContainer `
    @databaseParams -ReplaceExternalDatabases `
    -accept_eula `
    -containerName $containerName `
    -licenseFile $LicenseFile `
    -artifactUrl $artifactUrl `
    -auth UserPassword `
    -Credential $credential `
    -enableTaskScheduler `
    -alwaysPull `
    -includeAL `
    -usessl:$false `
    -updateHosts `
    #-assignPremiumPlan `
    -shortcuts Desktop
```

And here's the result...

```
BcContainerHelper version 2.0.7
BcContainerHelper is version 2.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 20.10.5
Docker Server Version is 20.10.5
Removing <container-name> from host hosts file
Removing <container-name>-01-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\<container-name>-01
Downloading application artifact /sandbox/17.5.22499.23473/ca
Downloading C:\Users\<username>\AppData\Local\Temp\fc982ed1-96aa-420a-8128-5398c662eec5.zip
Could not download from https://bcartifacts.azureedge.net/..., retrying from https://bcartifacts.blob.core.windows.net/...
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/17.5.22499.23473/platform
Downloading C:\Users\<username>\AppData\Local\Temp\3cfbe68b-34e0-4435-897f-3bac3c05afd8.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\17.5.22499.23473\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\17.5.22499.23473\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\sandbox\17.5.22499.23473\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Starting Database Restore job from https://bcartifacts.azureedge.net/sandbox/17.5.22499.23473/ca
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.18363.1198
10.0.18363.1198: Pulling from businesscentral
Digest: sha256:<redacted>
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.18363.1198
mcr.microsoft.com/businesscentral:10.0.18363.1198
Using image mcr.microsoft.com/businesscentral:10.0.18363.1198
Creating Container <container-name>-01
Version: 17.5.22499.23473-CA
Style: sandbox
Multitenant: Yes
Platform: 17.0.22463.23443
Generic Tag: 1.0.1.4
Container OS Version: 10.0.18363.1198 (1909)
Host OS Version: 10.0.18363.1198 (1909)
Using process isolation
Using locale en-CA
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\<username>\[...]\Projects\Azur\Ventes\Dynamics\Docker\Licenses\D365BCv17.flf
Additional Parameters:
--env customNavSettings=EnableTaskScheduler=True
Files in C:\ProgramData\BcContainerHelper\Extensions\<container-name>-01\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupDatabase.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container <container-name>-01 from image mcr.microsoft.com/businesscentral:10.0.18363.1198
<redacted>
Waiting for container <container-name>-01 to be ready
Error

Initialization of container <container-name>-01 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...adApp-01 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container <container-name>-01 failed
```

**Comment by freddydk** [comment]
This doesn't look like the same error.
In the first output, the failure cam right after the "Using NavUserPassword Authentication"

```
Hostname is MyBCApp-01
PublicDnsName is MyBCApp-01
Using NavUserPassword Authentication
Initialization of container MyBCApp-01 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
```

This was fixed by removing the AssignPremiumPlan (btw. you cannot just comment out a part of a multiline command in PowerShell - you do not get the remaining parameters then. In this case that is not the problem though)

In this latest output, it never gets to start the container.
I have never before seen an error just described as

```
Error
```

and then nothing else.
My assumption is that this is machine specific and you might need to reset docker to factory defaults.

**Comment by slehoux** [comment]
Ok, I'll try reinstalling Docker and trying again. Will let you know what the result is.

Thanks again.

**Comment by gromney** [comment]
Saludos,

I'm traying to connect my bcContainer to my local instance of SQLserver using the following script. Using host ip-address as databaseServer because I can not reach the host with the name.


```
$navPass = ConvertTo-SecureString -String "Ad12345678" -AsPlainText -Force
$navCredential = New-Object System.Management.Automation.PSCredential -argumentList "admin", $navPass

$sqlPass = (ConvertTo-SecureString -String "Navuser1234" -AsPlainText -Force)
$sqlCredential = New-Object System.Management.Automation.PSCredential -argumentList "navuser", $sqlPass

$artifactUrl = Get-BcArtifactUrl -type onprem -country na -version 11.0.23019

$containerName = "HOMS"

New-BCContainer -accept_eula `
                -containerName $containerName `
                -artifactUrl $artifactUrl `
                -auth UserPassword `
                -Credential $navCredential `
                -includecside `
                -shortcuts Desktop `
                -updateHosts `
                -licenseFile 'd:\projects\Dynasoft_2020-2021.flf' `
                -databaseServer 192.168.0.105 `
                -databaseInstance MSSQLSERVER `
                -databaseName NAVDB `
                -databaseCredential $sqlCredential 
```

With this result

```
PS C:\WINDOWS\system32> D:\externalSQL.ps1
BcContainerHelper is version 2.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 20.10.5
Docker Server Version is 20.10.5
Removing HOMS from host hosts file
Removing HOMS-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\HOMS
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.19042.867
Creating Container HOMS
Version: 11.0.23019.0-na
Style: onprem
Multitenant: No
Platform: 11.0.23019.0
Generic Tag: 1.0.1.4
Container OS Version: 10.0.19042.867 (20H2)
Host OS Version: 10.0.19042.867 (20H2)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file d:\projects\Dynasoft_2020-2021.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\HOMS\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container HOMS from image mcr.microsoft.com/businesscentral:10.0.19042.867
6c6e0ce80ac5667117f731e544b83765db6fafb18b62267437fea81da531260c
Waiting for container HOMS to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/11.0.23019.0/na
Using installer from C:\Run\110
Copying Platform Artifacts
Copying Application Artifacts
Copying Installers
Copying ConfigurationPackages
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Installing NAV
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Skipping restore of Cronus database
Installing C:\NAVDVD\Installers\CA.en\RTC\RoleTailoredClient.Local.CA.en.msi
Skipping C:\NAVDVD\Installers\CA.en\WebHelp\WebHelp.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.fr\RTC\RoleTailoredClient.Local.CA.fr.msi
Skipping C:\NAVDVD\Installers\CA.fr\WebHelp\WebHelp.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\MX.es\RTC\RoleTailoredClient.Local.MX.es.msi
Skipping C:\NAVDVD\Installers\MX.es\WebHelp\WebHelp.Local.MX.es.msi
Installing C:\NAVDVD\Installers\US.en\RTC\RoleTailoredClient.Local.US.en.msi
Skipping C:\NAVDVD\Installers\US.en\WebHelp\WebHelp.Local.US.en.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 34 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.0.105 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.105 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.0.1 in container hosts file
Starting Container
Hostname is HOMS
PublicDnsName is HOMS
Using NavUserPassword Authentication
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 152
at <ScriptBlock>, C:\Run\navstart.ps1: line 121
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/11.0.23019.0/na
Using installer from C:\Run\110
Copying Platform Artifacts
Copying Application Artifacts
Copying Installers
Copying ConfigurationPackages
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Installing NAV
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Skipping restore of Cronus database
Installing C:\NAVDVD\Installers\CA.en\RTC\RoleTailoredClient.Local.CA.en.msi
Skipping C:\NAVDVD\Installers\CA.en\WebHelp\WebHelp.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.fr\RTC\RoleTailoredClient.Local.CA.fr.msi
Skipping C:\NAVDVD\Installers\CA.fr\WebHelp\WebHelp.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\MX.es\RTC\RoleTailoredClient.Local.MX.es.msi
Skipping C:\NAVDVD\Installers\MX.es\WebHelp\WebHelp.Local.MX.es.msi
Installing C:\NAVDVD\Installers\US.en\RTC\RoleTailoredClient.Local.US.en.msi
Skipping C:\NAVDVD\Installers\US.en\WebHelp\WebHelp.Local.US.en.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 34 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.0.105 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.105 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.0.1 in container hosts file
Starting Container
Hostname is HOMS
PublicDnsName is HOMS
Using NavUserPassword Authentication
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 152
at <ScriptBlock>, C:\Run\navstart.ps1: line 121
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
Initialization of container HOMS failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container HOMS failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container HOMS failed
```
The error form Get-NavContainerEventLog HOMS

```
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavCSideException
Remappable: True
ErrorCode: 22924076
ErrorNumber: 52012
ModuleNumber: 93
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: False
DiagnosticsSuppress: False
NavTenantId: nav-systemapplication
MessageWithoutPrivateInformation:
  Cannot establish a connection to the SQL Server/Database.
  
  This could be due to one of the following reasons:
  
  * SQL Server is not started.
  * The database does not exist.
  * Proper permissions have not been given to the NAV Server Account.
  
  Try again later or contact your system administrator.
SuppressExceptionCreatedEvent: False
FatalityScope: None
Message:
  <ii>Cannot establish a connection to the SQL Server/Database.
  
  This could be due to one of the following reasons:
  
  * SQL Server is not started.
  * The database does not exist.
  * Proper permissions have not been given to the NAV Server Account.
  
  Try again later or contact your system administrator.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnection(Int32 attemptCount)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.HandleEncryptionKeyChangeInApplicationDatabase(String newPublicKey)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088
```
