### ISSUE TITLE
Can't create docker connected with local instance (database restored from 1Click)

### ISSUE THREAD

**Issue by xgaronnat** [microsoft/navcontainerhelper#1964]
Hello Freddy,
Here my issue description, thanks for your help.

**Describe the issue**
Trying to create a docker to my local SQL Server instance/DB on my laptop, I get this error :
```
...
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

```

I can ping host.containerhelper.internal from the docker.
SQL Server is a fresh SQL 2019 Developer Edition install with sa account (Mixed mode) and TCP/IP enabled. The SQL backup came from 1Click hosting company.

**Scripts used to create container and cause the issue**
```
Clear-Host
Set-ExecutionPolicy Unrestricted -Force
#install-module BCcontainerhelper -Force -AllowClobber

#put all files (licences, bacpac, dll, ...) in this folder and adapt licence/bacpac names below
$dockerinput = "C:\temp\dockerinput"

# Licenses
$mydevlicense = "$dockerinput\German Developer BC V18.flf"


# Containers URL and settings
$accept_eula = $true
$artifactUrl = Get-BCArtifactUrl -type OnPrem -country "w1" -version "16.10" -select Latest
$containername = 'sqlv16'

# Set credentials #
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String '<pwd>' -AsPlainText -Force) #same password as for SA user in SQL Srv
$dbcredentials = New-Object PSCredential -ArgumentList 'sa', $credential.Password
$DatabaseName = 'ST-121122'

########################
# Create new container #
########################
New-BCContainer -accept_eula:$accept_eula `
                 -accept_outdated `
                 -containername $containername `
                 -artifactUrl $artifactUrl `
                 -licensefile $mydevlicense `
                 -Credential $credential `
                 -memoryLimit 8G `
                 -shortcuts Desktop `
                 -updateHosts `
                 -usessl:$false `
                 -auth NavUserPassword `
                 -doNotCheckHealth `
                 -databaseServer 'host.containerhelper.internal' `
                 -databaseInstance '' `
                 -databaseName $DatabaseName `
                 -databaseCredential $dbcredentials


```

**Full output of scripts**
```
BcContainerHelper is version 2.0.12
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Professionnel - 20H2
Docker Client Version is 20.10.6
Docker Server Version is 20.10.6
Removing sqlv16 from container hosts file
Removing sqlv16-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\sqlv16
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.19042.985
Disabling Health Check (always report healthy)
Creating Container sqlv16
Version: 16.10.21502.0-w1
Style: onprem
Multitenant: No
Platform: 16.0.21469.0
Generic Tag: 1.0.1.7
Container OS Version: 10.0.19042.985 (20H2)
Host OS Version: 10.0.19042.985 (20H2)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\temp\dockerinput\German Developer BC V18.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\sqlv16\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container sqlv16 from image mcr.microsoft.com/businesscentral:10.0.19042.985
1e5f37b92145837732f9d8a6b1b38f663866b5f0e44de5d558646658e3e2bca3
Waiting for container sqlv16 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.10.21502.0/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\16.10.21502.0\platform\ServiceTier\Program Files
c:\dl\onprem\16.10.21502.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\16.10.21502.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\16.10.21502.0\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\16.10.21502.0\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\16.10.21502.0\platform
c:\dl\onprem\16.10.21502.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\16.10.21502.0\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\16.10.21502.0\platform\Test Assemblies
Copying Applications
C:\dl\onprem\16.10.21502.0\platform\Applications
Installation took 38 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.1.8 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.8 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.24.32.1 in container hosts file
Starting Container
Hostname is sqlv16
PublicDnsName is sqlv16
Using NavUserPassword Authentication
Import Encryption Key
Impossible d'Ã©tablir une connexion avec la base de donnÃ©es ou SQL Server.

Raisons possiblesÂ :

* SQL Server n'est pas dÃ©marrÃ©.
* La base de donnÃ©es n'existe pas.
* Le compte NAV Server ne dispose pas des autorisations adÃ©quates.

RÃ©essayez plus tard ou contactez votre administrateur systÃ¨me.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 152
at <ScriptBlock>, C:\Run\navstart.ps1: line 122
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.10.21502.0/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\16.10.21502.0\platform\ServiceTier\Program Files
c:\dl\onprem\16.10.21502.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\16.10.21502.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\16.10.21502.0\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\16.10.21502.0\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\16.10.21502.0\platform
c:\dl\onprem\16.10.21502.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\16.10.21502.0\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\16.10.21502.0\platform\Test Assemblies
Copying Applications
C:\dl\onprem\16.10.21502.0\platform\Applications
Installation took 38 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.1.8 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.8 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.24.32.1 in container hosts file
Starting Container
Hostname is sqlv16
PublicDnsName is sqlv16
Using NavUserPassword Authentication
Import Encryption Key
Impossible d'Ã©tablir une connexion avec la base de donnÃ©es ou SQL Server.

Raisons possiblesÂ :

* SQL Server n'est pas dÃ©marrÃ©.
* La base de donnÃ©es n'existe pas.
* Le compte NAV Server ne dispose pas des autorisations adÃ©quates.

RÃ©essayez plus tard ou contactez votre administrateur systÃ¨me.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 152
at <ScriptBlock>, C:\Run\navstart.ps1: line 122
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
Initialization of container sqlv16 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.12\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r sqlv16 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container sqlv16 failed
 

PS C:\Windows\system32> 
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7318801/121559152-a1592f80-ca16-11eb-9bdf-d1f054f71346.png)

**Additional context**
- does it happen all the time? yes
- did it use to work? no

**Comment by freddydk** [comment]
You can try to set 
```
$bcContainerHelperConfig.useSharedEncryptionKeys = $false
```
before running New-BcContainer and let me know whether this fixes the issue.

**Comment by xgaronnat** [comment]
Nothing changed unfortunately.

```
Clear-Host
Set-ExecutionPolicy Unrestricted -Force
install-module BCcontainerhelper -Force -AllowClobber

#put all files (licences, bacpac, dll, ...) in this folder and adapt licence/bacpac names below
$dockerinput = "C:\temp\dockerinput"

# Licenses
$mydevlicense = "$dockerinput\German Developer BC V18.flf"


# Containers URL and settings
$accept_eula = $true
$artifactUrl = Get-BCArtifactUrl -type OnPrem -country "w1" -version "16.10" -select Latest
$containername = 'sqlv16'

# Set credentials #
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'Cosmo123!' -AsPlainText -Force) #same password as for SA user in SQL Srv
$dbcredentials = New-Object PSCredential -ArgumentList 'sa', $credential.Password
$DatabaseName = 'ST-121122'

$bcContainerHelperConfig.useSharedEncryptionKeys = $false

########################
# Create new container #
########################
New-BCContainer -accept_eula:$accept_eula `
                 -accept_outdated `
                 -containername $containername `
                 -artifactUrl $artifactUrl `
                 -licensefile $mydevlicense `
                 -Credential $credential `
                 -memoryLimit 8G `
                 -shortcuts Desktop `
                 -updateHosts `
                 -usessl:$false `
                 -auth NavUserPassword `
                 -doNotCheckHealth `
                 -databaseServer 'host.containerhelper.internal' `
                 -databaseInstance '' `
                 -databaseName $DatabaseName `
                 -databaseCredential $dbcredentials


```

Log:
```
BcContainerHelper is version 2.0.12
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Professionnel - 20H2
Docker Client Version is 20.10.6
Docker Server Version is 20.10.6
Removing container sqlv16
Removing sqlv16 from container hosts file
Removing sqlv16-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\sqlv16
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.19042.985
Disabling Health Check (always report healthy)
Creating Container sqlv16
Version: 16.10.21502.0-w1
Style: onprem
Multitenant: No
Platform: 16.0.21469.0
Generic Tag: 1.0.1.7
Container OS Version: 10.0.19042.985 (20H2)
Host OS Version: 10.0.19042.985 (20H2)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\temp\dockerinput\German Developer BC V18.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\sqlv16\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container sqlv16 from image mcr.microsoft.com/businesscentral:10.0.19042.985
68924c547d1b4b40ea1fdde7c56d58fb1762ac91e37a67a1bbb6c5ee16908d61
Waiting for container sqlv16 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.10.21502.0/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\16.10.21502.0\platform\ServiceTier\Program Files
c:\dl\onprem\16.10.21502.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\16.10.21502.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\16.10.21502.0\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\16.10.21502.0\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\16.10.21502.0\platform
c:\dl\onprem\16.10.21502.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\16.10.21502.0\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\16.10.21502.0\platform\Test Assemblies
Copying Applications
C:\dl\onprem\16.10.21502.0\platform\Applications
Installation took 70 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.1.8 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.8 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.24.32.1 in container hosts file
Starting Container
Hostname is sqlv16
PublicDnsName is sqlv16
Using NavUserPassword Authentication
Import Encryption Key
Impossible d'Ã©tablir une connexion avec la base de donnÃ©es ou SQL Server.

Raisons possiblesÂ :

* SQL Server n'est pas dÃ©marrÃ©.
* La base de donnÃ©es n'existe pas.
* Le compte NAV Server ne dispose pas des autorisations adÃ©quates.

RÃ©essayez plus tard ou contactez votre administrateur systÃ¨me.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 152
at <ScriptBlock>, C:\Run\navstart.ps1: line 122
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.10.21502.0/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\16.10.21502.0\platform\ServiceTier\Program Files
c:\dl\onprem\16.10.21502.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\16.10.21502.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\16.10.21502.0\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\16.10.21502.0\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\16.10.21502.0\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\16.10.21502.0\platform
c:\dl\onprem\16.10.21502.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\16.10.21502.0\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\16.10.21502.0\platform\Test Assemblies
Copying Applications
C:\dl\onprem\16.10.21502.0\platform\Applications
Installation took 70 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.1.8 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.8 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.24.32.1 in container hosts file
Starting Container
Hostname is sqlv16
PublicDnsName is sqlv16
Using NavUserPassword Authentication
Import Encryption Key
Impossible d'Ã©tablir une connexion avec la base de donnÃ©es ou SQL Server.

Raisons possiblesÂ :

* SQL Server n'est pas dÃ©marrÃ©.
* La base de donnÃ©es n'existe pas.
* Le compte NAV Server ne dispose pas des autorisations adÃ©quates.

RÃ©essayez plus tard ou contactez votre administrateur systÃ¨me.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 152
at <ScriptBlock>, C:\Run\navstart.ps1: line 122
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
Initialization of container sqlv16 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.12\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r sqlv16 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container sqlv16 failed
 
```

**Comment by freddydk** [comment]
Is there anything in the event log in the container?
Otherwise, you are welcome to email me a URL where I can download the DB and see if I can repro here.

**Comment by xgaronnat** [comment]
I can see this in the log :
 
```
2021-06-11T09:45:13 Warning [sqlv16.Application.Microsoft.Dynamics.Nav.Management.dll] Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavCSideException
Remappable: True
ErrorCode: 22924076
ErrorNumber: 52012
ModuleNumber: 93
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: False
DiagnosticsSuppress: True
NavTenantId: nav-systemapplication
EnvironmentType: Production
MessageWithoutPrivateInformation:
  Impossible d'établir une connexion avec la base de données ou SQL Server.
  
  Raisons possibles :
  
  * SQL Server n'est pas démarré.
  * La base de données n'existe pas.
  * Le compte NAV Server ne dispose pas des autorisations adéquates.
  
  Réessayez plus tard ou contactez votre administrateur système.
SuppressExceptionCreatedEvent: False
FatalityScope: None
ErrorLevel: Error
Message:
  Impossible d'établir une connexion avec la base de données ou SQL Server.
  
  Raisons possibles :
  
  * SQL Server n'est pas démarré.
  * La base de données n'existe pas.
  * Le compte NAV Server ne dispose pas des autorisations adéquates.
  
  Réessayez plus tard ou contactez votre administrateur système.
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnection(Int32 attemptCount)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey, Boolean isNewDatabase)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.HandleEncryptionKeyChangeInApplicationDatabase(String newPublicKey)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnection(Int32 attemptCount)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey, Boolean isNewDatabase)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.HandleEncryptionKeyChangeInApplicationDatabase(String newPublicKey)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()

```
I send you the log event and the .bak.

**Comment by dannoe** [comment]
Have you checked your firewall on the host to allow requests to the local sql server?

**Comment by xgaronnat** [comment]
> Have you checked your firewall on the host to allow requests to the local sql server?

Hello,
I can ping host.containerhelper.internal from the docker : is-it enough to check this ?

**Comment by xgaronnat** [comment]
I open up the 1433 port on firewall and it's ok now.
My mistake.

https://itproguru.com/expert/2011/06/how-to-open-firewall-port-1433-for-sql-server-database-engine-for-use-with-scom-or-anything-else-2/
