### ISSUE TITLE
OnPrem Container Creation A record in table User Property was locked for use in another session.

### ISSUE THREAD

**Issue by lktraser** [microsoft/navcontainerhelper#1975]
**Describe the issue**
Since this morning I have issues when creating BC18 OnPrem containers. Something is blocking the User Property Table. The problem only appears for OnPrem artfacts.

**Scripts used to create container and cause the issue**
```
$parameters = @{    
    includeTestToolkit            =  $true
    containerName                 =  "bugtest"
    enableTaskScheduler           =  $true
    credential                    =  (Get-Credential)    
    shortcuts                     =  "Desktop"
    includeTestLibrariesOnly      =  $true
    additionalParameters          = @("--env defaultTenantHasAllowAppDatabaseWrite=Y", "-e customNavSettings=ClientServicesMaxUploadSize=2000")
    assignPremiumPlan             =  $true
    updateHosts                   =  $true
    accept_eula                   =  $true
    artifactURL                   =  "https://bcartifacts.azureedge.net/onprem/18.1.24822.26330/de"
    alwaysPull                    =  $true
    accept_outdated               =  $true
    doNotExportObjectsToText      =  $true
    auth                          =  "NavUserPassword"
    useCleanDatabase              =  $false
    licenseFile                   =  "***"
}

New-BCContainer @parameters
```

**Full output of scripts**
```

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
BcContainerHelper is version 2.0.13
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 20.10.5
Docker Server Version is 20.10.5
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.17763.1935
10.0.17763.1935: Pulling from businesscentral
Digest: sha256:fac203f876f87ace14986b5afbe338dea7abb7c211fad94262e83c5628ac6e4f
Using image mcr.microsoft.com/businesscentral:10.0.17763.1935
Creating Container bugtest
Version: 18.1.24822.26330-de
Style: onprem
Multitenant: No
Platform: 18.0.24800.26311
Generic Tag: 1.0.1.7
Container OS Version: 10.0.17763.1935 (ltsc2019)
Host OS Version: 10.0.17763.1935 (ltsc2019)
Using process isolation
Using locale de-DE
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file ***
Additional Parameters:
--env defaultTenantHasAllowAppDatabaseWrite=Y
-e customNavSettings=ClientServicesMaxUploadSize=2000,EnableTaskScheduler=True
Files in C:\ProgramData\BcContainerHelper\Extensions\bugtest\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bugtest from image mcr.microsoft.com/businesscentral:10.0.17763.1935
7168af5e9a0ed68a85865d6794578a38f014050debead8765db03e6c685002dd
Waiting for container bugtest to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/18.1.24822.26330/de
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\18.1.24822.26330\platform\ServiceTier\Program Files
c:\dl\onprem\18.1.24822.26330\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\18.1.24822.26330\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\18.1.24822.26330\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\18.1.24822.26330\de\database\Demo Database NAV (18-0).bak
Changing Database Server Collation to Latin1_General_100_CI_AS
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\18.1.24822.26330\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\18.1.24822.26330\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\18.1.24822.26330\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\18.1.24822.26330\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\18.1.24822.26330\platform
c:\dl\onprem\18.1.24822.26330\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\18.1.24822.26330\de\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\18.1.24822.26330\platform\Test Assemblies
Copying Applications
C:\dl\onprem\18.1.24822.26330\de\Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 134 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.27.144.1 in container hosts file
Starting Container
Hostname is bugtest
PublicDnsName is bugtest
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 456D335369705EACD3553168F1C210E3845E97ED
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting ClientServicesMaxUploadSize to 2000
Setting EnableTaskScheduler to True
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating tester as SQL User and add to sysadmin
Creating SUPER user
We could not update the data right now.
Please try again later.

Technical details:
A record in table User Property was locked for use in another session. Administrators can see current locks on the Database Locks page or use telemetry. (Snapshot ID: a3aa9abb-a2e8-4eb2-b418-b6b2ece7ca75)
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 203
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/18.1.24822.26330/de
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\18.1.24822.26330\platform\ServiceTier\Program Files
c:\dl\onprem\18.1.24822.26330\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\18.1.24822.26330\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\18.1.24822.26330\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\18.1.24822.26330\de\database\Demo Database NAV (18-0).bak
Changing Database Server Collation to Latin1_General_100_CI_AS
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\18.1.24822.26330\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\18.1.24822.26330\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\18.1.24822.26330\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\18.1.24822.26330\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\18.1.24822.26330\platform
c:\dl\onprem\18.1.24822.26330\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\18.1.24822.26330\de\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\18.1.24822.26330\platform\Test Assemblies
Copying Applications
C:\dl\onprem\18.1.24822.26330\de\Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 134 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.27.144.1 in container hosts file
Starting Container
Hostname is bugtest
PublicDnsName is bugtest
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 456D335369705EACD3553168F1C210E3845E97ED
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting ClientServicesMaxUploadSize to 2000
Setting EnableTaskScheduler to True
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating tester as SQL User and add to sysadmin
Creating SUPER user
We could not update the data right now.
Please try again later.

Technical details:
A record in table User Property was locked for use in another session. Administrators can see current locks on the Database Locks page or use telemetry. (Snapshot ID: a3aa9abb-a2e8-4eb2-b418-b6b2ece7ca75)
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 203
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
Initialization of container bugtest failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.13\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ... bugtest failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bugtest failed
```

**Additional context**
- does it happen all the time? : only with OnPrem Artifacts. Sandbox seems to be fine.
- did it use to work? yes

**Comment by freddydk** [comment]
I tried to run the exact script (except for using my own license file of course) - and the script works just fine.
Could you try to get the event log from the container using Get-BcContainerEventLog and see whether that reveals anything about what is wrong here?

**Comment by lktraser** [comment]
Some new information: it seems to run fine with bccontainerhelper 2.0.10. I switched back to 2.0.13 and get the same behavior again. I should also mention that I also have a SQL Server on this machine but I'm not using it for this container.

Container Log 1
```
The description for Event ID 701 from source MicrosoftDynamicsNavServer$BC cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: BC
Category: Security
ClientSessionId: 2590ae3a-59b7-4d26-a535-56beafbe1175
ClientActivityId: 9410148c-fbae-4464-a5c7-a3ef6ab898a1
ServerSessionUniqueId: ab74ea8c-d247-4b0c-bbdd-1f7643ea35ae
ServerActivityId: abbb3a32-f933-469e-8cb1-0da9ebb20035
EventTime: 06/21/2021 09:50:22
Message (FaultException`1): This message had personal data removed. The original may still be in transient telemetry. Find it using the transientTelemetryId.
NewUser(String, String, NavUserState, DateTime, String, Boolean, LicenseType, String, String, Boolean, DateTime, String, String, String, Guid, String, String, Nullable`1) FAILURE.
RootException: FaultException`1
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TelemetryCombinator(Category telemetryCategory, Verbosity telemetryVerbosity, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TelemetryCombinator(Category telemetryCategory, Verbosity telemetryVerbosity, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TelemetryCombinator(Category telemetryCategory, Verbosity telemetryVerbosity, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass6_0.<Create>b__0(ServiceOperation operation, NSServiceBase instance, MethodBase syncMethodLocal, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
   at System.ServiceModel.Dispatcher.ChannelHandler.DispatchAndReleasePump(RequestContext request, Boolean cleanThread, OperationContext currentOperationContext)
   at System.ServiceModel.Dispatcher.ChannelHandler.HandleRequest(RequestContext request, OperationContext currentOperationContext)
   at System.ServiceModel.Dispatcher.ChannelHandler.AsyncMessagePump(IAsyncResult result)
   at System.ServiceModel.Dispatcher.ChannelHandler.OnAsyncReceiveComplete(IAsyncResult result)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceiveAsyncResult.OnReceive(IAsyncResult result)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.SynchronizedMessageSource.ReceiveAsyncResult.OnReceiveComplete(Object state)
   at System.ServiceModel.Channels.SessionConnectionReader.OnAsyncReadComplete(Object state)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security.NegotiateStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.ReadCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.ConnectionStream.IOAsyncResult.OnAsyncIOComplete(Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)


ProcessId: 2952
Tag: 00000ZX
ThreadId: 114
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: c886c7c8-b9f0-4eb7-907b-b2e8fdfd8a50
```

Container Log 2
```
Type: System.ServiceModel.FaultException`1[[Microsoft.Dynamics.Nav.Types.ServerFault, Microsoft.Dynamics.Nav.Types, Version=18.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]
Action: http://www.microsoft.com/Dynamics/NAV/51/ServerFault
Message:
  We could not update the data right now.
  Please try again later.
  
  Technical details:
  A record in table User Property was locked for use in another session. Administrators can see current locks on the Database Locks page or use telemetry. (Snapshot ID: 55229c7f-1f58-4545-b7b6-b4114fadf33e)
StackTrace:
  
  Server stack trace: 
     at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
  
  Exception rethrown at [0]: 
     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
     at Microsoft.Dynamics.Nav.Types.INCLAdminService.NewUser(String userName, String fullName, NavUserState state, DateTime expiryDate, String sid, Boolean changePassword, LicenseType licenseType, String passwordHash, String authenticationKey, Boolean webServicesKey, DateTime webServicesKeyExpiryDate, String authenticationEmail, String contactEmail, String profileId, Guid applicationId, String company, String languageId, Nullable`1 profileAppId)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.NewNavServerUser.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: mscorlib
HResult: -2146233087
StackTrace:
  
  Server stack trace: 
     at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
  
  Exception rethrown at [0]: 
     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
     at Microsoft.Dynamics.Nav.Types.INCLAdminService.NewUser(String userName, String fullName, NavUserState state, DateTime expiryDate, String sid, Boolean changePassword, LicenseType licenseType, String passwordHash, String authenticationKey, Boolean webServicesKey, DateTime webServicesKeyExpiryDate, String authenticationEmail, String contactEmail, String profileId, Guid applicationId, String company, String languageId, Nullable`1 profileAppId)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.NewNavServerUser.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
```

**Comment by freddydk** [comment]
could you try to use hyperv isolation?

**Comment by lktraser** [comment]
You are correct with `isolation                     = 'hyperv'` the script runs without a problem. Would you say it makes sense to run in this isolation mode in all cases? If so then I would include it in our powershell module.

**Comment by freddydk** [comment]
Sorry about the delay.
I don't know why hyperv isolation would solve this, I have not seen differences like this in hyperv vs. process isolation before.
It might be something locally on the docker host causing this
