### ISSUE TITLE
How to run API tests in a BC container?

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#2079]
### Issue
I raised the question a couple of days ago on [yammer](https://www.yammer.com/dynamicsnavdev/threads/1383604008484864). And Nikola Kukrika noted that this can only be done in a database that has no users and is access using Windows authentication. This is because, as he writes: "If there is a different authentication or an user in a database, the authorization must be implemented, and we have not done this one."
So, I tried to get this done with a BC container. But apparently `New-BcContainer` always inserts a user in the database.
@freddydk, you suggested to at to following parameter to the `New-BcContainer` call:

```
-myscripts @( @{ "SetupNavUsers.ps1" = "Write-Host 'Skipping user creation'" } )
```
As reported on yammer, this indeed prevents a user to be added, but also throws an error when in VS Code I try to download symbols from this database:

```
'The system cannot contact a domain controller to service the authentication request. Please try again later.'

   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Deployment.Telemetry.TelemetryHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Telemetry\TelemetryHttpClientHandler.cs:line 61
   at Microsoft.Dynamics.Nav.Deployment.Http.NavHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Http\NavHttpClientHandler.cs:line 35
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Deployment.ApiClients.ServerInfoApiClient.GetServerInfo() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ApiClients\ServerInfoApiClient.cs:line 46
   at Microsoft.Dynamics.Nav.Deployment.ApiClients.PackagesApiClient.SendRequest(IHttpClient client, SymbolReferenceSpecification reference) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ApiClients\PackagesApiClient.cs:line 130
   at Microsoft.Dynamics.Nav.Deployment.ApiClients.PackagesApiClient.DownloadPackage(IHttpClient client, SymbolReferenceSpecification specification, String directory, Boolean isSecondLevelDependency) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ApiClients\PackagesApiClient.cs:line 164
   at Microsoft.Dynamics.Nav.Deployment.ApiClients.PackagesApiClient.DownloadPackages(ImmutableArray`1 references, String targetDir) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ApiClients\PackagesApiClient.cs:line 56
   at Microsoft.Dynamics.Nav.Deployment.ReferenceDownloader.NavDevServerPackageDownloader.DownloadPackages(ImmutableArray`1 packages, String targetDirectory) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\ReferenceDownloader\NavDevServerPackageDownloader.cs:line 32
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.DownloadFiles(DownloadSymbolsRequest request, String cacheDirectory, ImmutableArray`1 referencesToDownload) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 124
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.DownloadSymbolsRequestHandler.ProcessRequestAsync(DownloadSymbolsRequest request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\DownloadSymbolsRequestHandler.cs:line 93
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`2.HandleAsync(T request, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.RequestHandlerBase`1.HandleAsync(JToken requestContents, Int32 requestId, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\RequestHandlerBase.cs:line 65
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.Process(Message message) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 80```
```

### Now what do I want to achieve exactly?
I want to run tests that check my own API page [APIV1LookupValues.Page.al](https://github.com/PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central-Second-Edition/blob/BC18/Chapter%2013%20(LookupValue%20Extension)/src/page/APIV1LookupValues.Page.al).. This will be part of the 2nd edition of my book for which the code can be found in the [Chapter 13 folder](https://github.com/PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central-Second-Edition/tree/BC18/Chapter%2013%20(LookupValue%20Extension)) of the accompanying GitHub repo (branch BC18, not main). This folder contains both the app en test code of the **LookupValue** extension and should be able to be deployed. The API tests are stored in codeunit: [APIV1LookupValuesE2E.Codeunit.al](https://github.com/PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central-Second-Edition/blob/BC18/Chapter%2013%20(LookupValue%20Extension)/test/APIV1LookupValuesE2E.Codeunit.al).

Hope this makes sense enough.

**Comment by freddydk** [comment]
What is the full command you use for creating the container?

**Comment by lvanvugt** [comment]
```
# set accept_eula to $true to accept the eula found here: https://go.microsoft.comfwlink/?linkid=861843
$accept_eula = $true

# container name and version
$containerName = 'd365bc18WA'

$artifactUrl = Get-BCArtifactUrl -type OnPrem -country "w1" -version "18"

$licenseFile = "https://www.dropbox.com/...."

New-BCContainer -accept_eula:$accept_eula `
                -containerName $containerName `
                -artifactUrl $artifactUrl `
                -licenseFile $licenseFile `
                -auth Windows `
                -credential $credential `
                -memoryLimit:10GB `
                -updateHost `
                -shortcuts StartMenu `
                -isolation process `
                -includeTestToolkit `
                -includeTestLibrariesOnly `
                -myscripts @( @{ "SetupNavUsers.ps1" = "Write-Host 'Skipping user creation'" } )
```

**Comment by freddydk** [comment]
Yeah, so you get a container without users.
But obviously that cannot be used from VS Code - but do you need VS Code to run the API tests?
Couldn't you publish your app and run the tests from PowerShell?

**Comment by lvanvugt** [comment]
Nope, don't need VSCode to run the tests, but need VSCode to develop and deploy the extension.
Hadn't only slightly thought of publishing the app through PowerShell, but thought it would throw the same error. But reading "between the lines" of your last question I reckon that should be possible. Let me try that one and get to you.

**Comment by freddydk** [comment]
Publish-BcContainerApp without -useDevEndpoint will not need the credentials as it doesn't actually connect to BC

**Comment by freddydk** [comment]
In the meantime, I will check whether I can launch the test runner from PowerShell without creating a user.

**Comment by freddydk** [comment]
Run-TestsInBcContainer will create a Windows User and if I disable that - it crashes.
It seems like the client Service endpoint does not support a database without users.
You should be able to login to the WebClient and run the tests though - not sure whether we would ever be able to support this through the client services endpoint (i.e. PowerShell)

**Comment by freddydk** [comment]
I stand corrected.
With a small fix to Run-TestsInBcContainer, it actually does work.
This script:
```
$licenseFile = $LicenseFileSecret.SecretValue | Get-PlainText
if (-not $windowsCredential) {
    $windowsCredential = get-credential
}
$auth = "Windows"
$artifactUrl = Get-BCArtifactUrl -country us -type OnPrem -storageAccount bcpublicpreview
New-BcContainer `
    -accept_eula `
    -artifactUrl $artifactUrl `
    -auth $auth `
    -Credential $windowsCredential `
    -licenseFile $licenseFile `
    -myscripts @( @{ "SetupNavUsers.ps1" = "Write-Host 'Skipping user creation'" } )

Import-TestToolkitToBcContainer -includeTestFrameworkOnly
Publish-BcContainerApp -skipVerification -appFile "C:\Users\freddyk\Dropbox\Shared\BingMaps\apps.zip" -sync -install
Publish-BcContainerApp -skipVerification -appFile "C:\Users\freddyk\Dropbox\Shared\BingMaps\testapps.zip" -sync -install
Run-TestsInBcContainer -extensionId '8d4a154b-8c4c-482a-ac1b-a09ee4ed7834' -detailed
```

Outputs:
```
  Codeunit 70131 BingMaps Test Success (8.243 seconds)
    Testfunction RoleCenterNotification Success (0.183 seconds)
    Testfunction ServiceConnection Success (0.104 seconds)
    Testfunction SetupBingMaps Success (0.166 seconds)
    Testfunction CreateCustomer Success (0.017 seconds)
    Testfunction RenameCustomer Success (0.187 seconds)
    Testfunction DeleteCustomer Success (0 seconds)
    Testfunction BingMapsOnCustomerCard Success (4.643 seconds)
    Testfunction BingMapsOnCustomerList Success (2.33 seconds)
    Testfunction BingMapsShowAllOnCustomerCard Success (0.406 seconds)
    Testfunction BingMapsShowAllOnCustomerList Success (0.207 seconds)
  Codeunit 70132 BingMaps Test2 Success (5.223 seconds)
    Testfunction RoleCenterNotification Success (0.2 seconds)
    Testfunction ServiceConnection Success (0.083 seconds)
    Testfunction SetupBingMaps Success (0.18 seconds)
    Testfunction CreateCustomer Success (0.01 seconds)
    Testfunction RenameCustomer Success (0.123 seconds)
    Testfunction DeleteCustomer Success (0.017 seconds)
    Testfunction BingMapsOnCustomerCard Success (4.61 seconds)
```

at the end.

**Comment by lvanvugt** [comment]
Great, when will it be available?

**Comment by freddydk** [comment]
in ~3 hours in a preview bccontainerhelper

**Comment by freddydk** [comment]
Buildmachine was in limbo stage:-( - takes some more time..

**Comment by freddydk** [comment]
The latest preview has this change.

**Comment by lvanvugt** [comment]
I finally did get the API tests working on a local installation with some help from Onat Buyukakkus. Yeahhh.
Now I am going to check it on docker.

**Comment by lvanvugt** [comment]
Halted by #2083 (wanted to run that first before I would install the preview)

**Comment by lvanvugt** [comment]
> Halted by #2083 (wanted to run that first before I would install the preview)

OK, that one is tackled.

Meanwhile, before using the preview with the fix I tested the following:

1. Created BC18 container
   - with Windows authentication
   - opening web client and logging in
   - deploying app and tests
   - add tests to AL Test Tool
   - set test runner to _130451 - Test Runner - Isol. Disabled_
   - removed all user related records using MSSSMS
   - ran tests **successfully**
1. Created BC18 container
   - with Windows authentication
   - without user by adding `-myscripts @( @{ "SetupNavUsers.ps1" = "Write-Host 'Skipping user creation'" } )` to `New-BCContainer`
   - can **not** login into web client

**Comment by freddydk** [comment]
I tried (2) - works fine if I specify my host computers windows credentials as -credential.

Just to be sure - in your 2. attempt - did you specify your host windows credentials as -credential?

**Comment by lvanvugt** [comment]
> Just to be sure - in your 2. attempt - did you specify your host windows credentials as -credential?

Nope and thought I had removed the `-credential` part. Will retest with (and without).

**Comment by freddydk** [comment]
The container needs to have the Windows User (same as on host) created - else Windows Auth. won't work

**Comment by lvanvugt** [comment]
> I tried (2) - works fine if I specify my host computers windows credentials as -credential.

Tested and indeed works like a charm with `BcContainerHelper` **2.0.15** and running tests from _AL Test Tool_ in _web client_.

Next test to trigger the tests with `Run-TestsInBcContainer`.

**Comment by freddydk** [comment]
for that you need the latest 2.0.16 preview

**Comment by lvanvugt** [comment]
Some time ago that I installed the preview. Thought it would installed using the `-AllowPrerelease` parameter on the `Install-Module`.
So, I run:
```
Install-Module -Name bccontainerhelper -force -AllowPrerelease
```

But do get the error:
```
Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
```
Something has changed on this?

**Comment by lvanvugt** [comment]
Apparently my PowerShellGet is outdated.

**Comment by lvanvugt** [comment]
Ran
```
# container name and version
$containerName = 'd365bc18WA'

# set credentials for using with Windows
$login = 'yyy'
$password = 'xxxx'
$securepassword = (ConvertTo-SecureString -String $password -AsPlainText -Force)
$credential = New-Object System.Management.Automation.PSCredential($login, $securepassword)

Run-TestsInBcContainer -containerName $containerName `
                       -credential $credential `
                       -extensionId 'e26890f8-fafe-49c6-8951-2c1457921f9b' `
                       -detailed
```

with positive result:

![image](https://user-images.githubusercontent.com/18466198/133919094-98cbca07-1adb-4208-a298-d6331cf33122.png)

So, **tested and ok**.

Thanx for the help and fix, @freddydk.

**Comment by freddydk** [comment]
Awesome, thanks

**Comment by lvanvugt** [comment]
I have an additional query related to this issue: as these API tests need to be run with test isolation disabled - using  the test runner **130451 - Test Runner - Isol. Disabled** -, how can I get this done without having to set the test manually on the AL Test Tool?
For this I have opened a new issue: #2084.
