### ISSUE TITLE
Compiling app in NextMajor is failing with AL compiler error

### ISSUE THREAD

**Issue by amea20** [microsoft/navcontainerhelper#2529]
**Describe the issue**
When trying to compile the app as a  SaaS solution in the NextMajor container, I get a AL compiler error

**Scripts used to create container and cause the issue**
```
Compile-AppInBcContainer -containerName bc `
                         -appProjectFolder $projectFolder `
                         -appOutputFolder $outputFolder `
                         -credential $credential
```

**Full output of scripts**
```
Compiling...
.\alc.exe /project:"C:\Agents\nav-app\app" /packagecachepath:"C:\Agents\nav-app\app\.alpackages" /out:"C:\Agents\nav-app\app\Company_N
avApp_1.2.3.4.app" /assemblyprobingpaths:"C:\Program Files\Microsoft Dynamics NAV\210\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\Windows\Microsoft.NET\Assembly","C:\Te
st Assemblies\Mock Assemblies"
Microsoft (R) AL Compiler version 10.0.9.46544
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'NavApp' containing '8314' files at '11:46:30.128'.


Compilation ended at '11:47:01.929'.

System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.IsPropertyDependencySatisifiedWithDefaultValue(PropertyTypeInfo propertyInfo, DependentProperty dependentProperty
) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 450
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.IsPropertyDependencySatisfied(Symbol symbolWithDependentProperties, DependentProperty dependentProperty) in D:\a\
1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 355
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.CheckDependentProperties(Symbol symbolWithProperties, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsof
t.Dynamics.Nav.CodeAnalysis\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 158
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.DefaultVisit(Symbol symbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysi
s\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 57
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.VisitAction(ActionSymbol symbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAn
alysis\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 500
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ActionSymbol.Accept[TArgument,TResult](SymbolVisitor`2 visitor, TArgument a) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Gene
rated\Symbols.Generated.cs:line 116
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.VisitMembersOfSymbol(Symbol symbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Cod
eAnalysis\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 150
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.DefaultVisit(Symbol symbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysi
s\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 63
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.VisitAction(ActionSymbol symbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAn
alysis\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 500
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ActionSymbol.Accept[TArgument,TResult](SymbolVisitor`2 visitor, TArgument a) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Gene
rated\Symbols.Generated.cs:line 116
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.VisitMembersOfSymbol(Symbol symbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Cod
eAnalysis\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 150
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.DefaultVisit(Symbol symbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysi
s\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 63
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor`2.VisitContainer(ContainerSymbol node, TArgument argument) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generate
d\SymbolVisitorWithArgumentAndResult.Generated.cs:line 326
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor`2.VisitType(TypeSymbol node, TArgument argument) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SymbolVi
sitorWithArgumentAndResult.Generated.cs:line 331
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor`2.VisitObjectType(ObjectTypeSymbol node, TArgument argument) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Genera
ted\SymbolVisitorWithArgumentAndResult.Generated.cs:line 336
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor`2.VisitRequestPageType(RequestPageTypeSymbol node, TArgument argument) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnaly
sis\Generated\SymbolVisitorWithArgumentAndResult.Generated.cs:line 281
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.RequestPageTypeSymbol.Accept[TArgument,TResult](SymbolVisitor`2 visitor, TArgument a) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnal
ysis\Generated\Symbols.Generated.cs:line 1199
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.VisitMembersOfSymbol(Symbol symbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.Cod
eAnalysis\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 150
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolWithPropertiesVisitor.DefaultVisit(Symbol symbol, DiagnosticBag diagnostics) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysi
s\Symbols\PropertyVisitor\SymbolWithPropertiesVisitor.cs:line 63
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor`2.VisitContainer(ContainerSymbol node, TArgument argument) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generate
d\SymbolVisitorWithArgumentAndResult.Generated.cs:line 326
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor`2.VisitType(TypeSymbol node, TArgument argument) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SymbolVi
sitorWithArgumentAndResult.Generated.cs:line 331
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor`2.VisitObjectType(ObjectTypeSymbol node, TArgument argument) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Genera
ted\SymbolVisitorWithArgumentAndResult.Generated.cs:line 336
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor`2.VisitApplicationObjectType(ApplicationObjectTypeSymbol node, TArgument argument) in D:\a\1\s\source\Prod\Microsoft.Dynamics.N
av.CodeAnalysis\Generated\SymbolVisitorWithArgumentAndResult.Generated.cs:line 341
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor`2.VisitReportType(ReportTypeSymbol node, TArgument argument) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Genera
ted\SymbolVisitorWithArgumentAndResult.Generated.cs:line 271
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReportTypeSymbol.Accept[TArgument,TResult](SymbolVisitor`2 visitor, TArgument a) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\
Generated\Symbols.Generated.cs:line 1161
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileProperties(ContainerSymbol containingType) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.
cs:line 267
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileObject(ObjectTypeSymbol containingType) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:
line 171
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.VisitObjectType(ObjectTypeSymbol symbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 1
61
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.SymbolVisitor.VisitReportType(ReportTypeSymbol node) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\SymbolVisitor.Gene
rated.cs:line 271
   at Microsoft.Dynamics.Nav.CodeAnalysis.Symbols.ReportTypeSymbol.Accept(SymbolVisitor visitor) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Generated\Symbols.Generated.cs:lin
e 1151
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.<>c__DisplayClass11_0.<CompileModule>b__0(Symbol memberSymbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\Me
thodCompiler.cs:line 129
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileModule(ModuleSymbol moduleSymbol) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 1
40
   at Microsoft.Dynamics.Nav.CodeAnalysis.MethodCompiler.CompileMethodBodies(Compilation compilation, ModuleBuilder moduleBeingBuiltOpt, Boolean hasDeclarationErrors, DiagnosticBag diagnostic
s, Predicate`1 filterOpt, Predicate`1 radCompilationFilter, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compiler\MethodCompiler.cs:line 10
3
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.CompileImpl(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilatio
nFilter, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 1031
   at Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Compile(ModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, Predicate`1 radCompilationFil
ter, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\Compilation\Compilation.cs:line 1003
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.PackageTheModule(Compilation compilation, CompilerTextWriter consoleOutput, CancellationToken cancellationToken, ErrorLogg
er errorLogger, AnalyzerDriver analyzerDriver, Predicate`1 filterOpt, Predicate`1 radCompilationFilter) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.
cs:line 721
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCoreImpl(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, Compilation compilation, AnalyzerDriver analyzerDri
ver, IEnumerable`1 analyzerExceptionDiagnostics, IEnumerable`1 additionalTextFiles, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLin
e\CommonCompiler.cs:line 548
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.RunCore(CompilerTextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in D:\a\1\s\source
\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\CommandLine\CommonCompiler.cs:line 479
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.CommonCompiler.Run(CompilerTextWriter consoleOutput, CancellationToken cancellationToken) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.
CodeAnalysis\CommandLine\CommonCompiler.cs:line 333
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.Alc.<>c__DisplayClass1_0.<Run>b__0(CompilerTextWriter textWriterOut, CompilerTextWriter _) in D:\a\1\s\source\Prod\alc\Alc.cs:line 37
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.ConsoleUtil.RunWithOutput[T](Boolean useUtf8Encoding, Func`3 func) in D:\a\1\s\source\Prod\alc\ConsoleUtil.cs:line 25
   at Microsoft.Dynamics.Nav.CodeAnalysis.CommandLine.Alc.Run(String clientDirectory, String baseDirectory, String[] args, IAnalyzerAssemblyLoader analyzerLoader) in D:\a\1\s\source\Prod\alc\
Alc.cs:line 37
App generation failed with exit code -1
Compile-AppInBcContainer Telemetry Correlation Id: 6d2e7783-6ab5-4991-8095-4b7d2abcd029
App generation failed with exit code -1
At C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\3.0.10\AppHandling\Compile-AppInNavContainer.ps1:651 char:72
+ ... | Where-Object { $_ -like "App generation failed*" } | % { throw $_ }
+                                                                ~~~~~~~~
    + CategoryInfo          : OperationStopped: (App generation failed with exit code -1:String) [], RuntimeException
    + FullyQualifiedErrorId : App generation failed with exit code -1
...
```

**Additional context**
- It happens all the time
- It never worked for V21
- I was hoping you could help shed some light on this.

**Comment by freddydk** [comment]
I haven't seen this before. An example of a pipeline passing nextmajor is here: https://github.com/BusinessCentralApps/BingMaps.PTE/runs/6908895843?check_suite_focus=true

It seems to be something specific in either your code or script.

You could create an AL-Go repo using https://aka.ms/al-go-appsource - upload your apps and create the necessary secrets and see whether next major works here?

**Comment by amea20** [comment]
I was worried about that. I managed to successfully publish a small dummy app with barely anything in there. I was also able to do that with the BingMaps app. Can you advise where I can go to find out why it fails to compile with the new AL compiler version?

**Comment by freddydk** [comment]
Any chance you could give me temp. access to the repo and I will have a look and see if I can figure out what's wrong?

**Comment by freddydk** [comment]
Just emailed you that I didn't get the attachment.
Could you retry with the latest nextmajor before sending me the url?
(Just to make sure that the team didn't fix this. I assume that this is a bug in the compiler)

**Comment by amea20** [comment]
The issue remains with trying to package it. I've sent you a SAS url of the zip file which will expire in 7 days.

**Comment by amea20** [comment]
Hi Freddy,

I have raised this as a AL Compiler issue, since it's tied to the AL compiler version being used

Link: https://github.com/microsoft/AL/issues/7103
