### ISSUE TITLE
Unable to connect to Tenant

### ISSUE THREAD

**Issue by AmandaTest** [microsoft/navcontainerhelper#2551]
I'm try to simulate a cloud environment in my sandbox with the BC insider builds.  I am able to do so with the artifacts from the minor builds but not the next major one.

The error that pops up after logging in, is "You cannot sign in due to a technical issue. Contact your system.administrator."

It works fine, if I use a minor release

From the container event log I see the following error and the warning just before it:
Application: Microsoft.Dynamics.Nav.Server.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException

Server stack trace: 
   at Microsoft.Dynamics.Nav.Cloud.Statistics.TenantStatisticsTracker.Dispose()
   at Microsoft.Dynamics.Nav.Runtime.NavEnvironment.Dispose(Boolean disposing)
   at Microsoft.Dynamics.Nav.Runtime.NavEnvironment.DisposeIfInitialized()
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.DisposeNavEnvironment()
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
   at System.Runtime.Remoting.Proxies.RealProxy.EndInvokeHelper(System.Runtime.Remoting.Messaging.Message, Boolean)
   at System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(System.Object, System.Runtime.Remoting.Proxies.MessageData ByRef)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService+DisposeDelegate.EndInvoke(System.IAsyncResult)
   at System.Runtime.Remoting.Messaging.AsyncResult.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessageSink)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Here is the warning:**

The operating system cannot run Server instance: BC
Tenant: 
Environment Name: 
Environment Type: 
The service could not remove service principal names because the service account could not be found in Active Directory.
Account: NT AUTHORITY\SYSTEM
Service principal names:
DynamicsNAV/mycompany-cd:7045
DynamicsNAV/mycompany-cd:7045
To avoid this warning, make sure the server account is provisioned correctly (see https://go.microsoft.com/fwlink/?linkid=874634 ).. 

**Scripts used to create container and cause the issue**
attached
[CreateContainer-SR365-Maj (CD) (3).txt](https://github.com/microsoft/navcontainerhelper/files/8971127/CreateContainer-SR365-Maj.CD.3.txt)

**Full output of scripts**
attached
[output.txt](https://github.com/microsoft/navcontainerhelper/files/8971164/output.txt)

**Screenshots**

**Additional context**
- does it happen all the time? Only for major release (minor release is fine)
- did it use to work? No.  This is new.
![Errormessage](https://user-images.githubusercontent.com/28625572/175407067-40e1590d-5a6a-4c3e-ac38-5845ba8cc892.png)

**Comment by freddydk** [comment]
Is this problem new?
Since when did this happen?

**Comment by AmandaTest** [comment]
Yes. We have been using username/Password for years and have no issues with that. But here, we are trying out AAD connection in our sandbox.

**Comment by freddydk** [comment]
It looks like a bug in the platform / client.
For now, you will have to not use AAD for insiders until fixed
