### ISSUE TITLE
Import-TestToolkitToBcContainer fails with unexpected error

### ISSUE THREAD

**Issue by Silentapproach** [microsoft/navcontainerhelper#2630]
We create container on a regular basis. Every once in a while we also import the testtoolkit. 

1. We create the container with the parameters "IncludeTestToolkit" and "IncludeTestLibrariesOnly"
2. Then we need to restart the service because of some basic configurations that we need to do.
3. After that we run the "Import-TestToolkitToBcContainer" command in the following fashion:

```powershell
Import-TestToolkitToBcContainer -containerName $containerName -includeTestLibrariesOnly -ErrorAction Stop
```

We then get the following error (There could be signs in the callstack of our own scripts):

```powershell
Importing TestToolkit
PS>TerminatingError(): "Der ausgeführte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: The tenant 'default' is not accessible.."
The tenant 'default' is not accessible.

Exception Script Stack Trace:
at <ScriptBlock>, <No file>: line 3

PowerShell Call Stack:
bei Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1: Zeile 71
bei <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.11\ObjectHandling\Import-TestToolkitToNavContainer.ps1: Zeile 198
bei Import-TestToolkitToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.11\ObjectHandling\Import-TestToolkitToNavContainer.ps1: Zeile 180
bei Import-TestToolkit<Process>, C:\DockerMgt\modules\pre-and-post-build-operations.ps1: Zeile 572
bei Start-PostContainerOperations, C:\DockerMgt\modules\pre-and-post-build-operations.ps1: Zeile 345
bei Start-ContainerBuild<Process>, C:\DockerMgt\modules\container-build.ps1: Zeile 229
bei <ScriptBlock>, C:\DockerMgt\mgt\start-container-build.ps1: Zeile 23
bei <ScriptBlock>, <Keine Datei>: Zeile 1
INFO: 
Container Free Physical Memory: 24.6Gb
INFO: 
Services in container Test-Container:
INFO: - MicrosoftDynamicsNavServer$BC is Running
INFO: - MSSQL$SQLEXPRESS is Running
INFO:
INFO: 
Relevant event log from container Test-Container:
INFO: - 20220802 11:10:22 - MicrosoftDynamicsNavServer$BC
INFO: 
  Server instance: BC
  Category: Extensions
  ClientSessionId: beb4e1c1-56bd-44d9-9066-1177dff811c5
  ClientActivityId: 01cc91b3-874e-4eea-ab75-d65d0426f927
  ServerSessionUniqueId: b45d3bed-395b-49a9-9adc-3dd12f368662
  ServerActivityId: c3b36f42-cf37-4010-afe7-8301e67e29cb
  EventTime: 08/02/2022 09:10:22
  Message (FaultException`1): GetNavAppInfo(GetNavAppInfoArguments) FAILURE.
  RootException: FaultException`1
  ExceptionStackTrace:
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PartnerTelemetryErrorCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase m, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PartnerTelemetryPermissionErrorCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TelemetryCombinator(Category telemetryCategory, Verbosity telemetryVerbosity, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
  CallerStackTrace:
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TelemetryCombinator(Category telemetryCategory, Verbosity telemetryVerbosity, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PartnerTelemetryErrorCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase m, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PartnerTelemetryPermissionErrorCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TelemetryCombinator(Category telemetryCategory, Verbosity telemetryVerbosity, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass6_0.<Create>b__0(ServiceOperation operation, NSServiceBase instance, MethodBase syncMethodLocal, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass14_0.<PerformanceCounterCombinator>b__0()
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
     at System.ServiceModel.Dispatcher.ChannelHandler.DispatchAndReleasePump(RequestContext request, Boolean cleanThread, OperationContext currentOperationContext)
     at System.ServiceModel.Dispatcher.ChannelHandler.HandleRequest(RequestContext request, OperationContext currentOperationContext)
     at System.ServiceModel.Dispatcher.ChannelHandler.AsyncMessagePump(IAsyncResult result)
     at System.ServiceModel.Dispatcher.ChannelHandler.OnAsyncReceiveComplete(IAsyncResult result)
     at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
     at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceiveAsyncResult.OnReceive(IAsyncResult result)
     at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
     at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
     at System.ServiceModel.Channels.SynchronizedMessageSource.ReceiveAsyncResult.OnReceiveComplete(Object state)
     at System.ServiceModel.Channels.SessionConnectionReader.OnAsyncReadComplete(Object state)
     at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
     at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
     at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
     at System.Net.Security.NegotiateStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.NegotiateStream.ReadCallback(AsyncProtocolRequest asyncRequest)
     at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
     at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
     at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
     at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
     at System.ServiceModel.Channels.ConnectionStream.IOAsyncResult.OnAsyncIOComplete(Object state)
     at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
     at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
     at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
  
  
  ProcessId: 33080
  Tag: 00000ZX
  ThreadId: 31
  CounterInformation: 
  CustomParameters: {
  }
  GatewayCorrelationId: f3fb3d55-b536-4103-8993-d69af741a536
INFO: - 20220802 11:10:22 - MicrosoftDynamicsNavServer$BC
INFO: 
  Server instance: BC
  Category: Extensions
  ClientSessionId: beb4e1c1-56bd-44d9-9066-1177dff811c5
  ClientActivityId: 01cc91b3-874e-4eea-ab75-d65d0426f927
  ServerSessionUniqueId: b45d3bed-395b-49a9-9adc-3dd12f368662
  ServerActivityId: c3b36f42-cf37-4010-afe7-8301e67e29cb
  EventTime: 08/02/2022 09:10:21
  Message The execution of the code block at GetNavAppInfo had one or more unhandled exceptions.
  ProcessId: 33080
  Tag: 00000GQ
  ThreadId: 31
  CounterInformation: 
  CustomParameters: {
  }
  GatewayCorrelationId: f3fb3d55-b536-4103-8993-d69af741a536
INFO: - 20220802 11:10:22 - MicrosoftDynamicsNavServer$BC
INFO: 
  Server instance: BC
  Category: Runtime
  ClientSessionId: beb4e1c1-56bd-44d9-9066-1177dff811c5
  ClientActivityId: 01cc91b3-874e-4eea-ab75-d65d0426f927
  ServerSessionUniqueId: c2bd61f3-37ee-47e1-8c63-ddd805bc08af
  ServerActivityId: 978d2061-3559-4066-a5db-c52f5285dd61
  EventTime: 08/02/2022 09:10:21
  Message (NavTenantNotAccessibleException): RootException: NavTenantNotAccessibleException
  The tenant 'default' is not accessible.
  CallerStackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavSession.CheckPreconditions(NavTenant tenant, TimeZoneInfo clientTimeZone, NavUserAuthentication navUserAuthentication, Boolean isSystemSession, ConnectionType connectionType)
     at Microsoft.Dynamics.Nav.Runtime.NavSession.Open(Boolean useUserPersonalization, Byte[] licenseToUse, Boolean allowAppsDisabledMode)
     at Microsoft.Dynamics.Nav.Runtime.NavTenant.Microsoft.Dynamics.Nav.Runtime.ITenantSessionHandler.RunTenantActionInSystemSession(Action`2 action, Boolean throwExceptions, Boolean useCurrentCulture, Boolean allowAppsDisabledMode, LanguageSetting language, NavCancellationToken cancellationToken)
     at Microsoft.Dynamics.Nav.Service.NSAdminService.<>c__DisplayClass62_0`1.<RunActionOnRequestedTenant>b__0()
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.<>c__DisplayClass1_0`1.<SendTraceTagOnFailure>b__0()
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.SendTraceTagOnFailure(Action operation, String additionalInfo, Func`2 exceptionMap, String callerName)
     at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppDiagnosticSession.SendTraceTagOnFailure[T](Func`1 operation, String additionalInfo, Func`2 exceptionMap, String callerName)
     at Microsoft.Dynamics.Nav.Service.NSAdminService.Microsoft.Dynamics.Nav.Types.INCLAdminService.GetNavAppInfo(GetNavAppInfoArguments getNavAppInfoArguments)
     at SyncInvokeGetNavAppInfo(Object , Object[] , Object[] )
     at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PartnerTelemetryErrorCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase m, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PartnerTelemetryPermissionErrorCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TelemetryCombinator(Category telemetryCategory, Verbosity telemetryVerbosity, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass6_0.<Create>b__0(ServiceOperation operation, NSServiceBase instance, MethodBase syncMethodLocal, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass14_0.<PerformanceCounterCombinator>b__0()
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass32_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
     at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
     at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
     at System.ServiceModel.Dispatcher.ChannelHandler.DispatchAndReleasePump(RequestContext request, Boolean cleanThread, OperationContext currentOperationContext)
     at System.ServiceModel.Dispatcher.ChannelHandler.HandleRequest(RequestContext request, OperationContext currentOperationContext)
     at System.ServiceModel.Dispatcher.ChannelHandler.AsyncMessagePump(IAsyncResult result)
     at System.ServiceModel.Dispatcher.ChannelHandler.OnAsyncReceiveComplete(IAsyncResult result)
     at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
     at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceiveAsyncResult.OnReceive(IAsyncResult result)
     at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
     at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
     at System.ServiceModel.Channels.SynchronizedMessageSource.ReceiveAsyncResult.OnReceiveComplete(Object state)
     at System.ServiceModel.Channels.SessionConnectionReader.OnAsyncReadComplete(Object state)
     at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
     at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
     at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
     at System.Net.Security.NegotiateStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.NegotiateStream.ReadCallback(AsyncProtocolRequest asyncRequest)
     at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
     at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
     at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
     at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
     at System.ServiceModel.Channels.ConnectionStream.IOAsyncResult.OnAsyncIOComplete(Object state)
     at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
     at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
     at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
  
  
  ProcessId: 33080
  Tag: 00001CH
  ThreadId: 31
  CounterInformation: 
  CustomParameters: {
  }
  GatewayCorrelationId: f3fb3d55-b536-4103-8993-d69af741a536
PS>TerminatingError(): "The tenant 'default' is not accessible."
>> TerminatingError(): "The tenant 'default' is not accessible."
PS>TerminatingError(): "The tenant 'default' is not accessible."
The tenant 'default' is not accessible.
WARNUNG: Importing TestToolkit failed!

```

What could this possibly be? Is it because the tenant is still in a startup-phase from the Restart-NavServerInstance? I personally doubt that because Powershell usually waits until the tenant is up and running? What is your opinion on that?

**Comment by freddydk** [comment]
I do think that tenants are in a startup-phase after restarting the container.
You can run Get-BcContainerTenants to see the state - and wait until it is operational.

**Comment by Silentapproach** [comment]
I restarted my internal service via the "Restart-NavServerInstance"-Command. But I'll try the Get-BcContainerTenants-function

**Comment by freddydk** [comment]
Restart-NavServerInstance is one of the base Cmdlets - they do not wait for anything
ContainerHelper functions are more highlevel

**Comment by freddydk** [comment]
Did this solve the issue?

**Comment by Silentapproach** [comment]
Sorry for the wait, had to do several test cause it is a sometimes thing. For now i would say yes. 

I'm closing this issue
