### ISSUE TITLE
NextMajor (v21) containers fails with -useSSL flag

### ISSUE THREAD

**Issue by jwikman** [microsoft/navcontainerhelper#2639]
**Describe the issue**
The NST cannot start when using `useSSL` for NextMajor containers.

**Scripts used to create container and cause the issue**
```
$artifactUrl = "https://bcinsider.azureedge.net/sandbox/21.0.44908.0/se$sasToken"
New-BCContainer -containerName $containerName `
                -accept_eula -alwaysPull `
                -Auth UserPassword `
                -artifactUrl $artifactUrl `
                -Credential $cred `
                -isolation hyperv `
                -useSSL
```

**Full output of scripts**
```
BcContainerHelper is version 3.0.12
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Enterprise - 21H2
Docker Client Version is 20.10.8
Docker Server Version is 20.10.8
Removing Session nextmajor
Removing container nextmajor
Removing entries from hosts
Removing nextmajor from container hosts file
Removing nextmajor-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\nextmajor
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.20348.887
10.0.20348.887: Pulling from businesscentral
Digest: sha256:8d42b55df9acea2c73c283ed1f8876431c04df2f5717f86b410949468254843f
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.887
mcr.microsoft.com/businesscentral:10.0.20348.887
Using image mcr.microsoft.com/businesscentral:10.0.20348.887
Creating Container nextmajor
Style: sandbox
Multitenant: Yes
Version: 21.0.44908.0
Platform: 21.0.44866.0
Generic Tag: 1.0.2.11
Container OS Version: 10.0.20348.887 (ltsc2022)
Host OS Version: 10.0.22000.856 (21H2)
Using hyperv isolation
Using locale sv-SE
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\nextmajor\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container nextmajor from image mcr.microsoft.com/businesscentral:10.0.20348.887
fd709f869d84ead3598a85584e4edaf2736d8b7bc43ab39f8ce834114cfa9ae2
Waiting for container nextmajor to be ready
Using artifactUrl https://bcinsider.azureedge.net/sandbox/21.0.44908.0/se
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\21.0.44908.0\platform\ServiceTier\Program Files
c:\dl\sandbox\21.0.44908.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\21.0.44908.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\21.0.44908.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\21.0.44908.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\21.0.44908.0\platform
c:\dl\sandbox\21.0.44908.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\21.0.44908.0\se\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\21.0.44908.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\21.0.44908.0\se\Extensions
Copying Applications
C:\dl\sandbox\21.0.44908.0\platform\Applications
Copying Applications.SE
C:\dl\sandbox\21.0.44908.0\se\Applications.SE
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Copying Database on localhost\SQLEXPRESS from tenant to default
Taking database tenant offline
Copying database files
Attaching files as new Database default
Putting database tenant back online
Mounting tenant database
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Stopping Business Central Service Tier
Installation took 100 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.26.144.1 in container hosts file
Starting Container
Hostname is nextmajor
PublicDnsName is nextmajor
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint F5B208014227CB229EB61D5C9875553C8A181177
DNS identity nextmajor
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 377
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcinsider.azureedge.net/sandbox/21.0.44908.0/se
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\21.0.44908.0\platform\ServiceTier\Program Files
c:\dl\sandbox\21.0.44908.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\21.0.44908.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\21.0.44908.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\21.0.44908.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\21.0.44908.0\platform
c:\dl\sandbox\21.0.44908.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\21.0.44908.0\se\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\21.0.44908.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\21.0.44908.0\se\Extensions
Copying Applications
C:\dl\sandbox\21.0.44908.0\platform\Applications
Copying Applications.SE
C:\dl\sandbox\21.0.44908.0\se\Applications.SE
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Copying Database on localhost\SQLEXPRESS from tenant to default
Taking database tenant offline
Copying database files
Attaching files as new Database default
Putting database tenant back online
Mounting tenant database
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Stopping Business Central Service Tier
Installation took 100 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.26.144.1 in container hosts file
Starting Container
Hostname is nextmajor
PublicDnsName is nextmajor
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint F5B208014227CB229EB61D5C9875553C8A181177
DNS identity nextmajor
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 377
at <ScriptBlock>, <No file>: line 1
New-BCContainer Telemetry Correlation Id: 8a4e6f30-dbea-4d5d-8138-e9498ff08904
Initialization of container nextmajor failed
At D:\VSCode\Git\NAB\NAB DevOps Tools\PowerShell\bccontainerhelper\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...extmajor failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container nextmajor failed
 
```
**Errors in container event log**
```
This version of Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
User: 
Type: Microsoft.AspNetCore.Server.HttpSys.HttpSysException
ErrorCode: 183
NativeErrorCode: 183
Message: The prefix 'http://+:7046/BC/client/' is already registered.
StackTrace:
     at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
     at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
     at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start()
     at Microsoft.AspNetCore.Server.HttpSys.MessagePump.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
     at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
     at Microsoft.Dynamics.Nav.Service.AspNetCore.AspNetCoreApiHost.Open()
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartOwinServices()
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartAllServices(ServerUserSettings settings)
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
     at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
     at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)
Source: Microsoft.AspNetCore.Server.HttpSys
HResult: -2147467259
StackTrace:
     at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
     at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
     at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start()
     at Microsoft.AspNetCore.Server.HttpSys.MessagePump.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
     at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
     at Microsoft.Dynamics.Nav.Service.AspNetCore.AspNetCoreApiHost.Open()
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartOwinServices()
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartAllServices(ServerUserSettings settings)
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
     at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
     at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)
 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher. 
```

```
This version of Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
Failed to start service with CLR type Microsoft.Dynamics.Nav.Service.AspNetCore.AspNetCoreApiHost, API type ClientApi and address http://nextmajor:7046/BC/client. is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher. 
```

**Additional context**
- does it happen all the time?
  - Yes, for nextmajor
- did it use to work?
  - Yes, for v20 and earlier

**Comment by freddydk** [comment]
It is a follow-up bug of the one causing generic image version 1.0.2.11 - creating 1.0.2.12 now.

**Comment by jwikman** [comment]
Ok, thanks. I'll keep an eye on https://github.com/microsoft/nav-docker/actions/runs/2845672702 to see when it's time to test again then :)

**Comment by freddydk** [comment]
now!

**Comment by freddydk** [comment]
remember -alwaysPull or run this once:
docker pull (Get-BestGenericImageName)

**Comment by jwikman** [comment]
Yes, I noticed that - already downloading! :)

**Comment by freddydk** [comment]
My brand new generic image generator pipeline works wonders... (sorting images newest first and building 4*5 images at a time)

**Comment by jwikman** [comment]
Fingers crossed... :)

Version: 21.0.44908.0
Platform: 21.0.44866.0
_**Generic Tag: 1.0.2.12**_
Container OS Version: 10.0.20348.887 (ltsc2022)
Host OS Version: 10.0.22000.856 (21H2)
Using hyperv isolation

**Comment by jwikman** [comment]
> My brand new generic image generator pipeline works wonders... (sorting images newest first and building 4*5 images at a time)

Yes, it sure seems so! 👍

**Comment by freddydk** [comment]
![image](https://user-images.githubusercontent.com/10775043/184326624-1024fd3d-0e5c-419f-bd76-32543a971cb8.png)

**Comment by jwikman** [comment]
This now works! 
```
New-BCContainer -containerName $containerName `
                -accept_eula -alwaysPull `
                -Auth UserPassword `
                -artifactUrl $artifactUrl `
                -Credential $cred `
                -isolation hyperv `
                -useSSL
```

I'll proceed and test with my custom scripts and AAD auth.
