### ISSUE TITLE
"Key vault client AAD app certificate has a private key, but it couldn't be accessed" when using Set-BcContainerKeyVaultAadAppAndCertificate

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/navcontainerhelper#2641]
**Describe the issue**
I am trying to give containers access to Azure Key Vault.
For that, I have followed this doc: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/setup-app-key-vault-onprem)
I have not found much more about the command Set-BcContainerKeyVaultAadAppAndCertificate and receive this strange error when running the script (and also in the Event log):
```
Key vault client AAD app certificate has a private key, but it couldn't be accessed.
```

**Scripts used to create container and cause the issue**
```
$certPfxPassword = "A***Z"
$certPfxSecurePassword = ConvertTo-SecureString -String $certPfxPassword -AsPlainText -Force
Set-BcContainerKeyVaultAadAppAndCertificate -containerName bc-master -pfxFile "https://***/capvision-cloud.fr.pfx" -pfxPassword $certPfxSecurePassword -clientId 10***-***-***-***-***fe
```

**Full output of scripts**
```
BcContainerHelper version 3.0.11
BcContainerHelper emits usage statistics telemetry to Microsoft
Downloading certificate file to container
Keyvault Certificate Thumbprint: DB***7E
Restarting Service Tier
ServerInstance 'MicrosoftDynamicsNavServer$BC' failed to reach  status 'Running' on this server due to the following error: 'Cannot start the service.'. Additional information may be in the event log of the server.

Exception Script Stack Trace:
at <ScriptBlock>, <No file>: line 26

PowerShell Call Stack:
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 71
at Set-BcContainerKeyVaultAadAppAndCertificate, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.11\ContainerHandling\Set-BcContainerKeyVaultAadAppAndCertificate.ps1: line 58
at <ScriptBlock>, <No file>: line 1

Container Free Physical Memory: 6.8Gb

Services in container bc-master:
- MicrosoftDynamicsNavServer$BC is Stopped
- MSSQL$SQLEXPRESS is Running


Relevant event log from container bc-master:
- 20220817 02:49:33 - MicrosoftDynamicsNavServer$BC

  Server instance: BC
  Tenant ID:
  Environment Name:
  Environment Type:
  User:
  Type: Microsoft.Dynamics.Nav.Runtime.AppSecrets.AzureKeyVaultAppSecretProviderException
  ErrorCode: -1
  SuppressMessage: False
  ContainsPersonalOrRestrictedInformation: False
  DiagnosticsSuppress: True
  MessageWithoutPrivateInformation: Key vault client AAD app certificate has a private key, but it couldn't be accessed.
  SuppressExceptionCreatedEvent: False
  FatalityScope: None
  ErrorLevel: Error
  Message: Key vault client AAD app certificate has a private key, but it couldn't be accessed.
  StackTrace:
       at Microsoft.Dynamics.Nav.Runtime.AppSecrets.AzureKeyVaultFacade..ctor(String aadAppId, X509Certificate2 aadAppCertificate)
       at Microsoft.Dynamics.Nav.Runtime.Debugger.ResourceExposurePolicyProvider.KeyVaultDynamicPolicyProvider.CreateAndConfigureAzureKeyVaultFacadeBasedOnServerSettings()
       at Microsoft.Dynamics.Nav.Runtime.NavEnvironment..ctor(NavEnvironmentFlags flags)
       at Microsoft.Dynamics.Nav.Runtime.NavEnvironment.get_Instance()
       at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.SetNavEnviroment(String commandLineServiceInstanceName, ServerUserSettings settings)
       at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
       at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
       at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)
  Source: Microsoft.Dynamics.Nav.Ncl
  HResult: -2146233088
  StackTrace:
       at Microsoft.Dynamics.Nav.Runtime.AppSecrets.AzureKeyVaultFacade..ctor(String aadAppId, X509Certificate2 aadAppCertificate)
       at Microsoft.Dynamics.Nav.Runtime.Debugger.ResourceExposurePolicyProvider.KeyVaultDynamicPolicyProvider.CreateAndConfigureAzureKeyVaultFacadeBasedOnServerSettings()
       at Microsoft.Dynamics.Nav.Runtime.NavEnvironment..ctor(NavEnvironmentFlags flags)
       at Microsoft.Dynamics.Nav.Runtime.NavEnvironment.get_Instance()
       at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.SetNavEnviroment(String commandLineServiceInstanceName, ServerUserSettings settings)
       at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
       at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
       at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)


- 20220817 02:49:33 - MicrosoftDynamicsNavServer$BC

  Server instance: BC
  Category: Runtime
  ClientSessionId: 00000000-0000-0000-0000-000000000000
  ClientActivityId: 00000000-0000-0000-0000-000000000000
  ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
  ServerActivityId: f759c801-a2f4-4056-94bb-7b2a991c4c05
  EventTime: 08/17/2022 14:49:33
  Message (AzureKeyVaultAppSecretProviderException): RootException: AzureKeyVaultAppSecretProviderException
  Key vault client AAD app certificate has a private key, but it couldn't be accessed.
  ExceptionStackTrace:
     at Microsoft.Dynamics.Nav.Runtime.AppSecrets.AzureKeyVaultFacade..ctor(String aadAppId, X509Certificate2 aadAppCertificate)
     at Microsoft.Dynamics.Nav.Runtime.Debugger.ResourceExposurePolicyProvider.KeyVaultDynamicPolicyProvider.CreateAndConfigureAzureKeyVaultFacadeBasedOnServerSettings()
     at Microsoft.Dynamics.Nav.Runtime.NavEnvironment..ctor(NavEnvironmentFlags flags)
     at Microsoft.Dynamics.Nav.Runtime.NavEnvironment.get_Instance()
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.SetNavEnviroment(String commandLineServiceInstanceName, ServerUserSettings settings)
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
     at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
     at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)
  CallerStackTrace:
     at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)


  ProcessId: 4172
  Tag: 00008NE
  ThreadId: 1
  CounterInformation:
  CustomParameters: {
  }
  GatewayCorrelationId:
```

**Additional context**

Because the script is giving the access to read the private key to NT AUTHORITY\SYSTEM, I have run Get-NAVServerInstance BC to make sure BC is running with this user. And this is the case:

```
ServerInstance : MicrosoftDynamicsNavServer$BC
DisplayName    : Dynamics 365 Business Central Server [BC]
State          : Stopped
ServiceAccount : NT AUTHORITY\SYSTEM
Version        : 20.0.45122.0
Default        : True
```

I have also tried to give a wrong password, and the script is clearly saying that the password is wrong.

**Comment by freddydk** [comment]
Did you make this work?
What BC version is this?
Have you tried with other BC versions?

**Comment by nicolassaleron** [comment]
I have not been able to make it work. I do not remember the exact version of this attempt but it should have been 20.4.
I have retried today with the artifact 20.6.46752.0-FR and I get the same error.

The context is: we are using key vaults more and more and we cannot test them properly today before sending them to App Source. I would like being able to make proper tests in a sandbox.

**Comment by fvet** [comment]
@nicolassaleron Have you been able to get this working? 

We have 2 main types of development environments:

- **Online sandboxes** (CDX environment) where we publish apps in dev scope via VS Code: apparently those can't access the Azure Key Vaults. According to MS, the app needs to be published first to AppSource and be 100% identical to be able to access the Key Vault ... I don't see how we'll ever succeed in using Key Vault access in combination online sandboxes and dev scope artifacts ... 

@freddydk Any idea on how this should work with AL-Go where online dev sandboxes are used as well?

- **Local docker containers** where we publish apps in dev scope via VS Code: I was about to try this, but due to limited guidance on the subject, I stumbled upon this post. Will try to test soon.

**Comment by nicolassaleron** [comment]
@fvet I have never been able to make it works. To be honest, I have not tried since october 2022.

This is a bit annoying for local docker containers because when developers need to develop/debug such features, we have to give them secrets. Then, these secrets are living on their computer and can be by accident committed to the repos.

**Comment by freddydk** [comment]
I think this should just work - but I will re-check at the earliest possible time.

**Comment by nicolassaleron** [comment]
I am just giving an update on this issue... which in the end was not an issue because it works just fine.

My mistake was the following: I have forgotten to import the domain certificate in the app registration as mentioned in the doc: [Step 3 of Register a key vault reader application in Azure AD](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/setup-app-key-vault-onprem#register-a-key-vault-reader-application-in-azure-ad)
