### ISSUE TITLE
New VM running Server 2019 - cannot build container - hcsshim::CreateComputeSystem c51ab102daed9d7011216b07d8655a6e3b73445a88cffe4da007d64f67d5c1ac: The virtual machine could not be started because a required feature is not installed.

### ISSUE THREAD

**Issue by rsaritzky** [microsoft/navcontainerhelper#2774]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Running inside Docker EE
Container isn't being built with error "hcsshim::CreateComputeSystem c51ab102daed9d7011216b07d8655a6e3b73445a88cffe4da007d64f67d5c1ac: The virtual machine could not be started because a required feature is not installed."

I believe I've installed docker EE and bccontainerhelper 4.0.6 correctly (but am not certain)

**Scripts used to create container and cause the issue**
We use AdvaniaGit so the actual bccontainer call is hidden.  Here's the output

**Full output of scripts**
```
BcContainerHelper is version 4.0.6
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 20.10.9
Docker Server Version is 20.10.21
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Building image custombuild:onprem-9.0.50357.0-na based on mcr.microsoft.com/businesscentral:10.0.17763.3532 with https://bcartifacts.azureedge.net/onprem/9.0.50357.0/na
Pulling latest image mcr.microsoft.com/businesscentral:10.0.17763.3532
10.0.17763.3532: Pulling from businesscentral
Digest: sha256:2d79923d7fd4c55a86ff7446061310d0dedb5d84a7ebaf8e869b6600f5bbad76
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.17763.3532
mcr.microsoft.com/businesscentral:10.0.17763.3532
Generic Tag: 1.0.2.13
Container OS Version: 10.0.17763.3532 (ltsc2019)
Host OS Version: 10.0.17763.3650 (ltsc2019)
Using hyperv isolation
Using license file C:\AdvaniaGIT\License\Cryobank.flf
Files in c:\bcartifacts.cache\xaq51vcd.ap0\my:
Copying Platform Artifacts
c:\bcartifacts.cache\onprem\9.0.50357.0\platform
Copying Database
Copying Licensefile
Copying Installers
C:\bcartifacts.cache\onprem\9.0.50357.0\na\Installers
Copying TestToolKit
C:\bcartifacts.cache\onprem\9.0.50357.0\na\TestToolKit
Copying UpgradeToolKit
C:\bcartifacts.cache\onprem\9.0.50357.0\na\UpgradeToolKit
c:\bcartifacts.cache\xaq51vcd.ap0
[2022-11-10T22:39:27.280843300Z][docker-credential-desktop][W] Windows version might not be up-to-date: The system cannot find the file specified.
Sending build context to Docker daemon    974MB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.3532
 ---> ed2b98b73e0e
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/9.0.50357.0/na filesOnly=False
 ---> Running in cb4356860f91
Removing intermediate container cb4356860f91
 ---> 1d170356e348
Step 3/6 : COPY my /run/
 ---> cfbc70c98edf
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 7be3bc0c274c
Step 5/6 : RUN \Run\start.ps1 -installOnly
 ---> Running in c51ab102daed
BcContainerHelper is version 4.0.6
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 20.10.9
Docker Server Version is 20.10.21
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Building image custombuild:onprem-9.0.50357.0-na based on mcr.microsoft.com/businesscentral:10.0.17763.3532 with https://bcartifacts.azureedge.net/onprem/9.0.50357.0/na
Pulling latest image mcr.microsoft.com/businesscentral:10.0.17763.3532
10.0.17763.3532: Pulling from businesscentral
Digest: sha256:2d79923d7fd4c55a86ff7446061310d0dedb5d84a7ebaf8e869b6600f5bbad76
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.17763.3532
mcr.microsoft.com/businesscentral:10.0.17763.3532
Generic Tag: 1.0.2.13
Container OS Version: 10.0.17763.3532 (ltsc2019)
Host OS Version: 10.0.17763.3650 (ltsc2019)
Using hyperv isolation
Using license file C:\AdvaniaGIT\License\Cryobank.flf
Files in c:\bcartifacts.cache\xaq51vcd.ap0\my:
Copying Platform Artifacts
c:\bcartifacts.cache\onprem\9.0.50357.0\platform
Copying Database
Copying Licensefile
Copying Installers
C:\bcartifacts.cache\onprem\9.0.50357.0\na\Installers
Copying TestToolKit
C:\bcartifacts.cache\onprem\9.0.50357.0\na\TestToolKit
Copying UpgradeToolKit
C:\bcartifacts.cache\onprem\9.0.50357.0\na\UpgradeToolKit
c:\bcartifacts.cache\xaq51vcd.ap0
[2022-11-10T22:39:27.280843300Z][docker-credential-desktop][W] Windows version might not be up-to-date: The system cannot find the file specified.
Sending build context to Docker daemon    974MB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.3532
 ---> ed2b98b73e0e
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/9.0.50357.0/na filesOnly=False
 ---> Running in cb4356860f91
Removing intermediate container cb4356860f91
 ---> 1d170356e348
Step 3/6 : COPY my /run/
 ---> cfbc70c98edf
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 7be3bc0c274c
Step 5/6 : RUN \Run\start.ps1 -installOnly
 ---> Running in c51ab102daed
hcsshim::CreateComputeSystem c51ab102daed9d7011216b07d8655a6e3b73445a88cffe4da007d64f67d5c1ac: The virtual machine could not be started because a required feature is not installed.
New-Bcimage Telemetry Correlation Id: 8bd7a8e9-3c0a-436d-ba5f-34cd9ee5116a
New-NavContainer Telemetry Correlation Id: c3a5fb67-099e-456c-83df-808a4feaae01
System.Management.Automation.RuntimeException Docker Build failed with exit code 1
New-Bcimage Telemetry Correlation Id: 8bd7a8e9-3c0a-436d-ba5f-34cd9ee5116a
New-NavContainer Telemetry Correlation Id: c3a5fb67-099e-456c-83df-808a4feaae01
System.Management.Automation.RuntimeException Docker Build failed with exit code 1


**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
- This is a new VM and it has happened all the time - trying to get docker/bccontainerhelper running for the first time

Tried to run get-bccontainereventlog - got this
PS C:\AdvaniaGIT\Workspace\Git\NAV2016_CCB> get-bccontainereventlog
BcContainerHelper version 4.0.6
BcContainerHelper emits usage statistics telemetry to Microsoft
Getting event log for bcserver
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/bcserver/json": open //./pipe/docker_engine: The system cannot find the file specified.
get-bccontainereventlog Telemetry Correlation Id: b2e2e155-9b4c-40ec-98e1-2f62de0371d4
The property 'HostConfig' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.6\ContainerInfo\Get-NavContainerSharedFolders.ps1:27 char:9
+     if ($inspect.HostConfig.Binds) {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFoundStrict


When running docker desktop (I installed it after Docker EE), I receive this error:

System.InvalidOperationException:
job failed with message: 'DockerDesktopVM' failed to start. (Virtual machine ID 39D8E1C9-CC6F-4B92-A264-3E2DBD29942D)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 39D8E1C9-CC6F-4B92-A264-3E2DBD29942D).
   at Docker.Backend.HyperVInfrastructure.HandleUpdatedJob(CIMConcreteJob updatedJob) in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 780
   at Docker.Backend.HyperVInfrastructure.<HandleMaybeAsyncJob>d__40.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 714
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HyperVInfrastructure.<StartVMAsync>d__32.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 554
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HyperV.<StartAsync>d__6.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperV.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpAPI.HyperVController.<StartAsync>d__7.MoveNext() in C:\workspaces\PR-19568\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\HyperVController.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

Any help or references would be appreciated.

**Comment by freddydk** [comment]
This is because Docker on Server 2019 defaults to HyperV isolation if a generic docker image, which matches the host OS is not available - and this machine doesn't have HyperV installed (even though it says that it is enabled????).
If you specify -isolation process you force process isolation - and it should work.

Reason was that the workflow for generating docker images when a new windows version was shipped had stopped running.
Kicked one off today - and this should work a little later.
Run: https://github.com/microsoft/nav-docker/actions/runs/3449623826

**Comment by rsaritzky** [comment]
Thank you for the help.  Setting it to -isolation process did the trick.

Ron
