### ISSUE TITLE
BCInsider container is not working with AAD Auth

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/navcontainerhelper#2876]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Related to this issue (https://github.com/microsoft/navcontainerhelper/issues/2874#issuecomment-1406437009) but slightly different.
The container is correctly created but we are unable to log on with this error message in the browser:
```
You cannot sign in due to a technical issue. Contact your system administrator.
```

The script is able to create a container (without multitenancy) for BC21 but not for BC22.

**Scripts used to create container and cause the issue**
```

$securePassword = ConvertTo-SecureString -String $adminPassword -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "admin", $securePassword
$additionalParameters = @("--publish ${publicHttpAltPort}:8080",
                          "--publish ${publicHttpPort}:80",
                          "--publish ${publicHttpsPort}:443",
                          "--publish ${publicServicePorts}:7046-7049",
                          "--restart always")

New-BCContainer `
    -accept_eula `
    -alwaysPull `
    -isolation hyperv `
    -containerName $ContainerName `
    -useSSL `
    -myscripts @('https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/210-new/SetupConfiguration.ps1', $setupCertificateScript, $domainCertificate) `
    -auth AAD `
    -AadTenant "48***aa" `
    -AadAppId "10***fe" `
    -AadAppIdUri "api://10***fe" `
    -AuthenticationEMail "***" `
    -credential $credential `
    -additionalParameters $additionalParameters `
    -licensefile "$licenseFile" `
    -useBestContainerOS `
    -memoryLimit $memoryLimit `
    -PublicDnsName $publicDnsName `
    -dns '8.8.8.8' `
    -updatehosts `
    -multitenant:$false `
    -artifactUrl $artifactUrl
```

**Full output of scripts**
```
BcContainerHelper version 4.0.10
BC.HelperFunctions emits usage statistics telemetry to Microsoft
##[debug]Looking for bcinsider sandbox  fr Latest    
##[debug]Artifact found: https://bcinsider.azureedge.net/sandbox/22.0.52293.0/fr***
BcContainerHelper is version 4.0.10
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Enterprise - 22H2
Docker Client Version is 20.10.21
Docker Server Version is 20.10.21
Removing Session bc-master
Removing container bc-master
Removing entries from hosts
Removing bc-master from container hosts file
Removing bc-master-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\bc-master
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.20348.1487
10.0.20348.1487: Pulling from businesscentral
Digest: sha256:a587834184d1f1e2855a52db7a20fba720de08e958559fd62e1702daa3d9be59
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.1487
mcr.microsoft.com/businesscentral:10.0.20348.1487
Using image mcr.microsoft.com/businesscentral:10.0.20348.1487
PublicDnsName is ***
Creating Container bc-master
Style: sandbox
Multitenant: No
Version: 22.0.52293.0
Platform: 22.0.52192.0
Generic Tag: 1.0.2.13
Container OS Version: 10.0.20348.1487 (ltsc2022)
Host OS Version: 10.0.22621.819 (22H2)
Using hyperv isolation
Using locale fr-FR
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\BcContainerHelper\Extensions\bc-master\my\SetupConfiguration.ps1
Using WebClient
Downloading C:\ProgramData\BcContainerHelper\Extensions\bc-master\my\SetupCertificate.ps1
Using WebClient
Downloading C:\ProgramData\BcContainerHelper\Extensions\bc-master\my\capvision-cloud.fr.pfx
Using WebClient
Using license file https://cvcapvignesdevstorage.blob.core.windows.net/dev/5164876.bclicense
Downloading C:\ProgramData\BcContainerHelper\Extensions\bc-master\my\license.bclicense
Using WebClient
Additional Parameters:
--publish 7188:8080
--publish 7180:80
--publish 7143:443
--publish 7146-7149:7046-7049
--restart always
--env customNavSettings=ValidAudiences=10***fe;https://api.businesscentral.dynamics.com,DisableTokenSigningCertificateValidation=True,ExtendedSecurityTokenLifetime=24,ClientServicesCredentialType=NavUserPassword
--env customWebSettings=AadApplicationId=10***fe,AadAuthorityUri=https://login.microsoftonline.com/***
Files in C:\ProgramData\BcContainerHelper\Extensions\bc-master\my:
- AdditionalOutput.ps1
- capvision-cloud.fr.pfx
- license.bclicense
- MainLoop.ps1
- SetupCertificate.ps1
- SetupConfiguration.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc-master from image mcr.microsoft.com/businesscentral:10.0.20348.1487
35da3e27fa673456609d736fbda48e7dfe3ac13afffa76aa204a46bbf81192ef
Waiting for container bc-master to be ready
Using artifactUrl https://bcinsider.azureedge.net/sandbox/22.0.52293.0/fr
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\22.0.52293.0\platform\ServiceTier\Program Files
c:\dl\sandbox\22.0.52293.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\22.0.52293.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\22.0.52293.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\22.0.52293.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\22.0.52293.0\platform
c:\dl\sandbox\22.0.52293.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\22.0.52293.0\fr\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\22.0.52293.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\22.0.52293.0\fr\Extensions
Copying Applications
C:\dl\sandbox\22.0.52293.0\platform\Applications
Copying Applications.FR
C:\dl\sandbox\22.0.52293.0\fr\Applications.FR
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 134 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.20.48.1 in container hosts file
Starting Container
Hostname is bc-master
PublicDnsName is ***
Using AccessControlService Authentication
Certificate File Thumbprint ***
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting ValidAudiences to 10***fe;https://api.businesscentral.dynamics.com
Setting DisableTokenSigningCertificateValidation to True
Setting ExtendedSecurityTokenLifetime to 24
Setting ClientServicesCredentialType to NavUserPassword
Starting Service Tier
CertificateThumprint ***
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer with SSL
Update configuration: navsettings.json
Done Configuring Web Client
Modifying Web Client config with settings from environment variable
Setting AadApplicationId to 10***fe
Setting AadAuthorityUri to https://login.microsoftonline.com/***
Enabling Financials User Experience
Using license file 'c:\run\my\license.bclicense'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.20.56.135
Container Hostname  : bc-master
Container Dns Name  : ***
Web Client          : https://***/BC/
Dev. Server         : https://***
Dev. ServerInstance : BC
Setting bc-master to 172.20.56.135 in host hosts file

Files:
http://***:8080/ALLanguage.vsix

Container Total Physical Memory is 8.5Gb
Container Free Physical Memory is 5.9Gb

Initialization took 47 seconds
Ready for connections!
Reading CustomSettings.config from bc-master
Creating Desktop Shortcuts for bc-master
Container bc-master successfully created

Use:
Get-BcContainerEventLog -containerName bc-master to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName bc-master to get debug information about the container
Enter-BcContainer -containerName bc-master to open a PowerShell prompt inside the container
Remove-BcContainer -containerName bc-master to remove the container again
docker logs bc-master to retrieve information about URL's again

Welcome to the Server Admin Tool Shell!
For a complete list of Server cmdlets type
```

**Additional context**
It happens with AAD auth with BC22 artifacts.
It works well with artifacts like https://bcinsider.azureedge.net/sandbox/21.4.52586.0/fr (BC21)

In the event log of the container there is a succession of issues:

**1. NST warning**

```
Server instance: BC
Category: Api
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 8093066e-76e0-429a-9a55-cd540d0bd001
ServerActivityId: 8851f272-5a73-421c-87c5-d409c4d8eca1
EventTime: 01/27/2023 13:11:36
Message The HTTP header ClientActivityId is not set or has an invalid GUID. Cancellation cannot be registered.
ProcessId: 3528
Tag: 0000J34
ThreadId: 17
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 
```

**2. NST error**

```
Server instance: BC
Category: Security
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: dd89bd4f-a916-4841-8fd6-a73f3ea778f6
EventTime: 01/27/2023 13:11:36
Message (NavConfigurationException): RootException: NavConfigurationException
Message not shown because the NavBaseException constructor was used without privacy classification
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.LoadFederationMetadata(Boolean forceRefresh)
   at Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.get_SigningCertificates()
   at Microsoft.Dynamics.Nav.Runtime.FederationMetadataProvider.GetValidSigningCertificateWithThumbprint(String tokenCertificateThumbprint, Boolean retry)
   at Microsoft.Dynamics.Nav.Runtime.NavJwtSecurityTokenFactory.<>c__DisplayClass3_0.<CreateUserTokenValidationParameters>b__1(String token, SecurityToken securityToken, String kid, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignatureAndIssuerSecurityKey(String token, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateJWS(String token, TokenValidationParameters validationParameters, BaseConfiguration currentConfiguration, SecurityToken& signatureValidatedToken, ExceptionDispatchInfo& exceptionThrown)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, JwtSecurityToken outerToken, TokenValidationParameters validationParameters, SecurityToken& signatureValidatedToken)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.Dynamics.Nav.Runtime.NavJwtSecurityTokenFactory.CreateAndValidateWithAudienceList(NavTenant tenant, String authorizationHeader, FederationMetadataProvider federationMetadataProvider, IEnumerable`1 allowedAudiences, String tokenId, NavDiagnostics diagnostics)
   at Microsoft.Dynamics.Nav.Service.WSFederationValidator.Validate(NavTenant tenant, String userName, String password, String navAppId, Boolean forceLongerCacheItemLifetime)
   at Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.ValidateCredentials(String userName, String password, NavTenant tenant, String navAppId, Boolean forceLongerCacheItemLifetime)
   at Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.Validate(String userName, String password)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.Validate(String userName, String password)
   at Microsoft.Dynamics.Nav.Service.NSServiceBase.<>c__DisplayClass16_0.<ValidateAndCreateSession>b__0()
   at Microsoft.Dynamics.Nav.Service.NSServiceBase.ValidateAndCreateSession(ConnectionRequest connectionRequest, Boolean requireNavUser, String userName, WindowsIdentity windowsIdentity)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.CreateNewSessionCombinator(ServiceOperationContext context, ServiceOperation innerOperation, Boolean requireNavUser, Boolean useCoreWcfFaultException)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.<>c__DisplayClass1_0.<Create>b__4(ServiceOperationContext context, ServiceOperation operation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.<>c__DisplayClass7_0.<PerformanceCounterCombinator>b__0()
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PerformanceCounterCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.InitClientTelemetryIdsCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TlsClearCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineDispatchProxy`1.Invoke(MethodInfo targetMethod, Object[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.OpenConnection(ConnectionRequest , CancellationToken )
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at StreamJsonRpc.TargetMethod.<InvokeAsync>d__19.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


ProcessId: 3528
Tag: 0000237
ThreadId: 38
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 
```

**3. NST Warning**

```
Server instance: BC
Category: Runtime
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: dd89bd4f-a916-4841-8fd6-a73f3ea778f6
EventTime: 01/27/2023 13:11:36
Message (NavAuthenticationException): Sending exception to client. Session terminating: False
RootException: NavAuthenticationException
Message not shown because the NavBaseException constructor was used without privacy classification
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.Validate(String userName, String password)
   at Microsoft.Dynamics.Nav.Service.NSServiceBase.<>c__DisplayClass16_0.<ValidateAndCreateSession>b__0()
   at Microsoft.Dynamics.Nav.Service.NSServiceBase.ValidateAndCreateSession(ConnectionRequest connectionRequest, Boolean requireNavUser, String userName, WindowsIdentity windowsIdentity)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.CreateNewSessionCombinator(ServiceOperationContext context, ServiceOperation innerOperation, Boolean requireNavUser, Boolean useCoreWcfFaultException)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.CreateNewSessionCombinator(ServiceOperationContext context, ServiceOperation innerOperation, Boolean requireNavUser, Boolean useCoreWcfFaultException)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.<>c__DisplayClass1_0.<Create>b__4(ServiceOperationContext context, ServiceOperation operation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.<>c__DisplayClass7_0.<PerformanceCounterCombinator>b__0()
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.PerformanceCounterCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.InitClientTelemetryIdsCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TlsClearCombinator(ServiceOperationContext context, ServiceOperation innerOperation)
   at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineDispatchProxy`1.Invoke(MethodInfo targetMethod, Object[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.OpenConnection(ConnectionRequest , CancellationToken )
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at StreamJsonRpc.TargetMethod.<InvokeAsync>d__19.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


ProcessId: 3528
Tag: 00000HC
ThreadId: 38
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 
```

**4. Web Server Error**

```
Category: Microsoft.Dynamics.Nav.Client.Web.UserValidator
EventId: 0
ConnectionId: 0HMO0CNPI2J6L
RequestId: 0HMO0CNPI2J6L:00000029
RequestPath: /BC/SignIn
MemberName: ResolveException
FilePath: s:\repo\src\Platform\Client\Web\Prod.Client.WebCommon\Security\UserValidator.cs
LineNumber: 77

 

Exception: 
Microsoft.Dynamics.Nav.Types.Exceptions.NavAuthenticationException: You cannot sign in due to a technical issue. Contact your system administrator.
 ---> Microsoft.Dynamics.Nav.Types.Exceptions.NavAuthenticationException: You cannot sign in due to a technical issue. Contact your system administrator.
   at Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.Validate(String userName, String password)
   at Microsoft.Dynamics.Nav.Service.NSServiceBase.<>c__DisplayClass16_0.<ValidateAndCreateSession>b__0()
   at Microsoft.Dynamics.Nav.Service.NSServiceBase.ValidateAndCreateSession(ConnectionRequest connectionRequest, Boolean requireNavUser, String userName, WindowsIdentity windowsIdentity)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.CreateNewSessionCombinator(ServiceOperationContext context, ServiceOperation innerOperation, Boolean requireNavUser, Boolean useCoreWcfFaultException)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.CallOpenConnection(IClientApi api, ConnectionRequest connectionRequest) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 303
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection(ConnectionRequest connectionRequest, ConnectionOptions connectionOptions) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 130
   at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\Platform\Client\Web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 226
   at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\Platform\Client\Web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 239
```

** 5. Web server Error**

```
Error accessing Website BC
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavAuthenticationException
ErrorCode: -1
ShouldCalculateALCallStack: True
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: True
DiagnosticsSuppress: True
DiagnosticsMessage: Message not shown because the NavBaseException constructor was used without privacy classification
MessageWithoutPrivateInformation: Message not shown because the NavBaseException constructor was used without privacy classification
SuppressExceptionCreatedEvent: False
FatalityScope: None
ErrorLevel: Error
Message: You cannot sign in due to a technical issue. Contact your system administrator.
Source: Microsoft.Dynamics.Nav.Client.ServiceConnection
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.CallOpenConnection(IClientApi api, ConnectionRequest connectionRequest) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 303
     at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection(ConnectionRequest connectionRequest, ConnectionOptions connectionOptions) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 130
     at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\Platform\Client\Web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 226
     at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\Platform\Client\Web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 239
StackTrace:
     at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.CallOpenConnection(IClientApi api, ConnectionRequest connectionRequest) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 303
     at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection(ConnectionRequest connectionRequest, ConnectionOptions connectionOptions) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 130
     at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\Platform\Client\Web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 226
     at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\Platform\Client\Web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 239
----------------------------------
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavAuthenticationException
ErrorCode: -1
ShouldCalculateALCallStack: True
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: True
DiagnosticsSuppress: True
DiagnosticsMessage: Message not shown because the NavBaseException constructor was used without privacy classification
MessageWithoutPrivateInformation: Message not shown because the NavBaseException constructor was used without privacy classification
SuppressExceptionCreatedEvent: False
FatalityScope: None
ErrorLevel: Error
Message: You cannot sign in due to a technical issue. Contact your system administrator.
Source: Microsoft.Dynamics.Nav.Service
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.Validate(String userName, String password)
     at Microsoft.Dynamics.Nav.Service.NSServiceBase.<>c__DisplayClass16_0.<ValidateAndCreateSession>b__0()
     at Microsoft.Dynamics.Nav.Service.NSServiceBase.ValidateAndCreateSession(ConnectionRequest connectionRequest, Boolean requireNavUser, String userName, WindowsIdentity windowsIdentity)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.CreateNewSessionCombinator(ServiceOperationContext context, ServiceOperation innerOperation, Boolean requireNavUser, Boolean useCoreWcfFaultException)
StackTrace:
     at Microsoft.Dynamics.Nav.Service.ClientServicesUserNamePasswordValidator.Validate(String userName, String password)
     at Microsoft.Dynamics.Nav.Service.NSServiceBase.<>c__DisplayClass16_0.<ValidateAndCreateSession>b__0()
     at Microsoft.Dynamics.Nav.Service.NSServiceBase.ValidateAndCreateSession(ConnectionRequest connectionRequest, Boolean requireNavUser, String userName, WindowsIdentity windowsIdentity)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.CreateNewSessionCombinator(ServiceOperationContext context, ServiceOperation innerOperation, Boolean requireNavUser, Boolean useCoreWcfFaultException)
```

**Comment by freddydk** [comment]
I have contacted the team responsible to see what changed and/or where the bug is?

Thanks

**Comment by freddydk** [comment]
The problem is that the setting ADOpenIdMetadataLocation should be set to 
`https://login.microsoftonline.com/common/.well-known/openid-configuration`
This will be default in a later version of the insider build.

Until then - you can use

```
-myScripts @('https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/210-new/SetupConfiguration.ps1')
```
I have patched this to set the right setting if not already set.

**Comment by nicolassaleron** [comment]
Thank you, the session starts now
