### ISSUE TITLE
Azure DevOps pipelines randomly are getting stuck

### ISSUE THREAD

**Issue by pwx24** [microsoft/navcontainerhelper#3074]
**Describe the issue**
Hi, we have a problem with Azure DevOps pipelines - sometimes they are getting stuck without any error or notification. We use BCContainerHelper to create container and build our BC app. We noticed that mostly it happens on app installation or compilation task and they are completed (as log shows) but agent doesn't start next task.

Problem occurs on:
-different agent pools (microsoft-hosted, self-hosted, vmss)
-different Azure DevOps projects (different repos, code) - only CI/CD scripts stay the same
-different versions of BC containers

**Scripts used to create container and cause the issue**
```
#Example of our app installation script:

[CmdletBinding()]
param (
  [Parameter(Mandatory = $true)]
  [string]$Path,
  [Parameter(Mandatory = $false)]
  [string]$ContainerName = $env:CONTAINERNAME
)

. (Join-Path $PSScriptRoot\helpers 'telemetry.ps1')
$TelemetryClient = New-TelemetryClient

try {
  $TelemetryClient.TrackPageView('Install-Dependencies')
  $TelemetryClient.Flush()

  $dependenciesJson = Test-Path -Path (Join-Path "$Path\*" dependencies.json)

  if ($dependenciesJson) {
    & "$PSScriptRoot\Install-ApplicationsLocally.ps1" -appsPath "$Path\*" -containerName $ContainerName
  }
  else {
    $apps = Get-ChildItem -Path $Path -Recurse -Filter "*.app" |
    Where-Object { $_.Fullname -notmatch 'symbols' -and $_.Fullname -notmatch 'runtime_packages' -and $_ -notmatch "Test" }
    $apps = [string[]]$apps.FullName
    $sortedApps = Sort-AppFilesByDependencies -appFiles $apps -containerName $ContainerName
    foreach ($app in $sortedApps) {
      Publish-BcContainerApp -appFile $app -containerName $ContainerName -sync -install -skipVerification
    }
  }
}
catch {
  Write-Host $_.Exception.Message -ForegroundColor Red
  $TelemetryClient.TrackException($_.Exception)
  $TelemetryClient.Flush()
  throw $_.Exception
}
```

**Full output of scripts**
```
2023-05-25T06:30:49.4729002Z ##[debug]Evaluating condition for step: 'Install Application-AVK'
2023-05-25T06:30:49.4730467Z ##[debug]Evaluating: SucceededNode()
2023-05-25T06:30:49.4731038Z ##[debug]Evaluating SucceededNode:
2023-05-25T06:30:49.4731520Z ##[debug]=> True
2023-05-25T06:30:49.4732072Z ##[debug]Result: True
2023-05-25T06:30:49.4732413Z ##[section]Starting: Install Application-AVK
2023-05-25T06:30:49.5142518Z ==============================================================================
2023-05-25T06:30:49.5142844Z Task         : PowerShell
2023-05-25T06:30:49.5142920Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2023-05-25T06:30:49.5143043Z Version      : 2.220.0
2023-05-25T06:30:49.5143127Z Author       : Microsoft Corporation
2023-05-25T06:30:49.5143211Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2023-05-25T06:30:49.5143344Z ==============================================================================
2023-05-25T06:30:50.7265598Z ##[debug]VstsTaskSdk 0.11.0 commit 7ff27a3e0bdd6f7b06690ae5f5b63cb84d0f23f4
2023-05-25T06:30:52.0465903Z ##[debug]Entering C:\azp-agent_2\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.220.0\powershell.ps1.
2023-05-25T06:30:52.0580525Z ##[debug]Loading resource strings from: C:\azp-agent_2\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.220.0\task.json
2023-05-25T06:30:52.1011882Z ##[debug]Loaded 13 strings.
2023-05-25T06:30:52.1074372Z ##[debug]SYSTEM_CULTURE: 'en-US'
2023-05-25T06:30:52.1138261Z ##[debug]Loading resource strings from: C:\azp-agent_2\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.220.0\Strings\resources.resjson\en-US\resources.resjson
2023-05-25T06:30:52.1555862Z ##[debug]Loaded 13 strings.
2023-05-25T06:30:52.1900030Z ##[debug]INPUT_ERRORACTIONPREFERENCE: 'stop'
2023-05-25T06:30:52.1984021Z ##[debug]INPUT_WARNINGPREFERENCE: 'default'
2023-05-25T06:30:52.2022426Z ##[debug]INPUT_INFORMATIONPREFERENCE: 'default'
2023-05-25T06:30:52.2060592Z ##[debug]INPUT_VERBOSEPREFERENCE: 'default'
2023-05-25T06:30:52.2096271Z ##[debug]INPUT_DEBUGPREFERENCE: 'default'
2023-05-25T06:30:52.2133360Z ##[debug]INPUT_PROGRESSPREFERENCE: 'silentlyContinue'
2023-05-25T06:30:52.2166205Z ##[debug]INPUT_SHOWWARNINGS: 'false'
2023-05-25T06:30:52.2206915Z ##[debug] Converted to bool: False
2023-05-25T06:30:52.2251745Z ##[debug]INPUT_FAILONSTDERR: 'false'
2023-05-25T06:30:52.2289213Z ##[debug] Converted to bool: False
2023-05-25T06:30:52.2331171Z ##[debug]INPUT_IGNORELASTEXITCODE: 'false'
2023-05-25T06:30:52.2362755Z ##[debug] Converted to bool: False
2023-05-25T06:30:52.2400224Z ##[debug]INPUT_PWSH: 'false'
2023-05-25T06:30:52.2427408Z ##[debug] Converted to bool: False
2023-05-25T06:30:52.2465110Z ##[debug]INPUT_WORKINGDIRECTORY: 'C:\azp-agent_2\_work\1389\s'
2023-05-25T06:30:52.2635724Z ##[debug]Asserting container path exists: 'C:\azp-agent_2\_work\1389\s'
2023-05-25T06:30:52.2675542Z ##[debug]INPUT_TARGETTYPE: 'filePath'
2023-05-25T06:30:52.2731966Z ##[debug]INPUT_FILEPATH: 'C:\azp-agent_2\_work\1389\s\ALScripts\src\Install-Dependencies.ps1'
2023-05-25T06:30:52.2764302Z ##[debug]Asserting leaf path exists: 'C:\azp-agent_2\_work\1389\s\ALScripts\src\Install-Dependencies.ps1'
2023-05-25T06:30:52.2822917Z ##[debug]INPUT_ARGUMENTS: '-Path C:\azp-agent_2\_work\1389\Application-AVK'
2023-05-25T06:30:52.2859885Z ##[debug]INPUT_RUNSCRIPTINSEPARATESCOPE: 'false'
2023-05-25T06:30:52.2884590Z ##[debug] Converted to bool: False
2023-05-25T06:30:52.2940881Z Generating script.
2023-05-25T06:30:52.3026607Z Formatted command: . 'C:\azp-agent_2\_work\1389\s\ALScripts\src\Install-Dependencies.ps1' -Path C:\azp-agent_2\_work\1389\Application-AVK
2023-05-25T06:30:52.3227645Z ##[debug]AGENT_VERSION: '3.218.0'
2023-05-25T06:30:52.3333871Z ##[debug]AGENT_TEMPDIRECTORY: 'C:\azp-agent_2\_work\_temp'
2023-05-25T06:30:52.3371542Z ##[debug]Asserting container path exists: 'C:\azp-agent_2\_work\_temp'
2023-05-25T06:30:52.3959263Z ##[debug]Asserting leaf path exists: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
2023-05-25T06:30:52.3982060Z ========================== Starting Command Output ===========================
2023-05-25T06:30:52.4233464Z ##[debug]Entering Invoke-VstsTool.
2023-05-25T06:30:52.4463489Z ##[debug] Arguments: '-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\azp-agent_2\_work\_temp\5787d381-220f-49f1-9372-262f94207019.ps1'"'
2023-05-25T06:30:52.4497786Z ##[debug] FileName: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
2023-05-25T06:30:52.4527373Z ##[debug] WorkingDirectory: 'C:\azp-agent_2\_work\1389\s'
2023-05-25T06:30:52.4620756Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\azp-agent_2\_work\_temp\5787d381-220f-49f1-9372-262f94207019.ps1'"
2023-05-25T06:30:53.6930856Z @{OrderNumber=1; AppName=Int. Feature Management; AppFileName=Int. Feature Management_1.0.0.2.app; AppRuntimeFileName=Int. Feature Management_1.0.0.2_runtime.app; AppVersion=1.0.0.2; Publisher=IT.integro sp. z o.o.}
2023-05-25T06:30:53.9579238Z BcContainerHelper version 5.0.3
2023-05-25T06:30:54.2557037Z BC.HelperFunctions emits usage statistics telemetry to Microsoft
2023-05-25T06:31:04.3600470Z BcContainerHelper version 5.0.3
2023-05-25T06:31:04.7994031Z BC.HelperFunctions emits usage statistics telemetry to Microsoft
2023-05-25T06:31:12.4426322Z Publishing C:\ProgramData\BcContainerHelper\Extensions\current-138344\39511248-6c9b-4b96-ae6c-9d7565583802\Int. Feature Management_1.0.0.2.app
2023-05-25T06:31:22.8359376Z Synchronizing Int. Feature Management on tenant default
2023-05-25T06:31:32.1455177Z Installing Int. Feature Management on tenant default
2023-05-25T06:31:32.6957973Z y
2023-05-25T06:33:38.4585309Z App Int. Feature Management_1.0.0.2.app successfully published
2023-05-25T06:51:14.2422741Z ##[debug]Re-evaluate condition on job cancellation for step: 'Install Application-AVK'.
2023-05-25T06:51:14.5730381Z ##[debug]Leaving Invoke-VstsTool.
2023-05-25T06:51:14.5764434Z ##[debug]Leaving C:\azp-agent_2\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\2.220.0\powershell.ps1.
2023-05-25T06:51:14.8988685Z ##[error]The operation was canceled.
2023-05-25T06:51:14.9015941Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, Boolean continueAfterCancelProcessTreeKillAttempt, CancellationToken cancellationToken) in D:\a\1\s\src\Agent.Sdk\ProcessInvoker.cs:line 376
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, Boolean continueAfterCancelProcessTreeKillAttempt, CancellationToken cancellationToken) in D:\a\1\s\src\Microsoft.VisualStudio.Services.Agent\ProcessInvoker.cs:line 308
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, Boolean continueAfterCancelProcessTreeKillAttempt, CancellationToken cancellationToken) in D:\a\1\s\src\Agent.Worker\Handlers\StepHost.cs:line 76
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync() in D:\a\1\s\src\Agent.Worker\Handlers\PowerShell3Handler.cs:line 72
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync() in D:\a\1\s\src\Agent.Worker\TaskRunner.cs:line 407
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken) in D:\a\1\s\src\Agent.Worker\StepsRunner.cs:line 224
2023-05-25T06:51:14.9019167Z ##[section]Finishing: Install Application-AVK
```

**Screenshots**
Please look at the time. Task was done but agent waited till timeout.
![image](https://github.com/microsoft/navcontainerhelper/assets/32017031/96e3be8d-21ec-4cdf-864e-1da7b51f0127)

**Additional context**
Additionally:
-we use newest BCContainerHelper on every pipeline run
-UsePsSession=false parameter doesn't resolve problem
-problem occurs at least few months and we can't reproduce it "on demand"

We kindly ask for any advice what could we do/check to solve this problem. If you need any more information - please let me know.

**Comment by freddydk** [comment]
I spend a few days some time ago investigating pipelines and found that in these cases, it was the session in the container, which caused the pipeline to get stuck. I came up with two solutions described here:

https://github.com/microsoft/navcontainerhelper/issues/2617

When you say -usePsSession false parameter, what do you mean?
usePsSession is a setting, which you can set in the settings file (or set right after loading containerhelper):

$bcContainerHelperConfig.usePsSession = $false

the other setting was:

$bcContainerHelperConfig.killPsSessionProcess = $true

If you re-load containerhelper in another step after this - the settings are gone.
The dump from the container generation will display information about whether it is using sessions or docker exec to invoke scripts inside the container.

**Comment by pwx24** [comment]
Sorry for the late reply - I was doing some tests. You gave important clue about $bcContainerHelperConfig. I have added separately "$bcContainerHelperConfig.usePsSession = $false" setting at the beginning of every PowerShell script which executes commands inside the container and now I can say - it works.

Thanks a lot for help!
