### ISSUE TITLE
404 NOT FOUND when calling OData V4 web service binding to page ID. 50 (Purchase Order) in SE company.

### ISSUE THREAD

**Issue by yuhongxiangtheorigin** [microsoft/navcontainerhelper#3137]
**Describe the issue**
We encountered 404 NOT FOUND when calling the OData V4 web service binding to page ID. 50 (Purchase Order) in SE company.

**Scripts used to create container and cause the issue**
```
$artifactUrl = "https://bcinsider.azureedge.net/sandbox/22.4.59056.0/se"
$credential = New-Object System.Management.Automation.PSCredential -argumentList "QA.TEST", (ConvertTo-SecureString -String "Password1" -AsPlainText -Force)
$accept_eula = $true
$containername = 'BC22SE'
$bcContainerHelperConfig.sandboxContainersAreMultitenantByDefault = $false

New-BcContainer -accept_eula: $accept_eula `
                -containerName: $containername `
                -auth NavUserPassword `
                -Credential $credential `
                -alwaysPull `
                -doNotExportObjectsToText `
                -useSSL:$false `
                -updateHosts `
                -assignPremiumPlan `
                -shortcuts Desktop `
                -artifactUrl $artifactUrl `
                -licenseFile "XXX.bclicense" `
                -includeTestToolkit:$false `
                -isolation hyperv `
                -memoryLimit 3G
```

**web service definition**
```
<TenantWebService>
	<ObjectType>Page</ObjectType>
	<ServiceName>PurchaseOrder</ServiceName>
	<ObjectID>50</ObjectID>
	<Published>true</Published>
</TenantWebService>
```

**web service calling**
```
http://bc22se:7048/BC/ODataV4/Company('CRONUS%20SE')/PurchaseOrder

```

**container event log**
```
Server instance: BC
Category: OData
ClientSessionId: 7d25c6e2-0970-48c6-9b28-0e7c67b06fd5
ClientActivityId: 13475bc1-b1ee-442f-85f2-8f74abebef90
ServerSessionUniqueId: 019c4232-ab7e-423d-af22-259d47ab3e77
ServerActivityId: 9d8f7ad0-d2bb-495b-8237-b4e0f37df8a3
EventTime: 07/28/2023 03:49:55
Message (NavODataArgumentException): Entity could not be added to the model -- PurchaseOrder
RootException: NavODataArgumentException
A property definition already exists for PurchaseOrder.EU_3_Party_Trade.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavEdmStructuralTypeMetadata`1.AddPrimitiveProperty(String name, IMetadata metadata)
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavEdmPropertyEntityTypeVisitor.Visit(INavEdmEntityTypeMetadata`1 edmMetadata, INavEdmModel model, ODataMetadataContext metadataContext)
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavEdmEntityTypeMetadataVisitor.<get_Visitors>b__5_0(INavEdmEntityTypeMetadata edmMetadata, INavEdmModel model, ODataMetadataContext metadataContext)
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavEdmEntityTypeMetadataVisitor.Visit(INavEdmEntityTypeMetadata edmMetadata, INavEdmModel model, ODataMetadataContext metadataContext)
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavEdmMetadataVisitor`1.Microsoft.Dynamics.Nav.Service.OData.Modeling.INavEdmMetadataVisitor.Visit(INavEdmMetadata edmMetadata, INavEdmModel model, ODataMetadataContext metadataContext)
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavEdmModelVisitor.TryVisitEntities(INavEdmModel model, INavEdmMetadataVisitor visitor, NavEdmModelBuildResult result, ODataMetadataContext metadataContext)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavEdmModelVisitor.TryVisitEntities(INavEdmModel model, INavEdmMetadataVisitor visitor, NavEdmModelBuildResult result, ODataMetadataContext metadataContext)
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavEdmModelVisitor.TryVisit(INavEdmModel model, NavEdmModelBuildResult result, ODataMetadataContext metadataContext)
   at Microsoft.Dynamics.Nav.Service.OData.V4.NavODataV4V1CachedModelBuilder.Build(IEnumerable`1 complexTypes, IEnumerable`1 services)
   at Microsoft.Dynamics.Nav.Service.OData.V4.NavODataV4V1CachedModelBuilder.Build(NavSession navSession, String key, IServiceProvider serviceProvider)
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavODataCachedModelBuilder`2.<>c__DisplayClass8_0.<Build>b__0(NavSession navSession)
   at Microsoft.Dynamics.Nav.Service.OData.NavServiceBase.Execute[TResult](HttpRequest request, NavSession session, Func`2 operation, OpenCompanyDetails openCompanyDetails)
   at Microsoft.Dynamics.Nav.Service.OData.NavServiceBase.Execute[TResult](Func`2 operation)
   at Microsoft.Dynamics.Nav.Service.OData.Modeling.NavODataCachedModelBuilder`2.Build(IServiceProvider serviceProvider)
   at Microsoft.Dynamics.Nav.Service.OData.V4.NavODataV4V1RouteBuilder.GetEdmModel(IServiceProvider serviceProvider)
   at Microsoft.Dynamics.Nav.Service.OData.V4.NavODataV4RouteBuilder.GetEdmModelWithLogging(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer, Boolean template)
   at Microsoft.AspNet.OData.Routing.DefaultODataPathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)
   at Microsoft.Dynamics.Nav.Service.OData.V4.NavODataV4PathHandler.Parse(String serviceRoot, String odataPath, IServiceProvider requestContainer)
   at Microsoft.Dynamics.Nav.Service.OData.V4.NavODataV4RouteConstraint.GetODataPath(String oDataPathString, String uriPathString, String queryString, HttpRequest request, String routeName, Func`1 requestContainerFactory, String& serviceRoot)
   at Microsoft.Dynamics.Nav.Service.OData.V4.NavODataV4RouteConstraint.Match(HttpContext httpContext, IRouter route, String routeKey, RouteValueDictionary values, RouteDirection routeDirection)
   at Microsoft.AspNetCore.Routing.RouteConstraintMatcher.Match(IDictionary`2 constraints, RouteValueDictionary routeValues, HttpContext httpContext, IRouter route, RouteDirection routeDirection, ILogger logger)
   at Microsoft.AspNetCore.Routing.RouteBase.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataExceptionHandlingMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataExceptionHandlingMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataExceptionHandlingMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataExceptionHandlingMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestAuthenticationMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestAuthenticationMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataCorsMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataCorsMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.AspNetCore.Middlewares.AuthorizationHeaderInspector.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.AspNetCore.Middlewares.AuthorizationHeaderInspector.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataMaxNodeConnectionsMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataMaxNodeConnectionsMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataTenantRequestThrottlingMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataTenantRequestThrottlingMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestStatisticsMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestStatisticsMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataOptionsPreflightMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataOptionsPreflightMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestCompressionMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestCompressionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestUrlMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestUrlMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.AspNetCore.Middlewares.NoCacheMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.AspNetCore.Middlewares.NoCacheMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataTelemetryIOMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataTelemetryIOMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.V4.NavODataPartnerTelemetryMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.V4.NavODataPartnerTelemetryMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestTracingMiddleware.InvokeAsync(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dynamics.Nav.Service.OData.NavODataRequestTracingMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.HttpSys.RequestContext`1.ExecuteAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.HttpSys.RequestContext`1.ExecuteAsync()
   at Microsoft.AspNetCore.Server.HttpSys.RequestContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()


ProcessId: 2344
Tag: 0000KC5
ThreadId: 41
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 
```

**Screenshots**
```
![Screenshot 2023-07-27 110236](https://github.com/microsoft/navcontainerhelper/assets/28568480/c70e60ff-758c-4ec3-a628-c6a11335dd74)
![Screenshot 2023-07-27 110323](https://github.com/microsoft/navcontainerhelper/assets/28568480/23ca49e4-b35d-447a-8587-5cc4d8e1a655)
![Screenshot 2023-07-27 110930](https://github.com/microsoft/navcontainerhelper/assets/28568480/ce9995f4-a320-4f14-b836-2e5b36e90963)
```

**Additional context**
- does it happen all the time?
- Yes, based on our tests against the insider artifact, the 404 NOT FOUND error happens from image "https://bcinsider.azureedge.net/sandbox/22.3.58325.0/se" to "https://bcinsider.azureedge.net/sandbox/22.4.59056.0/se"

- did it use to work?
- Yes, this web service calling did work on image "https://bcinsider.azureedge.net/sandbox/22.3.57528.0/se"

We assume this could be caused by some bugs within the SE company introduced between image 22.3.57528.0 SE and 22.3.58325.0.

Thanks.

**Comment by freddydk** [comment]
Is the problem only with this page?
Or are there problems with other pages?
Is it only in the swedish version?

Thanks

**Comment by freddydk** [comment]
@yuhongxiangtheorigin

**Comment by AndreaSmiley95** [comment]
Yes, based on our tests against the insider artifact, the 404 NOT FOUND error happens from image "https://bcinsider.azureedge.net/sandbox/22.3.58325.0/se" to "https://bcinsider.azureedge.net/sandbox/22.4.59056.0/se"

did it use to work?

Yes, this web service calling did work on image "https://bcinsider.azureedge.net/sandbox/22.3.57528.0/se"

We assume this could be caused by some bugs within the SE company introduced between image 22.3.57528.0 SE and 22.3.58325.0.

The customer has other entities that are working - only their swedish entity is having an issue.

**Comment by yuhongxiangtheorigin** [comment]
1. Yes, based on our testing, including page ID. 50 (Purchase Order), this error also happens on web service which binding to page ID. 49 (Purchase Quote), ID. 51 (Purchase Invoice), ID. 52 (Puchase Credit Memo.).
2. Yes, as far as we know, this problem only happens in swedish version.

Thanks.

**Comment by yuhongxiangtheorigin** [comment]
@freddydk 
More info attached.

Thanks.

**Comment by freddydk** [comment]
No extra info attached???
I just noticed memorylimit 3G, which is definitely not enough to run BC - please try this with 6G or more
It would also help to get the full output and the postman script or PS script you use to show the error on the container coming out of that script.

**Comment by yuhongxiangtheorigin** [comment]
![Screenshot 2023-07-27 110236](https://github.com/microsoft/navcontainerhelper/assets/28568480/fd50e19a-8a86-4366-8f6c-bbe08a451e2d)
As you can see, we bind the page of Purchase Order as a odatav4 service.

![Screenshot 2023-07-27 110323](https://github.com/microsoft/navcontainerhelper/assets/28568480/27384d0a-2142-4900-b60c-629f2f88b227)
But it reports as HTTP ERROR 404.

![Screenshot 2023-07-27 110930](https://github.com/microsoft/navcontainerhelper/assets/28568480/052d019f-9bbe-40db-a85c-6e4dafd5db6f)
So far, as we tried, this error still happens on the insider image for SE 22.4.59056.0.

**Comment by yuhongxiangtheorigin** [comment]
I am not sure if this is the right repo to submit this issue, also it seems this error is not related to the bc container helper module.  
It is more like a base app or system app bug.

Freddy, could you please suggest which repo could be the correct one for us to copy this issue to?

Thanks.

**Comment by freddydk** [comment]
I have a repro now - I have filed a bug in our internal system and will await an answer.

**Comment by yuhongxiangtheorigin** [comment]
Thank you so much @freddydk , we will be waiting on the fix.

**Comment by PredragMaricic** [comment]
The fix has now been submitted. The HF will be deployed for 22.3 and 22.4.

**Comment by freddydk** [comment]
Just tested the latest 22.4 - works there.
