### ISSUE TITLE
Not able to Enable SSL in oData and/or SOAP in business central server instance version 22.4 

### ISSUE THREAD

**Issue by keshavsrivastav** [microsoft/navcontainerhelper#3323]
Not able to Enable SSL in oData and/or SOAP in business central server instance version 22.4 

While enabling the SSL for SOAP and/or Odata in business central version 22.4 instance and restarting the NAServerInstance then i am getting the error:

Script:
**Set-NAVServerConfiguration -ServerInstance Production -KeyName odataservicesSSLEnabled -KeyValue false
Set-NAVServerConfiguration -ServerInstance Production -KeyName ODataServicesSSLEnabled -KeyValue true
Restart-NAVServerInstance -ServerInstance Production**
```

```
Error
**Restart-NAVServerInstance : ServerInstance 'MicrosoftDynamicsNavServer$Production' failed to reach  status 'Running' on this 
server due to the following error: 'Cannot start the service.'. Additional information may be in the event log of the server.
At line:1 char:1
+ Restart-NAVServerInstance -ServerInstance Production
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Restart-NAVServerInstance], NavServerInstanceException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$Production,Microsoft.Dynamics.Nav.Management.Cmdlets.RestartNavServerIns 
   tance**
```

Event Viewer log:
Server instance: Production
Tenant ID: 
Environment Name: 
Environment Type: 
User: 
Type: Microsoft.AspNetCore.Server.HttpSys.HttpSysException
ErrorCode: 183
NativeErrorCode: 183
Message: The prefix 'https://+:5047/Production/' is already registered.
Source: Microsoft.AspNetCore.Server.HttpSys
HResult: -2147467259
StackTrace:
     at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
     at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
     at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start()
     at Microsoft.AspNetCore.Server.HttpSys.MessagePump.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
     at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
     at Microsoft.AspNetCore.Hosting.WebHost.Start()
     at Microsoft.Dynamics.Nav.Service.AspNetCore.AspNetCoreApiHost.StartInternal()
     at Microsoft.Dynamics.Nav.Service.AspNetCore.AspNetCoreApiHost.Open()
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartOwinServices()
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartAllServices(ServerUserSettings settings)
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.OnStart(String[] args, ServiceBase serviceBase)
     at Microsoft.Dynamics.Nav.WindowsServices.WindowsService.NavWindowsServiceLifetime.OnStart(String[] args)
     at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
  --- End of stack trace from previous location ---
     at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
     at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
     at Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.Run()
  --- End of stack trace from previous location ---
     at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
     at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
     at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
     at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
     at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)
StackTrace:
     at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId)
     at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup)
     at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start()
     at Microsoft.AspNetCore.Server.HttpSys.MessagePump.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
     at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
     at Microsoft.AspNetCore.Hosting.WebHost.Start()
     at Microsoft.Dynamics.Nav.Service.AspNetCore.AspNetCoreApiHost.StartInternal()
     at Microsoft.Dynamics.Nav.Service.AspNetCore.AspNetCoreApiHost.Open()
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartOwinServices()
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartAllServices(ServerUserSettings settings)
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName)
     at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.OnStart(String[] args, ServiceBase serviceBase)
     at Microsoft.Dynamics.Nav.WindowsServices.WindowsService.NavWindowsServiceLifetime.OnStart(String[] args)
     at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
  --- End of stack trace from previous location ---
     at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
     at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
     at Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceLifetime.Run()
  --- End of stack trace from previous location ---
     at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
     at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
     at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
     at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
     at Microsoft.Dynamics.Nav.WindowsServices.DynamicsNavServer.Main(String[] args)


Please suggest solution for this error.

Thank you in advance.

**Comment by freddydk** [comment]
What script did you use to start the container?

**Comment by keshavsrivastav** [comment]
@freddydk, i have used 

Restart-NAVServerInstance -ServerInstance Production

**Comment by freddydk** [comment]
My question was targeting how you created the container in the first place - not how you restart it.
I assume you found a solution to your problem?
It is good practice to write in the issue what your problem was, for other people to find and resolve similar issues in the same way.
Thanks

**Comment by keshavsrivastav** [comment]
Hello @freddydk ,

I've set up the Business Central server instance using the following command:
New-NAVServerInstance '' -ManagementServicesPort 0000 -ClientServicesPort 0000 -DatabaseServer '**' -DatabaseName '***' -DeveloperServicesPort 0000 -ClientServicesCredentialType AccessControlService

The problem I encountered was with server ports already being registered to an HTTP URL. To resolve this, I used the netsh command (netsh http delete urlacl url=http://***********/) to delete that HTTP link. After restarting the server instance, the issue was resolved.

Thanks for prompt response.

**Comment by keshavsrivastav** [comment]
Hello @freddydk ,

I've set up the Business Central server instance using the following command:
New-NAVServerInstance '' -ManagementServicesPort 0000 -ClientServicesPort 0000 -DatabaseServer '**' -DatabaseName '***' -DeveloperServicesPort 0000 -ClientServicesCredentialType AccessControlService

The problem I encountered was with server ports already being registered to an HTTP URL. To resolve this, I used the netsh command (netsh http delete urlacl url=http://***********/) to delete that HTTP link. After restarting the server instance, the issue was resolved.

Thanks for prompt response.

**Comment by freddydk** [comment]
Please don't reply on a closed topic.
Please open a new issue and include the full script with which you have created your container in the first place.
If you are not using containers, then this is the wrong place for your issue - you should try other forums or like.
