### ISSUE TITLE
Dev License

### ISSUE THREAD

**Issue by adrianordonez** [Microsoft/navcontainerhelper#409]
When i try tu publish an extension i get the error "The request for path /NAV/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: Your program license does not allow you to publish 'GRWPagExtPacWebServiceDetails'."

this is in a server with a container, i search online and it appears is my license but i do not know how to get my dev license, i work for a partner

My extensions add a new field to a existing table and add the field to a page everything compiles good

**Comment by freddydk** [comment]
You can use the free object ranges (from 50000 to 99999) if you do not have a developer license.
Else you will need to get a developer license from partner central (I think) - I have never tried to create/download a license myself - all partners should have information on how to do this.
The Developer license will contain permissions to specific object id ranges which belongs to the partner.

**Comment by adrianordonez** [comment]
i am using the range 50500 to 50600 when i try to publish i got the next error "[2019-04-04 12:20:26.04] Sending request to http://bcgravitas:7049/NAV/dev/apps?SchemaUpdateMode=recreate
[2019-04-04 12:20:37.51] The request for path /NAV/dev/apps?SchemaUpdateMode=recreate failed with code 422. Reason: Your program license does not allow you to publish 'GRWPagExtPacWebServiceDetails'." even when i am using the free range thats why i am asking where can i download the doc FIF

**Comment by freddydk** [comment]
As you probably can see I have no idea where you download a partner license - this is something partners do - not us - and in general, I know very little about Licensing.
I do however think I was wrong before - the only objects which are included in the demo license (which you use if you don't provide a license) is 50100 to 50149 (I think)
try to use this and see if this works - else you will need to talk to somebody who has downloaded licenses before - I haven't - sorry.

**Comment by adrianordonez** [comment]
Thanks for the reply i change my ids and now i get the next error "[2019-04-04 12:43:24.33] Sending request to http://bcgravitas:7049/NAV/dev/apps?SchemaUpdateMode=recreate
[2019-04-04 12:43:26.39] Error: An internal error has occurred" i change my app fiel i put the "showMyCode": true, parameter compile with F6 and i get the following 

Success: The package is created.
[2019-04-04 12:44:59.59] Sending request to http://bcgravitas:7049/NAV/dev/apps?SchemaUpdateMode=recreate
[Error - 12:45:01 PM] Please report this issue to https://github.com/microsoft/al/issues including information on how to reproduce it, if possible.
Processing of message 'al/openPageDesigner' failed with error: 'Object reference not set to an instance of an object.'
StackTrace:
   at Microsoft.Dynamics.Nav.Deployment.Publishing.Publisher.<SendPackage>d__6.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Publishing\Publisher.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.Deployment.Publishing.Publisher.<Publish>d__5.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.Deployment\Publishing\Publisher.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.OpenPageDesignerRequestHandler.<ProcessRequestAsync>d__3.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\OpenPageDesignerRequestHandler.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.LanguageServer.Extensions.NavServerRequestHandler`1.<HandleAsync>d__5.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\LanguageServer\Extensions\NavServerRequestHandler.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.RequestRegistry.<Process>d__6.MoveNext() in C:\a\130\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Endpoints\RequestRegistry.cs:line 59

**Comment by freddydk** [comment]
Did you try to restart VS Code - it might be confused.

**Comment by adrianordonez** [comment]
Yes and i got the same error

**Comment by freddydk** [comment]
I know you got moved to the docker issues list, but this really have nothing to do with Docker, so I will transfer you back to AL issues, sorry about the confusion.
