### ISSUE TITLE
bcsandbox docker container with AAD auth

### ISSUE THREAD

**Issue by pzentner** [Microsoft/navcontainerhelper#441]
I created a new container (using navcontainerhelper 0.6.0.14) and set it up with AAD auth. I am using the latest microsoft/bcsandbox:us as the image. I then use the Create-AadAppsForNav commandlet to create the app.

When I try to sign on, I get authenticated properly to the AD and it goes back to the sign in page for BC and then I receive "An error has occurred". Nothing else. In the event log, I see the following

Error accessing Website 
Type: System.InvalidOperationException
Message: Incorrect Content-Type: 
StackTrace:
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at Microsoft.Dynamics.Nav.WebClient.Controllers.AuthenticationController.<SignIn>d__6.MoveNext() in s:\repo\src\platform\client\web\Prod.Client.WebCoreApp\Controllers\AuthenticationController.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
Source: Microsoft.AspNetCore.Http

Any guidance as to what is missing or what is happening?

thank you

Peter

**Comment by freddydk** [comment]
Did you reconfigure Service Tier and Web Client with the information returned from Create-AadApps...?

**Comment by pzentner** [comment]
I have double and triple checked the configuration and I do think that I have updated everything.

**Comment by freddydk** [comment]
The code I use in the ARM templates is here: https://github.com/Microsoft/nav-arm-templates/blob/master/SetupNavContainer.ps1

Look at these lines:
```
        $AdProperties = Create-AadAppsForNav -AadAdminCredential $Office365Credential -appIdUri $publicWebBaseUrl -IncludeExcelAadApp -IncludePowerBiAadApp
        $auth = "AAD"
'Write-Host "Changing Server config to NavUserPassword to enable basic web services"
Set-NAVServerConfiguration -ServerInstance nav -KeyName "ClientServicesCredentialType" -KeyValue "NavUserPassword" -WarningAction Ignore
Set-NAVServerConfiguration -ServerInstance nav -KeyName "ExcelAddInAzureActiveDirectoryClientId" -KeyValue "'+$AdProperties.ExcelAdAppId+'" -WarningAction Ignore
Set-NAVServerConfiguration -ServerInstance nav -KeyName "ValidAudiences" -KeyValue "'+$AdProperties.SsoAdAppId+'" -WarningAction Ignore -ErrorAction Ignore
' | Add-Content "c:\myfolder\SetupConfiguration.ps1"
```
Which basically sets up the aad apps and adds a setupconfiguration with the right parameters to the script overrides.

/Freddy

**Comment by pzentner** [comment]
Thank you Freddy. By removing the container and redoing everything again and then doing only the setups that you did (I believe it was the valid audience that was missing, but still didn't work) it started working in the new container.

I'll close this then, since it was user error I think.
