### ISSUE TITLE
"Error while copying content to a stream" when Run-TestsInBCContainer

### ISSUE THREAD

**Issue by dejfidson** [microsoft/navcontainerhelper#701]
I tried to run Run-TestsInBCContainer script but it failed.

Here is a script to create bc container:

```
import-module navcontainerhelper

$imageName = "mcr.microsoft.com/businesscentral/onprem:cz-ltsc2019"
$containerName = "bctester"
$licenseFile = "C:\Docker\SharedFolder\License.flf"
$auth = "NavUserPassword"
$credential =  New-Object pscredential 'admin', (ConvertTo-SecureString -String 'Pass.1234' -AsPlainText -Force)

New-BCContainer     -accept_eula `
                    -containerName $containerName `
                    -imageName $imageName `
                    -licenseFile $licenseFile `
                    -Auth $auth `
                    -Credential $credential `
                    -doNotExportObjectsToText `
                    -includeTestToolkit `
                    -updateHosts `
                    -dns '8.8.8.8' 
```
Result of this script:

```
NavContainerHelper is version 0.6.4.15
Host is Microsoft Windows 10 Enterprise - 1903
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Using image mcr.microsoft.com/businesscentral/onprem:cz-ltsc2019
Removing bctester from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bctester
Creating Container bctester
Version: 15.0.36560.0-cz
Style: onprem
Platform: 15.0.36510.0
Generic Tag: 0.0.9.95
Container OS Version: 10.0.17763.737 (ltsc2019)
Host OS Version: 10.0.18362.418 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale cs-CZ
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Docker\SharedFolder\License.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\bctester\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container bctester from image mcr.microsoft.com/businesscentral/onprem:cz-ltsc2019
4fa6c11d81403d92ccad899373caab23a363ecc966af1f272641fc1540afb139
Waiting for container bctester to be ready
Initializing...
Starting Container
Hostname is bctester
PublicDnsName is bctester
WARNING: Container starts with TimeZone = Střední Evropa (běžný čas), which is not recognized in the list of TimeZones.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 2E5E5F380878BD230431DECCAEE39B170A49A57A
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.30.131.126
Container Hostname  : bctester
Container Dns Name  : bctester
Web Client          : http://bctester/BC/
Dev. Server         : http://bctester
Dev. ServerInstance : BC

Files:
http://bctester:8080/al-4.0.176004.vsix

Initialization took 124 seconds
Ready for connections!
Reading CustomSettings.config from bctester
Creating Desktop Shortcuts for bctester
Copy from container bctester (C:\Applications\TestFramework\TestLibraries\Any\Microsoft_Any.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Any.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Any.app
Synchronizing Any on tenant default
Installing Any on tenant default
App successfully published
Copy from container bctester (C:\Applications\TestFramework\TestLibraries\Assert\Microsoft_Library Assert.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Library Assert.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Library Assert.app
Synchronizing Library Assert on tenant default
Installing Library Assert on tenant default
App successfully published
Copy from container bctester (C:\Applications\TestFramework\TestRunner\Microsoft_Test Runner.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Test Runner.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Test Runner.app
Synchronizing Test Runner on tenant default
Installing Test Runner on tenant default
App successfully published
Copy from container bctester (C:\Applications\System Application\Test\Microsoft_System Application Test Library.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_System Application Test Library.app
Synchronizing System Application Test Library on tenant default
Installing System Application Test Library on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-TestLibraries.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-TestLibraries.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-TestLibraries.app
Synchronizing Tests-TestLibraries on tenant default
Installing Tests-TestLibraries on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Bank.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Bank.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Bank.app
Synchronizing Tests-Bank on tenant default
Installing Tests-Bank on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Cash Flow.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Cash Flow.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Cash Flow.app
Synchronizing Tests-Cash Flow on tenant default
Installing Tests-Cash Flow on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Cost Accounting.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Cost Accounting.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Cost Accounting.app
Synchronizing Tests-Cost Accounting on tenant default
Installing Tests-Cost Accounting on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-CRM integration.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-CRM integration.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-CRM integration.app
Synchronizing Tests-CRM integration on tenant default
Installing Tests-CRM integration on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Data Exchange.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Data Exchange.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Data Exchange.app
Synchronizing Tests-Data Exchange on tenant default
Installing Tests-Data Exchange on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Dimension.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Dimension.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Dimension.app
Synchronizing Tests-Dimension on tenant default
Installing Tests-Dimension on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-ERM.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-ERM.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-ERM.app
Synchronizing Tests-ERM on tenant default
Installing Tests-ERM on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Fixed Asset.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Fixed Asset.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Fixed Asset.app
Synchronizing Tests-Fixed Asset on tenant default
Installing Tests-Fixed Asset on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-General Journal.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-General Journal.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-General Journal.app
Synchronizing Tests-General Journal on tenant default
Installing Tests-General Journal on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Graph.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Graph.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Graph.app
Synchronizing Tests-Graph on tenant default
Installing Tests-Graph on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Integration.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Integration.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Integration.app
Synchronizing Tests-Integration on tenant default
Installing Tests-Integration on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Invoicing.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Invoicing.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Invoicing.app
Synchronizing Tests-Invoicing on tenant default
Installing Tests-Invoicing on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Job.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Job.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Job.app
Synchronizing Tests-Job on tenant default
Installing Tests-Job on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Local.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Local.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Local.app
Synchronizing Tests-Local on tenant default
Installing Tests-Local on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Misc.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Misc.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Misc.app
Synchronizing Tests-Misc on tenant default
Installing Tests-Misc on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Permissions.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Permissions.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Permissions.app
Synchronizing Tests-Permissions on tenant default
Installing Tests-Permissions on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Physical Inventory.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Physical Inventory.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Physical Inventory.app
Synchronizing Tests-Physical Inventory on tenant default
Installing Tests-Physical Inventory on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Prepayment.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Prepayment.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Prepayment.app
Synchronizing Tests-Prepayment on tenant default
Installing Tests-Prepayment on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Rapid Start.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Rapid Start.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Rapid Start.app
Synchronizing Tests-Rapid Start on tenant default
Installing Tests-Rapid Start on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Report.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Report.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Report.app
Synchronizing Tests-Report on tenant default
Installing Tests-Report on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Resource.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Resource.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Resource.app
Synchronizing Tests-Resource on tenant default
Installing Tests-Resource on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Reverse.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Reverse.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Reverse.app
Synchronizing Tests-Reverse on tenant default
Installing Tests-Reverse on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-SCM.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-SCM.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-SCM.app
Synchronizing Tests-SCM on tenant default
Installing Tests-SCM on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-SMB.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-SMB.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-SMB.app
Synchronizing Tests-SMB on tenant default
Installing Tests-SMB on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-SMTP.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-SMTP.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-SMTP.app
Synchronizing Tests-SMTP on tenant default
Installing Tests-SMTP on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Upgrade.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Upgrade.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Upgrade.app
Synchronizing Tests-Upgrade on tenant default
Installing Tests-Upgrade on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-User.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-User.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-User.app
Synchronizing Tests-User on tenant default
Installing Tests-User on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-VAT.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-VAT.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-VAT.app
Synchronizing Tests-VAT on tenant default
Installing Tests-VAT on tenant default
App successfully published
Copy from container bctester (C:\Applications\BaseApp\Test\Microsoft_Tests-Workflow.app) to C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Workflow.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\bctester\_Microsoft_Tests-Workflow.app
Synchronizing Tests-Workflow on tenant default
Installing Tests-Workflow on tenant default
App successfully published
TestToolkit successfully imported
Container bctester successfully created
bctester is running!
```

Then I run this script:

```
import-module navcontainerhelper

$containerName = "bctester"
$xunitResultsFile = "c:\programdata\navcontainerhelper\Tests-Local-results.xml"
$credential =  New-Object pscredential 'admin', (ConvertTo-SecureString -String 'Pass.1234' -AsPlainText -Force)
$app = Get-NavContainerAppInfo $containerName | Where-Object { $_.Name -eq "Tests-Local" }
Run-TestsInBCContainer `
    -containerName $containerName `
    -credential $credential `
    -detailed `
    -XUnitResultFileName $xunitResultsFile `
    -extensionId $app.AppId
```
But this error occur:

```
CommunicationError : Error while copying content to a stream.
CommunicationError InnerException : System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.<>c__DisplayClass15_0.<EndInvokeInteractions>b__0() in s:\repo\src\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\JsonHttpClient.cs:line 299
   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action) in s:\repo\src\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\JsonHttpClient.cs:line 182
ClientSession State is InError (Wait time 5 seconds)
at AwaitState, C:\ProgramData\NavContainerHelper\Extensions\bctester\PsTestTool-4\ClientContext.ps1: line 179
at InvokeInteraction, C:\ProgramData\NavContainerHelper\Extensions\bctester\PsTestTool-4\ClientContext.ps1: line 197
at InvokeInteractionAndCatchForm, C:\ProgramData\NavContainerHelper\Extensions\bctester\PsTestTool-4\ClientContext.ps1: line 206
at OpenForm, C:\ProgramData\NavContainerHelper\Extensions\bctester\PsTestTool-4\ClientContext.ps1: line 221
at Run-Tests, C:\ProgramData\NavContainerHelper\Extensions\bctester\PsTestTool-4\PsTestFunctions.ps1: line 281
at <ScriptBlock>, <No file>: line 49
ClientSession State is InError (Wait time 5 seconds)
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.15\AppHandling\Run-TestsInNavContainer.ps1:368 char:17
+                 throw $_.Exception.Message
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ClientSession S...time 5 seconds):String) [], RuntimeException
    + FullyQualifiedErrorId : ClientSession State is InError (Wait time 5 seconds)
```

**Comment by freddydk** [comment]
I assume that this happens every time? and immediately?
Could you try to add -debugMode and -connectFromHost to your run-tests line?

**Comment by dejfidson** [comment]
Yes it happens every time. What is the immediately? It will happen after 10 - 15 seconds.
I tried to add -debufMode and -connectFromHost but the result is the same.

**Comment by freddydk** [comment]
We are looking after a problem on your setup.
I copy/pasted you exact script and it works here, so you are not looking for a problem in that.
![image](https://user-images.githubusercontent.com/10775043/68060082-32c2d480-fcff-11e9-94c9-9e8d2c75b9cb.png)
Are you running any kind of endpoint-protection, antivirus software?

**Comment by dejfidson** [comment]
Yes I have antivirus software. Could that be a problem?

**Comment by freddydk** [comment]
You could try to disable it temporarily - we have seen antivirus and endpoint protection give strange problems - and your script runs without any modifications on my box.

**Comment by dejfidson** [comment]
Ok. It's a little problem because I can't disable that due to our internal policy. So I will close this issue. Thanks
