### ISSUE TITLE
OnPrem Installation Error BC140/BC150 fails with error concerning Event Log access

### ISSUE THREAD

**Issue by ReneGubler** [microsoft/navcontainerhelper#739]
We installed a new Windows Server 2019 and tried to install BC140/BC150

When the installer tries to start the NST Service we got allot of error messages in the application event log.

I saw the same error in https://github.com/microsoft/navcontainerhelper/issues/504  but its concerning docker. 

We are using a domain user to run the service. This user is local admin. We also tried to use a domain admin but it also failed. We also tried to use the network service. As far as I can remember, we had this issue with NAV 2013 if the user was not local admin. 

**Error Messages:**

- The description for Event ID 218 from source MicrosoftDynamicsNavServer$BC150 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

- The description for Event ID 712 from source MicrosoftDynamicsNavServer$BC150 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

- The description for Event ID 705 from source MicrosoftDynamicsNavServer$BC150 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

- The description for Event ID 218 from source MicrosoftDynamicsNavServer$BC150 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

- The description for Event ID 701 from source MicrosoftDynamicsNavServer$BC150 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

**Detailes Error Message (first error) **
The description for Event ID 218 from source MicrosoftDynamicsNavServer$BC150 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: BC150
Tenant ID: 
Environment Name: 
Environment Type: 
User: 
Type: System.Data.SqlClient.SqlException
ClientConnectionId: 5878c57b-4097-4e9c-890b-2fb796317ae6
Class: 11
LineNumber: 65536
Number: 4060
Server: ALD-SVW-SQL01\SQL2017
State: 1
Source: .Net SqlClient Data Provider
ErrorCode: -2146232060
Message:
  Cannot open database "Demo Database BC (15-0)" requested by the login. The login failed.
  Login failed for user 'ALPHA\admin.rgu'.
StackTrace:
     at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
     at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
     at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
     at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
     at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
     at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
     at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
     at System.Data.SqlClient.SqlConnection.Open()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.TryConnect()
HResult: -2146232060
StackTrace:
     at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
     at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
     at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
     at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
     at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
     at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
     at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
     at System.Data.SqlClient.SqlConnection.Open()
     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.TryConnect()

The message resource is present but the message was not found in the message table

Best regards
René

**Comment by git-no** [comment]
Can you post your installation script, please.

**Comment by freddydk** [comment]
This issues list is for docker related issues only, am I right in  assuming that this is non-docker?

However - the error seems to be the connection to the SQL Server:
```
Cannot open database "Demo Database BC (15-0)" requested by the login. The login failed.
Login failed for user 'ALPHA\admin.rgu'.
```
Without database connection - all else fails.
