### ISSUE TITLE
Import-ObjectsToNavContainer extreme long runtime

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/navcontainerhelper#829]
I am importing a fob file with around 8000 objects into a "mcr.microsoft.com/businesscentral/onprem:14.8.38658.0-de-ltsc2019" container.

Currently it is running since one and half hours. Strange thing is that the container does not seem to do anything. No CPU usage at all. 
In C/SIDE I can see the changes already but if I cancel the import the changes are rolled back.

navcontainerhelper version is: **0.6.4.25**

These are the params:
```
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -doNotExportObjectsToText `
                 -useBestContainerOS `
                 -updateHosts `
                 -shortcuts DesktopFolder `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters `
                 -memoryLimit 8G `
                 -accept_outdated `
                 -enableSymbolLoading `
                 -includeCSide
```

**Comment by freddydk** [comment]
Strange.
Import-ObjectsToNavContainer is just launching finsql.exe to do the import.
Is there any virus scanner or like that is running?
Maybe you can try to remove -usebestcontaineros and instead use -isolation hyperv - so see if that changes anything.

**Comment by StefanMaron** [comment]
View days ago I started this in evening and in the morning it was finished. I can repeat that today and check if the event log contains anything interesting.

**Comment by StefanMaron** [comment]
The whole import process took around 3.5 hours.
In the event log I can see one error which occours every 40 seconds:

```
Fehler beim Zugriff auf die Website 
Type: System.TimeoutException
StackTrace:

Server stack trace: 
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Dynamics.Nav.Types.IHealthService.IsSystemHealthy()
   at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult,TChannel](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`3 operationWithContext, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\platform\client\web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 359
   at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.Execute[TResult,TChannel](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`2 localExceptionHandler) in s:\repo\src\platform\client\web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 235
   at Microsoft.Dynamics.Nav.Client.Web.SystemHealthChecker.IsSystemHealthyAsync() in s:\repo\src\platform\client\web\Prod.Client.WebCommon\Services\SystemHealth\SystemHealthChecker.cs:line 35
   at Microsoft.Dynamics.Nav.Client.Web.ThrottledSystemHealthChecker.<CheckHealthAndUpdateState>d__12.MoveNext() in s:\repo\src\platform\client\web\Prod.Client.WebCommon\Services\SystemHealth\ThrottledSystemHealthChecker.cs:line 150
Source: mscorlib----------------------------------
Type: System.TimeoutException
StackTrace:
   at System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)
   at System.ServiceModel.Channels.SocketConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.DelegatingConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
Source: System.ServiceModel----------------------------------
Type: System.Net.Sockets.SocketException
StackTrace:
   at System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)
Source: System.ServiceModel
```

**Comment by freddydk** [comment]
That looks like healthcheck is failing.
HealthCheck is running every 30 seconds with a timeout of 10 seconds = 40 sec...
Could you try to start the container with -doNotCheckHealth

Then I will try to create the same container and investigate why healthcheck is failing,

**Comment by freddydk** [comment]
Did this fix the issue?

**Comment by freddydk** [comment]
Will close the issue, please reopen with more information if the problem persists

**Comment by StefanMaron** [comment]
It did fix the issue, thank you!
