### ISSUE TITLE
Unable to sign into business central sandbox

### ISSUE THREAD

**Issue by syssolmarketing** [microsoft/navcontainerhelper#832]
![error](https://user-images.githubusercontent.com/54630609/73774111-74757800-4751-11ea-8923-eb78ecedf220.png)
When we type in our credentials it simply tells us that an error has occurred. 

Created through mcr.microsoft.com/businesscentral/sandbox:us

We haven't seen this error until the other day, certificate was expired so I had assumed that was causing this error. I have since successfully recertified but still can't log in. Thanks for your help

**Comment by freddydk** [comment]
any thing in the eventlog?
get-navcontainereventlog -containerName <containername>

**Comment by syssolmarketing** [comment]
@freddydk I will check that. What's the best way to get the container name?

**Comment by freddydk** [comment]
You named the container when creating it.
get-navcontainers
will show you a list of running containers.

**Comment by syssolmarketing** [comment]
Eventlog:

The description for Event ID 0 from source MicrosoftDynamicsNAVClientWebClient cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Error accessing Website 
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavLicenseViolationException
StackTrace:
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectFailedEventArgs connectFailedArgs, ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, SpnSetting spnSettingToTry, Boolean allowSpnSettingsSwap, UserSettings& userSettings) in s:\repo\src\platform\client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 379
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectFailedEventArgs connectFailedArgs, ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, SpnSetting spnSettingToTry, Boolean allowSpnSettingsSwap, UserSettings& userSettings) in s:\repo\src\platform\client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 438
   at Microsoft.Dynamics.Nav.Client.ConnectionEstablisher.OpenConnection[TChannel](ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, UserSettings& userSettings) in s:\repo\src\platform\client\Shared\Prod.Client.ServiceConnection\ConnectionEstablisher.cs:line 218
   at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.SimpleServerOperationConnectionEstablisher.OpenConnection[TChannel](ConnectionRequest connectionRequest, ConnectionOptions connectionOptions, UserSettings& userSettings) in s:\repo\src\platform\client\web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 179
   at Microsoft.Dynamics.Nav.Client.Web.SimpleServerOperation.ExecuteCore[TResult,TChannel](RequestContext requestContext, ConnectionOptions serverConnectionOptions, Func`2 operation, Func`3 operationWithContext, Func`2 localExceptionHandler, Int32 retryCount) in s:\repo\src\platform\client\web\Prod.Client.WebCommon\Security\SimpleServerOperation.cs:line 299
Source: Microsoft.Dynamics.Nav.Client.ServiceConnection----------------------------------
Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavLicenseViolationException
StackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavSession.LicenseHandler(ObjectType objType, Int32 objNo, Boolean isLicenseFile, Boolean isWarning, NavDate expiryDate, NavDate today, String expireText)
   at Microsoft.Dynamics.Nav.Runtime.NavSession.LicenseExpiryHandler(UInt16 objType, Int32 objNo, Boolean isLicenseFile, Boolean isWarning, NavDate expiryDate, NavDate today, String expireText)
   at Microsoft.Dynamics.Nav.Runtime.NavLicense.GetLicensePermissionMask(ObjectType objType, Int32 objNo, NavDate today)
   at Microsoft.Dynamics.Nav.Runtime.NavLicense.CheckExpired(NavDate today)
   at Microsoft.Dynamics.Nav.Runtime.NavLicense.CheckIsValid(NavDate today)
   at Microsoft.Dynamics.Nav.Runtime.NavLicense.CheckIsValid()
   at Microsoft.Dynamics.Nav.Runtime.NavSession.SetAndValidateLicense(Byte[] licenseToUse)
   at Microsoft.Dynamics.Nav.Runtime.NavSession.Open(Boolean useUserPersonalization, Byte[] licenseToUse, Boolean allowAppsDisabledMode)
   at Microsoft.Dynamics.Nav.Service.NSService.OpenConnection(ConnectionRequest connectionRequest)
   at SyncInvokeOpenConnection(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
Source: Microsoft.Dynamics.Nav.Ncl

**Comment by freddydk** [comment]
You can use Import-NavContainerLicense to import a new license to the container or recreate the container with a new license.
I assume that will fix the issue,

**Comment by syssolmarketing** [comment]
@freddydk fixed, thanks for all your help.
